--------------------------------------------------------
--  DDL for Trigger TRG_SLS$SO
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "SLS"."TRG_SLS$SO" 
AFTER UPDATE OR DELETE ON SLS$SO
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
BEGIN
 IF UPDATING THEN
 INSERT INTO trc.SLS$SO_TRC
(ADV_PAY_FLG,AMD_DT,AMD_NO,ASSIGNED_TO,CASH_CUST_ADDS,CASH_CUST_NM,CASH_SALES_VOU_ID,CLD_ID,CLS_RSN,COA_ID,COGS_VOU_ID,CURR_CONV_FCTR,CURR_ID_BS,CURR_ID_SP,DISC_PERC,DISC_TYPE,DISC_VAL,DLV_TYPE,DOC_DT,DOC_ID,DRFT_SO_ID,EO_CATG_ID,EO_ID,EO_PRICE_PLC,EXT_DOC_DT,EXT_DOC_NO,FY_ID,HOLD_TILL_DT,HO_ORG_ID,INS_AMT,ORDER_STAT,ORDER_TYPE,ORG_ID,PAYMNT_VOU_ID,PRJ_ID,QUOT_ID,REF_DOC_SPLIT_SRC,REF_SO_DOC_ID,REF_TYP_SRC,REMARKS,SCH_FLG,SHIP_ADDS,SHIP_TO_ADDS,SHIP_TO_NM,SLOC_ID,SO_BASIS,SO_CONTRACT_BASIS,SO_CONTRACT_PRICE,SO_CONTRACT_QTY,SO_CONTRACT_VALUE,SO_DOC_ORIGIN_ORG,SO_DOC_TXN_ID_SRC,SO_DOC_TYP_SRC,SO_ID,SO_MODE,SO_SUB_TYPE,SO_VLDT_DT,SPLIT_FLG,TAX_AFTER_DISC_FLG,TAX_FORM_TYP_ID,TAX_RULE_FLG,TLRNC_DAYS,TMPL_DOC_ID,TOT_AMT_BS,TOT_AMT_SP,TOT_ITM_AMT_GS_BS,TOT_ITM_AMT_GS_SP,TRANS_VH_NO,USR_ID_CREATE,USR_ID_CREATE_DT,USR_ID_MOD,USR_ID_MOD_DT,WH_ID,row_add_dt, statmnt_type, user_nm, usr_ipaddr)
 VALUES
 (:NEW.ADV_PAY_FLG,:NEW.AMD_DT,:NEW.AMD_NO,:NEW.ASSIGNED_TO,:NEW.CASH_CUST_ADDS,:NEW.CASH_CUST_NM,:NEW.CASH_SALES_VOU_ID,:NEW.CLD_ID,:NEW.CLS_RSN,:NEW.COA_ID,:NEW.COGS_VOU_ID,:NEW.CURR_CONV_FCTR,:NEW.CURR_ID_BS,:NEW.CURR_ID_SP,:NEW.DISC_PERC,:NEW.DISC_TYPE,:NEW.DISC_VAL,:NEW.DLV_TYPE,:NEW.DOC_DT,:NEW.DOC_ID,:NEW.DRFT_SO_ID,:NEW.EO_CATG_ID,:NEW.EO_ID,:NEW.EO_PRICE_PLC,:NEW.EXT_DOC_DT,:NEW.EXT_DOC_NO,:NEW.FY_ID,:NEW.HOLD_TILL_DT,:NEW.HO_ORG_ID,:NEW.INS_AMT,:NEW.ORDER_STAT,:NEW.ORDER_TYPE,:NEW.ORG_ID,:NEW.PAYMNT_VOU_ID,:NEW.PRJ_ID,:NEW.QUOT_ID,:NEW.REF_DOC_SPLIT_SRC,:NEW.REF_SO_DOC_ID,:NEW.REF_TYP_SRC,:NEW.REMARKS,:NEW.SCH_FLG,:NEW.SHIP_ADDS,:NEW.SHIP_TO_ADDS,:NEW.SHIP_TO_NM,:NEW.SLOC_ID,:NEW.SO_BASIS,:NEW.SO_CONTRACT_BASIS,:NEW.SO_CONTRACT_PRICE,:NEW.SO_CONTRACT_QTY,:NEW.SO_CONTRACT_VALUE,:NEW.SO_DOC_ORIGIN_ORG,:NEW.SO_DOC_TXN_ID_SRC,:NEW.SO_DOC_TYP_SRC,:NEW.SO_ID,:NEW.SO_MODE,:NEW.SO_SUB_TYPE,:NEW.SO_VLDT_DT,:NEW.SPLIT_FLG,:NEW.TAX_AFTER_DISC_FLG,:NEW.TAX_FORM_TYP_ID,:NEW.TAX_RULE_FLG,:NEW.TLRNC_DAYS,:NEW.TMPL_DOC_ID,:NEW.TOT_AMT_BS,:NEW.TOT_AMT_SP,:NEW.TOT_ITM_AMT_GS_BS,:NEW.TOT_ITM_AMT_GS_SP,:NEW.TRANS_VH_NO,:NEW.USR_ID_CREATE,:NEW.USR_ID_CREATE_DT,:NEW.USR_ID_MOD,:NEW.USR_ID_MOD_DT,:NEW.WH_ID,SYSTIMESTAMP,'U','SLS',(SELECT SYS_CONTEXT('USERENV','IP_ADDRESS') FROM DUAL));
END IF;
 IF DELETING THEN
 INSERT INTO trc.SLS$SO_TRC
(ADV_PAY_FLG,AMD_DT,AMD_NO,ASSIGNED_TO,CASH_CUST_ADDS,CASH_CUST_NM,CASH_SALES_VOU_ID,CLD_ID,CLS_RSN,COA_ID,COGS_VOU_ID,CURR_CONV_FCTR,CURR_ID_BS,CURR_ID_SP,DISC_PERC,DISC_TYPE,DISC_VAL,DLV_TYPE,DOC_DT,DOC_ID,DRFT_SO_ID,EO_CATG_ID,EO_ID,EO_PRICE_PLC,EXT_DOC_DT,EXT_DOC_NO,FY_ID,HOLD_TILL_DT,HO_ORG_ID,INS_AMT,ORDER_STAT,ORDER_TYPE,ORG_ID,PAYMNT_VOU_ID,PRJ_ID,QUOT_ID,REF_DOC_SPLIT_SRC,REF_SO_DOC_ID,REF_TYP_SRC,REMARKS,SCH_FLG,SHIP_ADDS,SHIP_TO_ADDS,SHIP_TO_NM,SLOC_ID,SO_BASIS,SO_CONTRACT_BASIS,SO_CONTRACT_PRICE,SO_CONTRACT_QTY,SO_CONTRACT_VALUE,SO_DOC_ORIGIN_ORG,SO_DOC_TXN_ID_SRC,SO_DOC_TYP_SRC,SO_ID,SO_MODE,SO_SUB_TYPE,SO_VLDT_DT,SPLIT_FLG,TAX_AFTER_DISC_FLG,TAX_FORM_TYP_ID,TAX_RULE_FLG,TLRNC_DAYS,TMPL_DOC_ID,TOT_AMT_BS,TOT_AMT_SP,TOT_ITM_AMT_GS_BS,TOT_ITM_AMT_GS_SP,TRANS_VH_NO,USR_ID_CREATE,USR_ID_CREATE_DT,USR_ID_MOD,USR_ID_MOD_DT,WH_ID,row_add_dt, statmnt_type, user_nm, usr_ipaddr)  VALUES  (:OLD.ADV_PAY_FLG,:OLD.AMD_DT,:OLD.AMD_NO,:OLD.ASSIGNED_TO,:OLD.CASH_CUST_ADDS,:OLD.CASH_CUST_NM,:OLD.CASH_SALES_VOU_ID,:OLD.CLD_ID,:OLD.CLS_RSN,:OLD.COA_ID,:OLD.COGS_VOU_ID,:OLD.CURR_CONV_FCTR,:OLD.CURR_ID_BS,:OLD.CURR_ID_SP,:OLD.DISC_PERC,:OLD.DISC_TYPE,:OLD.DISC_VAL,:OLD.DLV_TYPE,:OLD.DOC_DT,:OLD.DOC_ID,:OLD.DRFT_SO_ID,:OLD.EO_CATG_ID,:OLD.EO_ID,:OLD.EO_PRICE_PLC,:OLD.EXT_DOC_DT,:OLD.EXT_DOC_NO,:OLD.FY_ID,:OLD.HOLD_TILL_DT,:OLD.HO_ORG_ID,:OLD.INS_AMT,:OLD.ORDER_STAT,:OLD.ORDER_TYPE,:OLD.ORG_ID,:OLD.PAYMNT_VOU_ID,:OLD.PRJ_ID,:OLD.QUOT_ID,:OLD.REF_DOC_SPLIT_SRC,:OLD.REF_SO_DOC_ID,:OLD.REF_TYP_SRC,:OLD.REMARKS,:OLD.SCH_FLG,:OLD.SHIP_ADDS,:OLD.SHIP_TO_ADDS,:OLD.SHIP_TO_NM,:OLD.SLOC_ID,:OLD.SO_BASIS,:OLD.SO_CONTRACT_BASIS,:OLD.SO_CONTRACT_PRICE,:OLD.SO_CONTRACT_QTY,:OLD.SO_CONTRACT_VALUE,:OLD.SO_DOC_ORIGIN_ORG,:OLD.SO_DOC_TXN_ID_SRC,:OLD.SO_DOC_TYP_SRC,:OLD.SO_ID,:OLD.SO_MODE,:OLD.SO_SUB_TYPE,:OLD.SO_VLDT_DT,:OLD.SPLIT_FLG,:OLD.TAX_AFTER_DISC_FLG,:OLD.TAX_FORM_TYP_ID,:OLD.TAX_RULE_FLG,:OLD.TLRNC_DAYS,:OLD.TMPL_DOC_ID,:OLD.TOT_AMT_BS,:OLD.TOT_AMT_SP,:OLD.TOT_ITM_AMT_GS_BS,:OLD.TOT_ITM_AMT_GS_SP,:OLD.TRANS_VH_NO,:OLD.USR_ID_CREATE,:OLD.USR_ID_CREATE_DT,:OLD.USR_ID_MOD,:OLD.USR_ID_MOD_DT,:OLD.WH_ID,SYSTIMESTAMP,'D','SLS',(SELECT SYS_CONTEXT('USERENV','IP_ADDRESS') FROM DUAL));
END IF;
 END;










/
ALTER TRIGGER "SLS"."TRG_SLS$SO" ENABLE;
