--------------------------------------------------------
--  DDL for Trigger TRG_CC$_SLS_TRNP_VHCL_REG_DTL_
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "SLS"."TRG_CC$_SLS_TRNP_VHCL_REG_DTL_" After insert or delete or update on SLS.SLS$TRNP$VHCL$REG$DTL for each row BEGIN  CASE WHEN INSERTING THEN  APP.PROC_INS_UPD_CC(:NEW.ORG_ID,:NEW.HO_ORG_ID,:NEW.CLD_ID,:NEW.SLOC_ID,:NEW.VHCL_REG_NO,:NEW.VHCL_REG_NO,NULL,'I',343835,:NEW.ACTV);  WHEN UPDATING THEN  APP.PROC_INS_UPD_CC(:NEW.ORG_ID,:NEW.HO_ORG_ID,:NEW.CLD_ID,:NEW.SLOC_ID,:NEW.VHCL_REG_NO,:NEW.VHCL_REG_NO, NULL,'U',343835,:NEW.ACTV);  WHEN DELETING THEN  APP.PROC_INS_UPD_CC(:OLD.ORG_ID,:OLD.HO_ORG_ID,:OLD.CLD_ID,:OLD.SLOC_ID,:OLD.VHCL_REG_NO,:OLD.VHCL_REG_NO,NULL,'D',343835,:OLD.ACTV); END CASE; EXCEPTION WHEN OTHERS THEN NULL; END; 









/
ALTER TRIGGER "SLS"."TRG_CC$_SLS_TRNP_VHCL_REG_DTL_" ENABLE;
