--------------------------------------------------------
--  DDL for Trigger TRG_CC$_SLS_TRNP_VHCL_PRF_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "SLS"."TRG_CC$_SLS_TRNP_VHCL_PRF_TRG" 
	After insert or delete or update on SLS.SLS$TRNP$VHCL$PRF
	  for each row BEGIN
		CASE
		  WHEN INSERTING
			THEN
			  APP.PROC_INS_UPD_CC(:NEW.HO_ORG_ID,:NEW.HO_ORG_ID,:NEW.CLD_ID,:NEW.SLOC_ID,:NEW.VHCL_ITM_ID,:NEW.VHCL_DESC,NULL,'I',343833,:NEW.ACTV);
		  WHEN UPDATING
			THEN
			  APP.PROC_INS_UPD_CC(:NEW.HO_ORG_ID,:NEW.HO_ORG_ID,:NEW.CLD_ID,:NEW.SLOC_ID,:NEW.VHCL_ITM_ID,:NEW.VHCL_DESC, NULL,'U',343833,:NEW.ACTV);
		  WHEN DELETING
			THEN
			  APP.PROC_INS_UPD_CC(:OLD.HO_ORG_ID,:OLD.HO_ORG_ID,:OLD.CLD_ID,:NEW.SLOC_ID,:NEW.VHCL_ITM_ID,:NEW.VHCL_DESC,NULL,'D',343833,:NEW.ACTV);
	  END CASE;

	  EXCEPTION WHEN OTHERS THEN NULL;
	END;




















/
ALTER TRIGGER "SLS"."TRG_CC$_SLS_TRNP_VHCL_PRF_TRG" ENABLE;
