--------------------------------------------------------
--  DDL for Procedure FN_GET_SMS_DTLS_ON_SHIPMNT
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "SLS"."FN_GET_SMS_DTLS_ON_SHIPMNT" (
		P_SLOC_ID   IN NUMBER ,
		P_CLD_ID    IN VARCHAR2,
		P_HO_ORG_ID IN VARCHAR2,
		P_ORG_ID    IN VARCHAR2,
		P_SHIPNMT_TXN_ID VARCHAR2,
		P_PHNO OUT VARCHAR2,
		P_SMS_MSG OUT VARCHAR2 )
AS
	VAR_SO_DISP_ID   VARCHAR2(50);
	VAR_SHIP_DISP_ID VARCHAR2(50);
BEGIN
	BEGIN
		SELECT C.SO_ID,D.EO_PHONE
		INTO VAR_SO_DISP_ID,P_PHNO
		FROM
			(SELECT A.CLD_ID,A.SLOC_ID,A.HO_ORG_ID,
				A.SO_ID,A.DOC_ID,A.ASSIGNED_TO
			FROM SLS.SLS$SO A
			WHERE A.DOC_ID IN
				(SELECT SO_ID
				FROM SLS.SLS$SHIPMNT$ITM B
				WHERE B.SLOC_ID  = P_SLOC_ID
					AND B.CLD_ID    = P_CLD_ID
					AND B.ORG_ID    = P_ORG_ID
					AND B.HO_ORG_ID = P_HO_ORG_ID
					AND B.DOC_ID    = P_SHIPNMT_TXN_ID
				)
			) C ,APP.APP$EO$PERS$COMM D
		WHERE C.CLD_ID     = D.EO_CLD_ID
			AND C.SLOC_ID     = D.EO_SLOC_ID
			AND C.HO_ORG_ID   = D.EO_HO_ORG_ID
			AND C.ASSIGNED_TO = D.EO_ID;
		--AND D.DFLT_EMAIL  = 'Y';
		SELECT A.SHIPMNT_ID
		INTO VAR_SHIP_DISP_ID
		FROM SLS$SHIPMNT$HDR A
		WHERE A.CLD_ID   = P_CLD_ID
			AND A.SLOC_ID   = P_SLOC_ID
			AND A.ORG_ID    = P_ORG_ID
			AND A.HO_ORG_ID = P_HO_ORG_ID
			AND A.DOC_ID    = P_SHIPNMT_TXN_ID;
	EXCEPTION
	WHEN OTHERS THEN
		NULL;
	END;
	DBMS_OUTPUT.PUT_LINE(P_PHNO);
	IF P_PHNO  IS NOT NULL THEN
		P_SMS_MSG := 'Shipment No. '||VAR_SHIP_DISP_ID||' have been generated against Sales Order No. '||VAR_SO_DISP_ID;
	END IF;
END;

/

  GRANT EXECUTE ON "SLS"."FN_GET_SMS_DTLS_ON_SHIPMNT" TO PUBLIC;
