--------------------------------------------------------
--  DDL for Procedure PROC_WMS_VHCL_SCHDL_NOT_INFO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "SLS"."PROC_WMS_VHCL_SCHDL_NOT_INFO" (
		P_CLD_ID      IN VARCHAR2 ,
		P_SLOC_ID     IN NUMBER,
		P_ORG_ID      IN VARCHAR2,
		P_HO_ORG_ID   IN VARCHAR2,
    P_USR_ID      IN NUMBER,
		P_VHCL_DOC_ID IN VARCHAR2,
		P_WMS_DVC_ID OUT SYS_REFCURSOR)
AS
	/**
	* CREATED BY  : AG
	* DATE    :  26-04-2018
	* PURPOSE   : PROCEDURE USED FOR FETCHING DATA FOR SENDING NOTIFICATION ON MOBILE DEVICE
	* COMMENT : THIS PROCEDURE NEEDS TO CHANGED FOR PUSHING DATA IN WMS DEVICE
	**/

	BEGIN
  OPEN P_WMS_DVC_ID FOR
SELECT 'TITLE' AS KEY, 'Vehical Schedule' AS VALUE FROM DUAL
UNION
SELECT 'MESSAGE' AS KEY, 'Vehical Schedule is pending for Pick. Please Process Vehical Schedule' AS VALUE FROM DUAL
UNION
SELECT 'PROCESSID' AS KEY, '21506' AS VALUE FROM DUAL
;
	END PROC_WMS_VHCL_SCHDL_NOT_INFO;

/

  GRANT EXECUTE ON "SLS"."PROC_WMS_VHCL_SCHDL_NOT_INFO" TO PUBLIC;
