--------------------------------------------------------
--  DDL for Procedure PROC_WMS_VHCL_SCHDL_DVC_INFO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "SLS"."PROC_WMS_VHCL_SCHDL_DVC_INFO" (
		P_CLD_ID      IN VARCHAR2 ,
		P_SLOC_ID     IN NUMBER ,
		P_ORG_ID      IN VARCHAR2 ,
		P_HO_ORG_ID   IN VARCHAR2 ,
		P_VHCL_DOC_ID IN VARCHAR2 ,
		P_WMS_DVC_ID OUT SYS_REFCURSOR)
AS
	V_USR_ID     NUMBER (5) ;
	V_TASK_ALLCT NUMBER (5) ;
	V_WH_ID      VARCHAR2 (40) ;
BEGIN
	BEGIN
		SELECT DISTINCT
				A.WH_ID
			INTO
				V_WH_ID
			FROM
				SLS$TRNP$VHCL$SCHDL$PROD A
			WHERE
				A.CLD_ID    = P_CLD_ID AND
				A.SLOC_ID   = P_SLOC_ID AND
				A.ORG_ID    = P_ORG_ID AND
				A.HO_ORG_ID = P_HO_ORG_ID AND
				A.DOC_ID    = P_VHCL_DOC_ID;
	EXCEPTION
	WHEN OTHERS THEN
		V_WH_ID := NULL;
	END;
	BEGIN
		SELECT DISTINCT USR_ID , MAX (TASK_ALLCT) INTO V_USR_ID , V_TASK_ALLCT FROM APP.WH$SEC$WMS$USR WHERE WH_ID = V_WH_ID AND IS_LOGD_IN = 'Y' AND IS_PRSNT = 'Y' AND ROWNUM = 1 GROUP BY USR_ID;
	EXCEPTION
	WHEN OTHERS THEN
		V_USR_ID     := NULL;
		V_TASK_ALLCT := NULL;
	END;
	BEGIN
  --- TMS ID 62679 DVC_ID WHAREHOUSE SECURITY AND PICK LIST ACCESS ADDED IN WHARE CLAUSE  --ANAND KUMAR 22-08-2018
		OPEN P_WMS_DVC_ID FOR SELECT  DISTINCT APP_AUTH_KEY AUTH_KEY ,
DVC_ID FROM APP.APP$WMS$USR$DVC B ,APP.APP$GLBL$DOC C,APP.APP$SEC$USR$MNU D,APP.WH$SEC$USR E
WHERE B.USR_ID = V_USR_ID AND DVC_ACTV = 'Y' AND B.LOGIN_STAT='Y'
    AND  C.GLBL_DOC_ID = D.USR_MNU_ID
        AND D.USR_CLD_ID = P_CLD_ID
        AND D.SLOC_ID = P_SLOC_ID
        AND D.USR_ID = D.USR_ID
        AND D.USR_MNU_ID = 9005 --PICK LIST GLBL DOC _ID FOR WMS
        AND D.USR_CLD_ID = E.CLD_ID
        AND D.SLOC_ID = E.SLOC_ID
        AND E.ORG_ID = P_ORG_ID
        AND B.USR_ID = E.USR_ID
        AND E.WH_ID = V_WH_ID;

	END;
	BEGIN
		UPDATE APP.WH$SEC$WMS$USR SET TASK_ALLCT = V_TASK_ALLCT + 1 WHERE CLD_ID = P_CLD_ID AND SLOC_ID = P_SLOC_ID AND ORG_ID = P_ORG_ID AND WH_ID = V_WH_ID AND USR_ID = V_USR_ID;
	END;
	BEGIN
		INSERT INTO APP.WH$SEC$WMS$USR$DTL
				(CLD_ID , SLOC_ID , ORG_ID , USR_ID , WH_ID , DFLT_WH , IS_PRSNT , IS_LOGD_IN , TASK_ALLCT , VHCL_SCHDL_ID
				)
		SELECT
				CLD_ID   , SLOC_ID    , ORG_ID     ,
				USR_ID   , WH_ID      , DFLT_WH    ,
				IS_PRSNT , IS_LOGD_IN , TASK_ALLCT ,
				P_VHCL_DOC_ID
			FROM
				APP.WH$SEC$WMS$USR
			WHERE
				CLD_ID  = P_CLD_ID AND
				SLOC_ID = P_SLOC_ID AND
				ORG_ID  = P_ORG_ID AND
				USR_ID  = V_USR_ID AND
				WH_ID   = V_WH_ID AND
				NOT EXISTS
				(SELECT 1 FROM APP.WH$SEC$WMS$USR$DTL WHERE CLD_ID = P_CLD_ID AND SLOC_ID = P_SLOC_ID AND ORG_ID = P_ORG_ID AND USR_ID = V_USR_ID AND WH_ID = V_WH_ID
				) ;
	END;
EXCEPTION
WHEN OTHERS THEN
	RAISE_APPLICATION_ERROR ( - 20005 , SUBSTR (DBMS_UTILITY.FORMAT_ERROR_STACK , 1 , 400) ||SUBSTR (DBMS_UTILITY.FORMAT_ERROR_BACKTRACE , 1 , 600)) ;
END PROC_WMS_VHCL_SCHDL_DVC_INFO;

/

  GRANT EXECUTE ON "SLS"."PROC_WMS_VHCL_SCHDL_DVC_INFO" TO PUBLIC;
