--------------------------------------------------------
--  DDL for Table APP$GLBL$UPL$EO$PRICE
--------------------------------------------------------

  CREATE TABLE "SLS"."APP$GLBL$UPL$EO$PRICE" 
   (	"ORG" VARCHAR2(100 BYTE), 
	"HO_ORG" VARCHAR2(100 BYTE), 
	"ITM_DESC" VARCHAR2(100 BYTE), 
	"ITM_ID" VARCHAR2(50 BYTE), 
	"BASE_PRICE" NUMBER(26,6), 
	"MIN_PRICE" NUMBER(26,6), 
	"MRP_TYP" VARCHAR2(1 BYTE), 
	"MRP_RATE" NUMBER(26,6), 
	"MRP_ADD_SUB" VARCHAR2(1 BYTE), 
	"TOT_MRP_RATE" NUMBER(26,6), 
	"MRP_PRICE" NUMBER(26,6), 
	"ADD_MRP_TYP" VARCHAR2(1 BYTE), 
	"ADD_MRP_RATE" NUMBER(26,6), 
	"ADD_MRP_ADD_SUB" VARCHAR2(1 BYTE), 
	"ADD_TOT_MRP_RATE" NUMBER(26,6), 
	"ADD_MRP_PRICE" NUMBER(26,6), 
	"EFFECTIVE_DT" TIMESTAMP (8), 
	"EXPIRY_DT" TIMESTAMP (8), 
	"ITM_UOM" VARCHAR2(20 BYTE), 
	"PSFL_STATUS" VARCHAR2(1 BYTE), 
	"FL_REM" VARCHAR2(4000 BYTE)
   ) ;
  GRANT ALTER ON "SLS"."APP$GLBL$UPL$EO$PRICE" TO "APP";
  GRANT DELETE ON "SLS"."APP$GLBL$UPL$EO$PRICE" TO "APP";
  GRANT INDEX ON "SLS"."APP$GLBL$UPL$EO$PRICE" TO "APP";
  GRANT INSERT ON "SLS"."APP$GLBL$UPL$EO$PRICE" TO "APP";
  GRANT SELECT ON "SLS"."APP$GLBL$UPL$EO$PRICE" TO "APP";
  GRANT UPDATE ON "SLS"."APP$GLBL$UPL$EO$PRICE" TO "APP";
  GRANT REFERENCES ON "SLS"."APP$GLBL$UPL$EO$PRICE" TO "APP";
  GRANT ON COMMIT REFRESH ON "SLS"."APP$GLBL$UPL$EO$PRICE" TO "APP";
  GRANT QUERY REWRITE ON "SLS"."APP$GLBL$UPL$EO$PRICE" TO "APP";
  GRANT DEBUG ON "SLS"."APP$GLBL$UPL$EO$PRICE" TO "APP";
  GRANT FLASHBACK ON "SLS"."APP$GLBL$UPL$EO$PRICE" TO "APP";
  GRANT INSERT ON "SLS"."APP$GLBL$UPL$EO$PRICE" TO PUBLIC;
  GRANT SELECT ON "SLS"."APP$GLBL$UPL$EO$PRICE" TO PUBLIC;
  GRANT UPDATE ON "SLS"."APP$GLBL$UPL$EO$PRICE" TO PUBLIC;
