--------------------------------------------------------
--  DDL for Table APP$RPT$MDL$COL$PARA
--------------------------------------------------------

  CREATE TABLE "SLS"."APP$RPT$MDL$COL$PARA" 
   (	"MDL_CLD_ID" VARCHAR2(4 BYTE), 
	"MDL_SLOC_ID" NUMBER(2,0), 
	"MDL_ORG_ID" VARCHAR2(2 BYTE), 
	"MDL_ID" NUMBER(10,0), 
	"MDL_TAB_ID" VARCHAR2(50 BYTE), 
	"MDL_COL_NM" VARCHAR2(50 BYTE), 
	"MDL_COL_VSBL" VARCHAR2(1 BYTE), 
	"MDL_COL_SNO" NUMBER(10,0), 
	"MDL_COL_HEIGHT" NUMBER(5,0), 
	"MDL_COL_WIDTH" NUMBER(5,0), 
	"USR_ID_CREATE" NUMBER(10,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_MOD_ID" NUMBER(10,0), 
	"USR_MOD_DATE" DATE, 
	"MDL_COL_DESC" VARCHAR2(200 BYTE), 
	"MDL_COL_SUMM" VARCHAR2(1 BYTE), 
	"MDL_GRP_BY" VARCHAR2(1 BYTE), 
	"MDL_GRP_SNO" NUMBER(5,0), 
	"MDL_COL_SUM_FLG" VARCHAR2(1 BYTE)
   ) ;
  GRANT REFERENCES ON "SLS"."APP$RPT$MDL$COL$PARA" TO "FIN";
  GRANT QUERY REWRITE ON "SLS"."APP$RPT$MDL$COL$PARA" TO "SVC";
  GRANT QUERY REWRITE ON "SLS"."APP$RPT$MDL$COL$PARA" TO "MNF";
  GRANT QUERY REWRITE ON "SLS"."APP$RPT$MDL$COL$PARA" TO "MM";
  GRANT QUERY REWRITE ON "SLS"."APP$RPT$MDL$COL$PARA" TO "HCM";
  GRANT QUERY REWRITE ON "SLS"."APP$RPT$MDL$COL$PARA" TO "FIN";
  GRANT ON COMMIT REFRESH ON "SLS"."APP$RPT$MDL$COL$PARA" TO "SVC";
  GRANT ON COMMIT REFRESH ON "SLS"."APP$RPT$MDL$COL$PARA" TO "MNF";
  GRANT ON COMMIT REFRESH ON "SLS"."APP$RPT$MDL$COL$PARA" TO "MM";
  GRANT ON COMMIT REFRESH ON "SLS"."APP$RPT$MDL$COL$PARA" TO "HCM";
  GRANT ON COMMIT REFRESH ON "SLS"."APP$RPT$MDL$COL$PARA" TO "FIN";
  GRANT INSERT ON "SLS"."APP$RPT$MDL$COL$PARA" TO "SVC";
  GRANT INSERT ON "SLS"."APP$RPT$MDL$COL$PARA" TO "MNF";
  GRANT INSERT ON "SLS"."APP$RPT$MDL$COL$PARA" TO "MM";
  GRANT INSERT ON "SLS"."APP$RPT$MDL$COL$PARA" TO "HCM";
  GRANT INSERT ON "SLS"."APP$RPT$MDL$COL$PARA" TO "FIN";
  GRANT INDEX ON "SLS"."APP$RPT$MDL$COL$PARA" TO "SVC";
  GRANT INDEX ON "SLS"."APP$RPT$MDL$COL$PARA" TO "MNF";
  GRANT INDEX ON "SLS"."APP$RPT$MDL$COL$PARA" TO "MM";
  GRANT INDEX ON "SLS"."APP$RPT$MDL$COL$PARA" TO "HCM";
  GRANT INDEX ON "SLS"."APP$RPT$MDL$COL$PARA" TO "FIN";
  GRANT FLASHBACK ON "SLS"."APP$RPT$MDL$COL$PARA" TO "SVC";
  GRANT FLASHBACK ON "SLS"."APP$RPT$MDL$COL$PARA" TO "MNF";
  GRANT FLASHBACK ON "SLS"."APP$RPT$MDL$COL$PARA" TO "MM";
  GRANT FLASHBACK ON "SLS"."APP$RPT$MDL$COL$PARA" TO "HCM";
  GRANT FLASHBACK ON "SLS"."APP$RPT$MDL$COL$PARA" TO "FIN";
  GRANT DELETE ON "SLS"."APP$RPT$MDL$COL$PARA" TO "SVC";
  GRANT DELETE ON "SLS"."APP$RPT$MDL$COL$PARA" TO "MNF";
  GRANT DELETE ON "SLS"."APP$RPT$MDL$COL$PARA" TO "MM";
  GRANT DELETE ON "SLS"."APP$RPT$MDL$COL$PARA" TO "HCM";
  GRANT DELETE ON "SLS"."APP$RPT$MDL$COL$PARA" TO "FIN";
  GRANT DEBUG ON "SLS"."APP$RPT$MDL$COL$PARA" TO "SVC";
  GRANT DEBUG ON "SLS"."APP$RPT$MDL$COL$PARA" TO "MNF";
  GRANT DEBUG ON "SLS"."APP$RPT$MDL$COL$PARA" TO "MM";
  GRANT DEBUG ON "SLS"."APP$RPT$MDL$COL$PARA" TO "HCM";
  GRANT DEBUG ON "SLS"."APP$RPT$MDL$COL$PARA" TO "FIN";
  GRANT ALTER ON "SLS"."APP$RPT$MDL$COL$PARA" TO "SVC";
  GRANT ALTER ON "SLS"."APP$RPT$MDL$COL$PARA" TO "MNF";
  GRANT ALTER ON "SLS"."APP$RPT$MDL$COL$PARA" TO "MM";
  GRANT ALTER ON "SLS"."APP$RPT$MDL$COL$PARA" TO "HCM";
  GRANT ALTER ON "SLS"."APP$RPT$MDL$COL$PARA" TO "FIN";
  GRANT SELECT ON "SLS"."APP$RPT$MDL$COL$PARA" TO PUBLIC;
  GRANT INSERT ON "SLS"."APP$RPT$MDL$COL$PARA" TO PUBLIC;
  GRANT DEBUG ON "SLS"."APP$RPT$MDL$COL$PARA" TO PUBLIC;
  GRANT UPDATE ON "SLS"."APP$RPT$MDL$COL$PARA" TO PUBLIC;
  GRANT UPDATE ON "SLS"."APP$RPT$MDL$COL$PARA" TO "SVC";
  GRANT UPDATE ON "SLS"."APP$RPT$MDL$COL$PARA" TO "MNF";
  GRANT UPDATE ON "SLS"."APP$RPT$MDL$COL$PARA" TO "MM";
  GRANT UPDATE ON "SLS"."APP$RPT$MDL$COL$PARA" TO "HCM";
  GRANT UPDATE ON "SLS"."APP$RPT$MDL$COL$PARA" TO "FIN";
  GRANT SELECT ON "SLS"."APP$RPT$MDL$COL$PARA" TO "SVC";
  GRANT SELECT ON "SLS"."APP$RPT$MDL$COL$PARA" TO "MNF";
  GRANT SELECT ON "SLS"."APP$RPT$MDL$COL$PARA" TO "MM";
  GRANT REFERENCES ON "SLS"."APP$RPT$MDL$COL$PARA" TO "MM";
  GRANT SELECT ON "SLS"."APP$RPT$MDL$COL$PARA" TO "HCM";
  GRANT SELECT ON "SLS"."APP$RPT$MDL$COL$PARA" TO "FIN";
  GRANT REFERENCES ON "SLS"."APP$RPT$MDL$COL$PARA" TO "SVC";
  GRANT REFERENCES ON "SLS"."APP$RPT$MDL$COL$PARA" TO "MNF";
  GRANT REFERENCES ON "SLS"."APP$RPT$MDL$COL$PARA" TO "HCM";
  GRANT QUERY REWRITE ON "SLS"."APP$RPT$MDL$COL$PARA" TO "SVC" WITH GRANT OPTION;
  GRANT ON COMMIT REFRESH ON "SLS"."APP$RPT$MDL$COL$PARA" TO "SVC" WITH GRANT OPTION;
  GRANT REFERENCES ON "SLS"."APP$RPT$MDL$COL$PARA" TO "SVC" WITH GRANT OPTION;
  GRANT UPDATE ON "SLS"."APP$RPT$MDL$COL$PARA" TO "SVC" WITH GRANT OPTION;
  GRANT SELECT ON "SLS"."APP$RPT$MDL$COL$PARA" TO "SVC" WITH GRANT OPTION;
  GRANT INSERT ON "SLS"."APP$RPT$MDL$COL$PARA" TO "SVC" WITH GRANT OPTION;
  GRANT INDEX ON "SLS"."APP$RPT$MDL$COL$PARA" TO "SVC" WITH GRANT OPTION;
  GRANT DELETE ON "SLS"."APP$RPT$MDL$COL$PARA" TO "SVC" WITH GRANT OPTION;
  GRANT ALTER ON "SLS"."APP$RPT$MDL$COL$PARA" TO "SVC" WITH GRANT OPTION;
  GRANT FLASHBACK ON "SLS"."APP$RPT$MDL$COL$PARA" TO "MM" WITH GRANT OPTION;
  GRANT DEBUG ON "SLS"."APP$RPT$MDL$COL$PARA" TO "MM" WITH GRANT OPTION;
  GRANT QUERY REWRITE ON "SLS"."APP$RPT$MDL$COL$PARA" TO "MM" WITH GRANT OPTION;
  GRANT ON COMMIT REFRESH ON "SLS"."APP$RPT$MDL$COL$PARA" TO "MM" WITH GRANT OPTION;
  GRANT REFERENCES ON "SLS"."APP$RPT$MDL$COL$PARA" TO "MM" WITH GRANT OPTION;
  GRANT UPDATE ON "SLS"."APP$RPT$MDL$COL$PARA" TO "MM" WITH GRANT OPTION;
  GRANT SELECT ON "SLS"."APP$RPT$MDL$COL$PARA" TO "MM" WITH GRANT OPTION;
  GRANT INSERT ON "SLS"."APP$RPT$MDL$COL$PARA" TO "MM" WITH GRANT OPTION;
  GRANT INDEX ON "SLS"."APP$RPT$MDL$COL$PARA" TO "MM" WITH GRANT OPTION;
  GRANT DELETE ON "SLS"."APP$RPT$MDL$COL$PARA" TO "MM" WITH GRANT OPTION;
  GRANT ALTER ON "SLS"."APP$RPT$MDL$COL$PARA" TO "MM" WITH GRANT OPTION;
  GRANT SELECT ON "SLS"."APP$RPT$MDL$COL$PARA" TO "MNF" WITH GRANT OPTION;
  GRANT INSERT ON "SLS"."APP$RPT$MDL$COL$PARA" TO "MNF" WITH GRANT OPTION;
  GRANT SELECT ON "SLS"."APP$RPT$MDL$COL$PARA" TO "HCM" WITH GRANT OPTION;
  GRANT INSERT ON "SLS"."APP$RPT$MDL$COL$PARA" TO "HCM" WITH GRANT OPTION;
  GRANT INDEX ON "SLS"."APP$RPT$MDL$COL$PARA" TO "MNF" WITH GRANT OPTION;
  GRANT DELETE ON "SLS"."APP$RPT$MDL$COL$PARA" TO "MNF" WITH GRANT OPTION;
  GRANT UPDATE ON "SLS"."APP$RPT$MDL$COL$PARA" TO "MNF" WITH GRANT OPTION;
  GRANT REFERENCES ON "SLS"."APP$RPT$MDL$COL$PARA" TO "MNF" WITH GRANT OPTION;
  GRANT DEBUG ON "SLS"."APP$RPT$MDL$COL$PARA" TO "HCM" WITH GRANT OPTION;
  GRANT INDEX ON "SLS"."APP$RPT$MDL$COL$PARA" TO "HCM" WITH GRANT OPTION;
  GRANT ALTER ON "SLS"."APP$RPT$MDL$COL$PARA" TO "MNF" WITH GRANT OPTION;
  GRANT QUERY REWRITE ON "SLS"."APP$RPT$MDL$COL$PARA" TO "MNF" WITH GRANT OPTION;
  GRANT UPDATE ON "SLS"."APP$RPT$MDL$COL$PARA" TO "HCM" WITH GRANT OPTION;
  GRANT ON COMMIT REFRESH ON "SLS"."APP$RPT$MDL$COL$PARA" TO "MNF" WITH GRANT OPTION;
  GRANT DELETE ON "SLS"."APP$RPT$MDL$COL$PARA" TO "HCM" WITH GRANT OPTION;
  GRANT ON COMMIT REFRESH ON "SLS"."APP$RPT$MDL$COL$PARA" TO "HCM" WITH GRANT OPTION;
  GRANT QUERY REWRITE ON "SLS"."APP$RPT$MDL$COL$PARA" TO "HCM" WITH GRANT OPTION;
  GRANT DEBUG ON "SLS"."APP$RPT$MDL$COL$PARA" TO "MNF" WITH GRANT OPTION;
  GRANT ALTER ON "SLS"."APP$RPT$MDL$COL$PARA" TO "HCM" WITH GRANT OPTION;
  GRANT REFERENCES ON "SLS"."APP$RPT$MDL$COL$PARA" TO "HCM" WITH GRANT OPTION;
  GRANT FLASHBACK ON "SLS"."APP$RPT$MDL$COL$PARA" TO "HCM" WITH GRANT OPTION;
  GRANT FLASHBACK ON "SLS"."APP$RPT$MDL$COL$PARA" TO "MNF" WITH GRANT OPTION;
  GRANT FLASHBACK ON "SLS"."APP$RPT$MDL$COL$PARA" TO "APP" WITH GRANT OPTION;
  GRANT DEBUG ON "SLS"."APP$RPT$MDL$COL$PARA" TO "APP" WITH GRANT OPTION;
  GRANT QUERY REWRITE ON "SLS"."APP$RPT$MDL$COL$PARA" TO "APP" WITH GRANT OPTION;
  GRANT ON COMMIT REFRESH ON "SLS"."APP$RPT$MDL$COL$PARA" TO "APP" WITH GRANT OPTION;
  GRANT REFERENCES ON "SLS"."APP$RPT$MDL$COL$PARA" TO "APP" WITH GRANT OPTION;
  GRANT UPDATE ON "SLS"."APP$RPT$MDL$COL$PARA" TO "APP" WITH GRANT OPTION;
  GRANT SELECT ON "SLS"."APP$RPT$MDL$COL$PARA" TO "APP" WITH GRANT OPTION;
  GRANT INSERT ON "SLS"."APP$RPT$MDL$COL$PARA" TO "APP" WITH GRANT OPTION;
  GRANT INDEX ON "SLS"."APP$RPT$MDL$COL$PARA" TO "APP" WITH GRANT OPTION;
  GRANT DELETE ON "SLS"."APP$RPT$MDL$COL$PARA" TO "APP" WITH GRANT OPTION;
  GRANT ALTER ON "SLS"."APP$RPT$MDL$COL$PARA" TO "APP" WITH GRANT OPTION;
  GRANT FLASHBACK ON "SLS"."APP$RPT$MDL$COL$PARA" TO "FIN" WITH GRANT OPTION;
  GRANT REFERENCES ON "SLS"."APP$RPT$MDL$COL$PARA" TO "FIN" WITH GRANT OPTION;
  GRANT DEBUG ON "SLS"."APP$RPT$MDL$COL$PARA" TO "FIN" WITH GRANT OPTION;
  GRANT QUERY REWRITE ON "SLS"."APP$RPT$MDL$COL$PARA" TO "FIN" WITH GRANT OPTION;
  GRANT ON COMMIT REFRESH ON "SLS"."APP$RPT$MDL$COL$PARA" TO "FIN" WITH GRANT OPTION;
  GRANT INSERT ON "SLS"."APP$RPT$MDL$COL$PARA" TO "FIN" WITH GRANT OPTION;
  GRANT INDEX ON "SLS"."APP$RPT$MDL$COL$PARA" TO "FIN" WITH GRANT OPTION;
  GRANT SELECT ON "SLS"."APP$RPT$MDL$COL$PARA" TO "FIN" WITH GRANT OPTION;
  GRANT UPDATE ON "SLS"."APP$RPT$MDL$COL$PARA" TO "FIN" WITH GRANT OPTION;
  GRANT DELETE ON "SLS"."APP$RPT$MDL$COL$PARA" TO "FIN" WITH GRANT OPTION;
  GRANT ALTER ON "SLS"."APP$RPT$MDL$COL$PARA" TO "FIN" WITH GRANT OPTION;
  GRANT FLASHBACK ON "SLS"."APP$RPT$MDL$COL$PARA" TO PUBLIC;
  GRANT DEBUG ON "SLS"."APP$RPT$MDL$COL$PARA" TO PUBLIC;
  GRANT QUERY REWRITE ON "SLS"."APP$RPT$MDL$COL$PARA" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "SLS"."APP$RPT$MDL$COL$PARA" TO PUBLIC;
  GRANT REFERENCES ON "SLS"."APP$RPT$MDL$COL$PARA" TO PUBLIC;
  GRANT UPDATE ON "SLS"."APP$RPT$MDL$COL$PARA" TO PUBLIC;
  GRANT SELECT ON "SLS"."APP$RPT$MDL$COL$PARA" TO PUBLIC;
  GRANT INSERT ON "SLS"."APP$RPT$MDL$COL$PARA" TO PUBLIC;
  GRANT INDEX ON "SLS"."APP$RPT$MDL$COL$PARA" TO PUBLIC;
  GRANT DELETE ON "SLS"."APP$RPT$MDL$COL$PARA" TO PUBLIC;
  GRANT ALTER ON "SLS"."APP$RPT$MDL$COL$PARA" TO PUBLIC;
  GRANT FLASHBACK ON "SLS"."APP$RPT$MDL$COL$PARA" TO "SVC" WITH GRANT OPTION;
  GRANT DEBUG ON "SLS"."APP$RPT$MDL$COL$PARA" TO "SVC" WITH GRANT OPTION;
