--------------------------------------------------------
--  DDL for Table DUMMY3
--------------------------------------------------------

  CREATE TABLE "SLS"."DUMMY3" 
   (	"A" VARCHAR2(2 BYTE), 
	"B" NUMBER, 
	"C" VARCHAR2(50 BYTE), 
	"D" VARCHAR2(50 BYTE)
   ) ;
  GRANT QUERY REWRITE ON "SLS"."DUMMY3" TO PUBLIC;
  GRANT REFERENCES ON "SLS"."DUMMY3" TO PUBLIC;
  GRANT UPDATE ON "SLS"."DUMMY3" TO PUBLIC;
  GRANT SELECT ON "SLS"."DUMMY3" TO PUBLIC;
  GRANT INSERT ON "SLS"."DUMMY3" TO PUBLIC;
  GRANT INDEX ON "SLS"."DUMMY3" TO PUBLIC;
  GRANT DELETE ON "SLS"."DUMMY3" TO PUBLIC;
  GRANT ALTER ON "SLS"."DUMMY3" TO PUBLIC;
  GRANT FLASHBACK ON "SLS"."DUMMY3" TO PUBLIC;
  GRANT DEBUG ON "SLS"."DUMMY3" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "SLS"."DUMMY3" TO PUBLIC;
