--------------------------------------------------------
--  DDL for Table DUMMY1
--------------------------------------------------------

  CREATE TABLE "SLS"."DUMMY1" 
   (	"A" VARCHAR2(40 BYTE)
   ) ;
  GRANT ALTER ON "SLS"."DUMMY1" TO PUBLIC;
  GRANT FLASHBACK ON "SLS"."DUMMY1" TO PUBLIC;
  GRANT DEBUG ON "SLS"."DUMMY1" TO PUBLIC;
  GRANT QUERY REWRITE ON "SLS"."DUMMY1" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "SLS"."DUMMY1" TO PUBLIC;
  GRANT REFERENCES ON "SLS"."DUMMY1" TO PUBLIC;
  GRANT UPDATE ON "SLS"."DUMMY1" TO PUBLIC;
  GRANT SELECT ON "SLS"."DUMMY1" TO PUBLIC;
  GRANT INSERT ON "SLS"."DUMMY1" TO PUBLIC;
  GRANT INDEX ON "SLS"."DUMMY1" TO PUBLIC;
  GRANT DELETE ON "SLS"."DUMMY1" TO PUBLIC;
