--------------------------------------------------------
--  DDL for Table DUMMY
--------------------------------------------------------

  CREATE TABLE "SLS"."DUMMY" 
   (	"A" NUMBER
   ) ;
  GRANT DELETE ON "SLS"."DUMMY" TO PUBLIC;
  GRANT INDEX ON "SLS"."DUMMY" TO PUBLIC;
  GRANT INSERT ON "SLS"."DUMMY" TO PUBLIC;
  GRANT SELECT ON "SLS"."DUMMY" TO PUBLIC;
  GRANT UPDATE ON "SLS"."DUMMY" TO PUBLIC;
  GRANT REFERENCES ON "SLS"."DUMMY" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "SLS"."DUMMY" TO PUBLIC;
  GRANT QUERY REWRITE ON "SLS"."DUMMY" TO PUBLIC;
  GRANT DEBUG ON "SLS"."DUMMY" TO PUBLIC;
  GRANT FLASHBACK ON "SLS"."DUMMY" TO PUBLIC;
  GRANT ALTER ON "SLS"."DUMMY" TO PUBLIC;
