--------------------------------------------------------
--  DDL for Table PS_TXN
--------------------------------------------------------

  CREATE TABLE "SLS"."PS_TXN" 
   (	"ID" NUMBER(20,0), 
	"PARENTID" NUMBER(20,0), 
	"COLLID" NUMBER(10,0), 
	"CONTENT" BLOB, 
	"CREATION_DATE" DATE DEFAULT sysdate
   ) ;
  GRANT INSERT ON "SLS"."PS_TXN" TO PUBLIC;
  GRANT SELECT ON "SLS"."PS_TXN" TO PUBLIC;
  GRANT UPDATE ON "SLS"."PS_TXN" TO PUBLIC;
  GRANT REFERENCES ON "SLS"."PS_TXN" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "SLS"."PS_TXN" TO PUBLIC;
  GRANT QUERY REWRITE ON "SLS"."PS_TXN" TO PUBLIC;
  GRANT DEBUG ON "SLS"."PS_TXN" TO PUBLIC;
  GRANT FLASHBACK ON "SLS"."PS_TXN" TO PUBLIC;
  GRANT ALTER ON "SLS"."PS_TXN" TO PUBLIC;
  GRANT DELETE ON "SLS"."PS_TXN" TO PUBLIC;
  GRANT INDEX ON "SLS"."PS_TXN" TO PUBLIC;
