--------------------------------------------------------
--  DDL for Table SLS$SO$ITM$QC$PARAM
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$SO$ITM$QC$PARAM" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"ITM_ID" VARCHAR2(50 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"PARAM_ID" VARCHAR2(20 BYTE), 
	"PARAM_SPEC" VARCHAR2(100 BYTE), 
	"PARAM_TYPE" NUMBER(5,0), 
	"STD_VAL" NUMBER(26,6), 
	"TLRNC_LOWER" NUMBER(26,6), 
	"TLRNC_UPPER" NUMBER(26,6), 
	"TLRNC_TYPE" VARCHAR2(1 BYTE), 
	"FAIL_ACTN" NUMBER(5,0), 
	"LOWER_LIMIT" NUMBER(26,6), 
	"UPPER_LIMIT" NUMBER(26,6), 
	"USR_ID_CREATE" NUMBER(5,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(5,0), 
	"USR_ID_MOD_DT" DATE, 
	"ITM_SR_NO" NUMBER(10,0) DEFAULT 1
   ) ;
  GRANT UPDATE ON "SLS"."SLS$SO$ITM$QC$PARAM" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$SO$ITM$QC$PARAM" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$SO$ITM$QC$PARAM" TO PUBLIC;
