--------------------------------------------------------
--  DDL for Table SLS$TRNP$TB$ADJ
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$TRNP$TB$ADJ" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"COA_ID" NUMBER(20,0), 
	"GL_VOU_ID" VARCHAR2(40 BYTE), 
	"GL_VOU_DT" DATE, 
	"GL_AMT_SP" NUMBER(26,6), 
	"GL_AMT_BS" NUMBER(26,6), 
	"INV_AMT_ADJ" NUMBER(26,6), 
	"SR_NO" NUMBER(10,0), 
	"REMARKS" VARCHAR2(100 BYTE), 
	"CURR_ID_SP" NUMBER(10,0), 
	"CURR_CONV_FCTR" NUMBER(26,6), 
	"TRAN_TYPE" VARCHAR2(2 BYTE), 
	"AR_GL_SL_NO" NUMBER(10,0), 
	"AR_SL_NO" NUMBER(10,0), 
	"VOU_ID_DISP" VARCHAR2(20 BYTE), 
	"INV_AMT_OT" NUMBER(26,6), 
	"CURR_ID_SP_OLD" NUMBER(10,0), 
	"CURR_CONV_FCTR_OLD" NUMBER(26,6), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"CURR_ID_BS" NUMBER(10,0)
   ) ;
  GRANT INSERT ON "SLS"."SLS$TRNP$TB$ADJ" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$TRNP$TB$ADJ" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$TRNP$TB$ADJ" TO PUBLIC;
