--------------------------------------------------------
--  DDL for Table SLS$SUBC$INV
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$SUBC$INV" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"DOC_DT" DATE, 
	"EO_ID" NUMBER(20,0), 
	"SECU_AMT" NUMBER(26,6), 
	"ADV_AMT" NUMBER(26,6), 
	"RENEW_BASIS" NUMBER(5,0), 
	"FIXED_TERM_STRTDT" DATE, 
	"FIXED_TERM_ENDDT" DATE, 
	"RENEW_PRCNT" NUMBER(3,0), 
	"STRT_DT" DATE, 
	"END_DT" DATE, 
	"INV_TYPE" NUMBER(10,0), 
	"INV_SUB_TYPE" NUMBER(10,0), 
	"CONTACT_PERSON_BILL" VARCHAR2(100 BYTE), 
	"CONTACT_PERSON_TECH" VARCHAR2(100 BYTE), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"PROJ_ID" VARCHAR2(40 BYTE), 
	"SUBC_INV_DRFT_ID" VARCHAR2(40 BYTE), 
	"SUBC_INV_ID" VARCHAR2(40 BYTE), 
	"SUBC_INV_MODE" NUMBER(5,0), 
	"SUBC_INV_STATUS" NUMBER(5,0), 
	"FY_ID" NUMBER(5,0), 
	"COA_ID" NUMBER(5,0), 
	"SHIP_ADDS" VARCHAR2(20 BYTE), 
	"PNT_OF_SPLY" VARCHAR2(20 BYTE), 
	"PLC_OF_DLV" VARCHAR2(250 BYTE), 
	"CURR_ID_SP" NUMBER, 
	"BILL_ADDS" VARCHAR2(20 BYTE), 
	"CURR_ID_RATE" NUMBER, 
	"SLS_INV_ID" VARCHAR2(40 BYTE), 
	"REMARKS" VARCHAR2(250 BYTE), 
	"TOT_AMT_SP" NUMBER(26,6), 
	"TOT_AMT_BS" NUMBER(26,6)
   ) ;
  GRANT ALTER ON "SLS"."SLS$SUBC$INV" TO PUBLIC;
  GRANT DELETE ON "SLS"."SLS$SUBC$INV" TO PUBLIC;
  GRANT INDEX ON "SLS"."SLS$SUBC$INV" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$SUBC$INV" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$SUBC$INV" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$SUBC$INV" TO PUBLIC;
  GRANT REFERENCES ON "SLS"."SLS$SUBC$INV" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$SUBC$INV" TO PUBLIC;
  GRANT QUERY REWRITE ON "SLS"."SLS$SUBC$INV" TO PUBLIC;
  GRANT DEBUG ON "SLS"."SLS$SUBC$INV" TO PUBLIC;
  GRANT FLASHBACK ON "SLS"."SLS$SUBC$INV" TO PUBLIC;
