--------------------------------------------------------
--  DDL for Table SLS$QUOT$ITM$AMD
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$QUOT$ITM$AMD" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"DOC_DT" DATE, 
	"AMD_NO" VARCHAR2(40 BYTE), 
	"AMD_DT" DATE, 
	"ITM_ID" VARCHAR2(50 BYTE), 
	"ITM_PRICE" NUMBER(26,6), 
	"ITM_UOM" VARCHAR2(20 BYTE), 
	"QUOT_QTY" NUMBER(26,6), 
	"TLRNC_QTY_TYPE" VARCHAR2(1 BYTE), 
	"TLRNC_QTY_VAL" NUMBER(26,6), 
	"ITM_AMT_BS" NUMBER(26,6), 
	"ITM_AMT_SP" NUMBER(26,6), 
	"SCHM_ID" VARCHAR2(40 BYTE), 
	"ITM_DISC_TYP" VARCHAR2(1 BYTE), 
	"ITM_DISC_VAL" NUMBER(26,6), 
	"REMARKS" VARCHAR2(1000 BYTE), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"TAX_RULE_FLG" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"ITM_UOM_BS" VARCHAR2(20 BYTE), 
	"UOM_CONV_FCTR" NUMBER(26,6), 
	"ITM_QTY_BS" NUMBER(26,6), 
	"ITM_SR_NO" NUMBER(10,0) DEFAULT 1, 
	"WTY_ID" VARCHAR2(20 BYTE), 
	"AMC_FLG" VARCHAR2(1 BYTE), 
	"CNT_QTY" NUMBER(26,6) DEFAULT 0, 
	"ITM_COST_RATE" NUMBER(26,6) DEFAULT 0, 
	"ITM_BASIS" NUMBER(5,0) DEFAULT 869, 
	"INCL_TX" VARCHAR2(1 BYTE) DEFAULT 'N'
   ) ;
  GRANT DELETE ON "SLS"."SLS$QUOT$ITM$AMD" TO PUBLIC;
  GRANT ALTER ON "SLS"."SLS$QUOT$ITM$AMD" TO PUBLIC;
  GRANT FLASHBACK ON "SLS"."SLS$QUOT$ITM$AMD" TO PUBLIC;
  GRANT DEBUG ON "SLS"."SLS$QUOT$ITM$AMD" TO PUBLIC;
  GRANT QUERY REWRITE ON "SLS"."SLS$QUOT$ITM$AMD" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$QUOT$ITM$AMD" TO PUBLIC;
  GRANT REFERENCES ON "SLS"."SLS$QUOT$ITM$AMD" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$QUOT$ITM$AMD" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$QUOT$ITM$AMD" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$QUOT$ITM$AMD" TO PUBLIC;
  GRANT INDEX ON "SLS"."SLS$QUOT$ITM$AMD" TO PUBLIC;
