--------------------------------------------------------
--  DDL for Table SLS$RMA$SHIPMNT
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$RMA$SHIPMNT" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"DOC_DT" DATE DEFAULT (SYSDATE), 
	"SHIPMNT_ID" VARCHAR2(40 BYTE), 
	"SHIPMNT_DT" DATE, 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE
   ) ;
  GRANT DEBUG ON "SLS"."SLS$RMA$SHIPMNT" TO "APP";
  GRANT INSERT ON "SLS"."SLS$RMA$SHIPMNT" TO "APP";
  GRANT QUERY REWRITE ON "SLS"."SLS$RMA$SHIPMNT" TO "APP";
  GRANT REFERENCES ON "SLS"."SLS$RMA$SHIPMNT" TO "APP";
  GRANT SELECT ON "SLS"."SLS$RMA$SHIPMNT" TO "APP";
  GRANT FLASHBACK ON "SLS"."SLS$RMA$SHIPMNT" TO "APP";
  GRANT INDEX ON "SLS"."SLS$RMA$SHIPMNT" TO "APP";
  GRANT ALTER ON "SLS"."SLS$RMA$SHIPMNT" TO "APP";
  GRANT DELETE ON "SLS"."SLS$RMA$SHIPMNT" TO PUBLIC;
  GRANT ALTER ON "SLS"."SLS$RMA$SHIPMNT" TO PUBLIC;
  GRANT FLASHBACK ON "SLS"."SLS$RMA$SHIPMNT" TO PUBLIC;
  GRANT DEBUG ON "SLS"."SLS$RMA$SHIPMNT" TO PUBLIC;
  GRANT QUERY REWRITE ON "SLS"."SLS$RMA$SHIPMNT" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$RMA$SHIPMNT" TO PUBLIC;
  GRANT REFERENCES ON "SLS"."SLS$RMA$SHIPMNT" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$RMA$SHIPMNT" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$RMA$SHIPMNT" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$RMA$SHIPMNT" TO PUBLIC;
  GRANT INDEX ON "SLS"."SLS$RMA$SHIPMNT" TO PUBLIC;
  GRANT DELETE ON "SLS"."SLS$RMA$SHIPMNT" TO "APP";
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$RMA$SHIPMNT" TO "APP";
  GRANT UPDATE ON "SLS"."SLS$RMA$SHIPMNT" TO "APP";
