--------------------------------------------------------
--  DDL for Table SLS$CATG$DISC$ITM
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$CATG$DISC$ITM" 
   (	"CLD_ID" VARCHAR2(4 BYTE) DEFAULT 'no', 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"ITM_ID" VARCHAR2(50 BYTE), 
	"ITM_UOM" VARCHAR2(20 BYTE), 
	"LIST_PRICE" NUMBER(26,6), 
	"LOAD_VAL" NUMBER(26,6) DEFAULT 0, 
	"MAX_SCHM_PRC" NUMBER(26,6), 
	"END_CUST_PRC" NUMBER(26,6), 
	"MAX_DISC_PRCNT" NUMBER(26,6) DEFAULT 0, 
	"MAX_DISC_AMT" NUMBER(26,6), 
	"BASIC_CUST_PRC" NUMBER(26,6), 
	"BASIC_CUST_PRC_CALC" NUMBER(26,6), 
	"BASIC_CUST_PRC_FINAL" NUMBER(26,6), 
	"BASIC_CUST_PRC_ADJ" NUMBER(26,6), 
	"DISC_APLCBL_PRCNT" NUMBER(26,6), 
	"ENQ_FLG" VARCHAR2(1 BYTE), 
	"DISC_VAL" NUMBER(26,6), 
	"PEND_ADJ_AMT" NUMBER(26,6), 
	"DISC_ADJ_REMAIN" NUMBER(26,6), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE DEFAULT SYSDATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE
   ) ;

   COMMENT ON COLUMN "SLS"."SLS$CATG$DISC$ITM"."LIST_PRICE" IS 'List Price';
   COMMENT ON COLUMN "SLS"."SLS$CATG$DISC$ITM"."LOAD_VAL" IS 'Loading Applicable';
   COMMENT ON COLUMN "SLS"."SLS$CATG$DISC$ITM"."MAX_SCHM_PRC" IS 'Max Customer Price as per scheme';
   COMMENT ON COLUMN "SLS"."SLS$CATG$DISC$ITM"."END_CUST_PRC" IS 'End Customer  Price';
   COMMENT ON COLUMN "SLS"."SLS$CATG$DISC$ITM"."MAX_DISC_PRCNT" IS 'Max disc  Offer';
   COMMENT ON COLUMN "SLS"."SLS$CATG$DISC$ITM"."MAX_DISC_AMT" IS 'Max disc Amount';
   COMMENT ON COLUMN "SLS"."SLS$CATG$DISC$ITM"."BASIC_CUST_PRC" IS 'Dealer Basic';
   COMMENT ON COLUMN "SLS"."SLS$CATG$DISC$ITM"."BASIC_CUST_PRC_CALC" IS 'Dealer Basic with ceiling';
   COMMENT ON COLUMN "SLS"."SLS$CATG$DISC$ITM"."BASIC_CUST_PRC_FINAL" IS 'Dealer Basic Final';
   COMMENT ON COLUMN "SLS"."SLS$CATG$DISC$ITM"."BASIC_CUST_PRC_ADJ" IS 'Dealer Basic after adjustment';
   COMMENT ON COLUMN "SLS"."SLS$CATG$DISC$ITM"."DISC_APLCBL_PRCNT" IS 'Discount  Offer eligible %';
   COMMENT ON COLUMN "SLS"."SLS$CATG$DISC$ITM"."ENQ_FLG" IS 'Enquiry Ref.';
   COMMENT ON COLUMN "SLS"."SLS$CATG$DISC$ITM"."DISC_VAL" IS 'Discount Value Rs';
   COMMENT ON COLUMN "SLS"."SLS$CATG$DISC$ITM"."PEND_ADJ_AMT" IS 'Manual Previous adj Pending';
   COMMENT ON COLUMN "SLS"."SLS$CATG$DISC$ITM"."DISC_ADJ_REMAIN" IS 'Total Disc to be adjusted';
  GRANT INSERT ON "SLS"."SLS$CATG$DISC$ITM" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$CATG$DISC$ITM" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$CATG$DISC$ITM" TO PUBLIC;
