--------------------------------------------------------
--  DDL for Table SLS$CRM$IMD$SO$DTL
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$CRM$IMD$SO$DTL" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"CRM_ORD_ID" NUMBER(10,0), 
	"CRM_USR_ID" NUMBER(10,0), 
	"CRM_ORD_DT" DATE, 
	"CRM_NO_ORDR_FLG" VARCHAR2(1 BYTE), 
	"CRM_NO_OF_ITMS" NUMBER(10,0), 
	"CRM_REMARKS" VARCHAR2(1000 BYTE), 
	"ORD_ENTRD_IN_ERP" VARCHAR2(1 BYTE), 
	"SO_DOC_TXN_ID" VARCHAR2(40 BYTE), 
	"SO_STAT" NUMBER(10,0), 
	"SO_SR_NO" NUMBER(10,0) DEFAULT 0, 
	"CUST_ID" NUMBER(10,0), 
	"CUST_NM" VARCHAR2(250 BYTE), 
	"CRM_USR_NM" VARCHAR2(250 BYTE), 
	"CNCL_RSN" VARCHAR2(1000 BYTE), 
	"STAT_NM" VARCHAR2(20 BYTE), 
	"SO_DISP_ID" VARCHAR2(20 BYTE)
   ) ;
