--------------------------------------------------------
--  DDL for Table SLS$PRIC$BUILDR
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$PRIC$BUILDR" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"DOC_DT" DATE, 
	"DISP_DOC_ID" VARCHAR2(20 BYTE), 
	"CATG_ID" NUMBER(5,0), 
	"DOC_MODE" NUMBER(5,0), 
	"PRJ_ID" VARCHAR2(40 BYTE), 
	"FY_ID" NUMBER(2,0), 
	"USR_ID_CREATE" NUMBER(5,0), 
	"USR_ID_MOD" NUMBER(5,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD_DT" DATE
   ) ;
  GRANT FLASHBACK ON "SLS"."SLS$PRIC$BUILDR" TO "APP";
  GRANT DEBUG ON "SLS"."SLS$PRIC$BUILDR" TO "APP";
  GRANT QUERY REWRITE ON "SLS"."SLS$PRIC$BUILDR" TO "APP";
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$PRIC$BUILDR" TO "APP";
  GRANT REFERENCES ON "SLS"."SLS$PRIC$BUILDR" TO "APP";
  GRANT UPDATE ON "SLS"."SLS$PRIC$BUILDR" TO "APP";
  GRANT SELECT ON "SLS"."SLS$PRIC$BUILDR" TO "APP";
  GRANT INSERT ON "SLS"."SLS$PRIC$BUILDR" TO "APP";
  GRANT INDEX ON "SLS"."SLS$PRIC$BUILDR" TO "APP";
  GRANT DELETE ON "SLS"."SLS$PRIC$BUILDR" TO "APP";
  GRANT ALTER ON "SLS"."SLS$PRIC$BUILDR" TO "APP";
