--------------------------------------------------------
--  DDL for Table SLS$EO$PYMNT$TRMS
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$EO$PYMNT$TRMS" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(5,0), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"PYMNT_TRMS_ID" NUMBER(5,0), 
	"PYMNT_TRMS_DESC" VARCHAR2(1000 BYTE), 
	"RMRKS" VARCHAR2(1000 BYTE), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"INV_TYPE_ID" NUMBER(5,0)
   ) ;
  GRANT INSERT ON "SLS"."SLS$EO$PYMNT$TRMS" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$EO$PYMNT$TRMS" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$EO$PYMNT$TRMS" TO PUBLIC;
