--------------------------------------------------------
--  DDL for Table SLS$SO$DLV$SCHDL
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$SO$DLV$SCHDL" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"ITM_ID" VARCHAR2(50 BYTE), 
	"DLV_DT" DATE, 
	"TOT_QTY" NUMBER(26,6), 
	"DLV_MODE" NUMBER(20,0), 
	"DLV_QTY" NUMBER(26,6), 
	"TLRNC_QTY_TYPE" VARCHAR2(1 BYTE), 
	"TLRNC_QTY_VAL" NUMBER(26,6), 
	"WH_ID" VARCHAR2(20 BYTE), 
	"DLV_ADDS_ID" VARCHAR2(20 BYTE), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE DEFAULT SYSDATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"DLV_SCHDL_NO" NUMBER(4,0), 
	"AVL_QTY" NUMBER(26,6), 
	"ITM_UOM_BS" VARCHAR2(20 BYTE), 
	"UOM_CONV_FCTR" NUMBER(26,6), 
	"DLV_QTY_BS" NUMBER(26,6), 
	"BAL_QTY" NUMBER(26,6), 
	"ITM_UOM" VARCHAR2(20 BYTE), 
	"REMARKS" VARCHAR2(250 BYTE), 
	"PLN_QTY" NUMBER(26,6), 
	"PRJ_ID" VARCHAR2(40 BYTE) DEFAULT 'PROJ0000', 
	"TMP_BAL_QTY" NUMBER(26,6) DEFAULT 0, 
	"ITM_SR_NO" NUMBER(10,0) DEFAULT 1, 
	"RSRV_QTY" NUMBER(26,6) DEFAULT 0, 
	"CNT_QTY" NUMBER(26,6) DEFAULT 0, 
	"DLV_TYPE" NUMBER(20,0), 
	"GTC_ID" VARCHAR2(40 BYTE), 
	"ATC_ID" VARCHAR2(40 BYTE), 
	"SHIP_FLG" VARCHAR2(1 BYTE), 
	"PO_DOC_ID" VARCHAR2(40 BYTE), 
	"RETURN_QTY" NUMBER(26,6), 
	"PI_BAL_QTY" NUMBER(26,6) DEFAULT 0, 
	"OLD_BAL_QTY" NUMBER(26,6), 
	"CNSL_FLG" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"DLV_TIME" VARCHAR2(5 BYTE), 
	"LR_TEMP_BAL_QTY" NUMBER(26,6) DEFAULT 0, 
	"LR_BAL_QTY" NUMBER(26,6)
   ) ;

   COMMENT ON COLUMN "SLS"."SLS$SO$DLV$SCHDL"."DLV_SCHDL_NO" IS 'Unique set of Number for each deliveery schedule for each Sales Order';
   COMMENT ON COLUMN "SLS"."SLS$SO$DLV$SCHDL"."GTC_ID" IS 'Good to Collect Id';
   COMMENT ON COLUMN "SLS"."SLS$SO$DLV$SCHDL"."ATC_ID" IS 'ALREADY COLLECTED ID';
   COMMENT ON COLUMN "SLS"."SLS$SO$DLV$SCHDL"."PO_DOC_ID" IS 'To store Purchase order Number';
   COMMENT ON COLUMN "SLS"."SLS$SO$DLV$SCHDL"."PI_BAL_QTY" IS 'BALANCE QTY OF PERFORMA INVOICE';
  GRANT FLASHBACK ON "SLS"."SLS$SO$DLV$SCHDL" TO "PMS";
  GRANT DEBUG ON "SLS"."SLS$SO$DLV$SCHDL" TO "PMS";
  GRANT QUERY REWRITE ON "SLS"."SLS$SO$DLV$SCHDL" TO "PMS";
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$SO$DLV$SCHDL" TO "PMS";
  GRANT REFERENCES ON "SLS"."SLS$SO$DLV$SCHDL" TO "PMS";
  GRANT UPDATE ON "SLS"."SLS$SO$DLV$SCHDL" TO "PMS";
  GRANT SELECT ON "SLS"."SLS$SO$DLV$SCHDL" TO "PMS";
  GRANT INSERT ON "SLS"."SLS$SO$DLV$SCHDL" TO "PMS";
  GRANT INDEX ON "SLS"."SLS$SO$DLV$SCHDL" TO "PMS";
  GRANT DELETE ON "SLS"."SLS$SO$DLV$SCHDL" TO "PMS";
  GRANT ALTER ON "SLS"."SLS$SO$DLV$SCHDL" TO "PMS";
  GRANT SELECT ON "SLS"."SLS$SO$DLV$SCHDL" TO "APP";
  GRANT FLASHBACK ON "SLS"."SLS$SO$DLV$SCHDL" TO PUBLIC;
  GRANT DEBUG ON "SLS"."SLS$SO$DLV$SCHDL" TO PUBLIC;
  GRANT QUERY REWRITE ON "SLS"."SLS$SO$DLV$SCHDL" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$SO$DLV$SCHDL" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$SO$DLV$SCHDL" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$SO$DLV$SCHDL" TO PUBLIC;
  GRANT REFERENCES ON "SLS"."SLS$SO$DLV$SCHDL" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$SO$DLV$SCHDL" TO PUBLIC;
  GRANT INDEX ON "SLS"."SLS$SO$DLV$SCHDL" TO PUBLIC;
  GRANT DELETE ON "SLS"."SLS$SO$DLV$SCHDL" TO PUBLIC;
  GRANT ALTER ON "SLS"."SLS$SO$DLV$SCHDL" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$SO$DLV$SCHDL" TO "MNF" WITH GRANT OPTION;
  GRANT FLASHBACK ON "SLS"."SLS$SO$DLV$SCHDL" TO "MNF" WITH GRANT OPTION;
  GRANT DEBUG ON "SLS"."SLS$SO$DLV$SCHDL" TO "MNF" WITH GRANT OPTION;
  GRANT QUERY REWRITE ON "SLS"."SLS$SO$DLV$SCHDL" TO "MNF" WITH GRANT OPTION;
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$SO$DLV$SCHDL" TO "MNF" WITH GRANT OPTION;
  GRANT REFERENCES ON "SLS"."SLS$SO$DLV$SCHDL" TO "MNF" WITH GRANT OPTION;
  GRANT UPDATE ON "SLS"."SLS$SO$DLV$SCHDL" TO "MNF" WITH GRANT OPTION;
  GRANT INSERT ON "SLS"."SLS$SO$DLV$SCHDL" TO "MNF" WITH GRANT OPTION;
  GRANT INDEX ON "SLS"."SLS$SO$DLV$SCHDL" TO "MNF" WITH GRANT OPTION;
  GRANT DELETE ON "SLS"."SLS$SO$DLV$SCHDL" TO "MNF" WITH GRANT OPTION;
  GRANT ALTER ON "SLS"."SLS$SO$DLV$SCHDL" TO "MNF" WITH GRANT OPTION;
