--------------------------------------------------------
--  DDL for Table SLS$DISC$PLC$HDR
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$DISC$PLC$HDR" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"DISC_PLC_ID" VARCHAR2(40 BYTE), 
	"DISC_PLC_MODE" NUMBER(5,0), 
	"USR_ID_CREATE" NUMBER(10,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(10,0), 
	"USR_ID_MOD_DT" DATE, 
	"DOC_DT" DATE, 
	"AMD_NO" VARCHAR2(40 BYTE), 
	"AMD_DT" DATE
   ) ;
  GRANT SELECT ON "SLS"."SLS$DISC$PLC$HDR" TO "APP";
  GRANT SELECT ON "SLS"."SLS$DISC$PLC$HDR" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$DISC$PLC$HDR" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$DISC$PLC$HDR" TO PUBLIC;
