--------------------------------------------------------
--  DDL for Table SLS$RMA$ITM
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$RMA$ITM" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"DOC_DT" DATE, 
	"ITM_ID" VARCHAR2(50 BYTE), 
	"SHIPMNT_QTY" NUMBER(26,6), 
	"ITM_UOM" VARCHAR2(20 BYTE), 
	"ITM_PRICE" NUMBER(20,6), 
	"ITM_AMT_SP" NUMBER(26,6), 
	"SO_ID" VARCHAR2(40 BYTE), 
	"SHIPMNT_ID" VARCHAR2(40 BYTE), 
	"SHIPMNT_DT" DATE, 
	"RETURN_TYP_ID" NUMBER(10,0), 
	"REASON" VARCHAR2(100 BYTE), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE DEFAULT SYSDATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"ITM_AMT_BS" NUMBER(26,6), 
	"REJ_QTY" NUMBER(26,6), 
	"TAX_REVS_FLG" VARCHAR2(1 BYTE), 
	"REMARKS" VARCHAR2(1000 BYTE), 
	"CURR_ID_BS" NUMBER(10,0), 
	"CURR_ID_SP" NUMBER(10,0), 
	"CURR_CONV_FCTR" NUMBER(26,6), 
	"WH_ID" VARCHAR2(20 BYTE) DEFAULT 0, 
	"ITM_UOM_BS" VARCHAR2(20 BYTE), 
	"UOM_CONV_FCTR" NUMBER(26,6), 
	"ITM_QTY_BS" NUMBER(26,6), 
	"OK_QTY" NUMBER(26,6), 
	"RWK_QTY" NUMBER(26,6), 
	"RCPT_QTY" NUMBER(26,6), 
	"INV_ID" VARCHAR2(40 BYTE), 
	"DISC_REVS_FLG" VARCHAR2(1 BYTE), 
	"PICK_ID" VARCHAR2(40 BYTE), 
	"PRJ_ID" VARCHAR2(40 BYTE) DEFAULT 'PROJ0000', 
	"ITM_ASBL_AMT_SP" NUMBER(26,6), 
	"ITM_ASBL_AMT_BS" NUMBER(26,6), 
	"CC_ID" VARCHAR2(45 BYTE), 
	"OK_QTY_BS" NUMBER(26,6) DEFAULT 0, 
	"REJ_QTY_BS" NUMBER(26,6) DEFAULT 0, 
	"RWK_QTY_BS" NUMBER(26,6) DEFAULT 0, 
	"ITM_AMT_GS_SP" NUMBER(26,6) DEFAULT 0, 
	"ITM_AMT_GS_BS" NUMBER(26,6) DEFAULT 0, 
	"ITM_SR_NO" NUMBER(10,0) DEFAULT 1, 
	"CNT_QTY" NUMBER(26,6) DEFAULT 0, 
	"RCPT_QTY_BS" NUMBER(26,6), 
	"INCL_TX" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"COLOR_ATT_GRP_ID" VARCHAR2(40 BYTE)
   ) ;

   COMMENT ON COLUMN "SLS"."SLS$RMA$ITM"."RCPT_QTY" IS 'TOTAL RCPT QUANTITY AT THE TIME OF RMA WHICH IS SUM OF OK_QTY+REW_QTY+REJ_QTY';
   COMMENT ON COLUMN "SLS"."SLS$RMA$ITM"."OK_QTY_BS" IS 'To Store Ok Qty Base';
   COMMENT ON COLUMN "SLS"."SLS$RMA$ITM"."REJ_QTY_BS" IS 'To Store Rejected Qty base';
   COMMENT ON COLUMN "SLS"."SLS$RMA$ITM"."RWK_QTY_BS" IS 'To Store Reworkable Qty Base';
   COMMENT ON COLUMN "SLS"."SLS$RMA$ITM"."RCPT_QTY_BS" IS 'To Store receipt Quantity in Base';
   COMMENT ON COLUMN "SLS"."SLS$RMA$ITM"."INCL_TX" IS 'In Case Of Gst Tax Is Inclusive Or Not';
  GRANT FLASHBACK ON "SLS"."SLS$RMA$ITM" TO "APP";
  GRANT REFERENCES ON "SLS"."SLS$RMA$ITM" TO "MNF" WITH GRANT OPTION;
  GRANT ALTER ON "SLS"."SLS$RMA$ITM" TO "MNF" WITH GRANT OPTION;
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$RMA$ITM" TO "MNF" WITH GRANT OPTION;
  GRANT DELETE ON "SLS"."SLS$RMA$ITM" TO "MNF" WITH GRANT OPTION;
  GRANT SELECT ON "SLS"."SLS$RMA$ITM" TO "APP";
  GRANT FLASHBACK ON "SLS"."SLS$RMA$ITM" TO PUBLIC;
  GRANT QUERY REWRITE ON "SLS"."SLS$RMA$ITM" TO PUBLIC;
  GRANT DEBUG ON "SLS"."SLS$RMA$ITM" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$RMA$ITM" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$RMA$ITM" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$RMA$ITM" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$RMA$ITM" TO PUBLIC;
  GRANT INDEX ON "SLS"."SLS$RMA$ITM" TO PUBLIC;
  GRANT DELETE ON "SLS"."SLS$RMA$ITM" TO PUBLIC;
  GRANT ALTER ON "SLS"."SLS$RMA$ITM" TO PUBLIC;
  GRANT INDEX ON "SLS"."SLS$RMA$ITM" TO "MNF" WITH GRANT OPTION;
  GRANT INSERT ON "SLS"."SLS$RMA$ITM" TO "MNF" WITH GRANT OPTION;
  GRANT DELETE ON "SLS"."SLS$RMA$ITM" TO "APP";
  GRANT REFERENCES ON "SLS"."SLS$RMA$ITM" TO PUBLIC;
  GRANT INDEX ON "SLS"."SLS$RMA$ITM" TO "APP";
  GRANT QUERY REWRITE ON "SLS"."SLS$RMA$ITM" TO "APP";
  GRANT INSERT ON "SLS"."SLS$RMA$ITM" TO "APP";
  GRANT QUERY REWRITE ON "SLS"."SLS$RMA$ITM" TO "MNF" WITH GRANT OPTION;
  GRANT DEBUG ON "SLS"."SLS$RMA$ITM" TO "MNF" WITH GRANT OPTION;
  GRANT FLASHBACK ON "SLS"."SLS$RMA$ITM" TO "MNF" WITH GRANT OPTION;
  GRANT DEBUG ON "SLS"."SLS$RMA$ITM" TO "APP";
  GRANT SELECT ON "SLS"."SLS$RMA$ITM" TO "MNF" WITH GRANT OPTION;
  GRANT UPDATE ON "SLS"."SLS$RMA$ITM" TO "MNF" WITH GRANT OPTION;
  GRANT REFERENCES ON "SLS"."SLS$RMA$ITM" TO "APP";
  GRANT ALTER ON "SLS"."SLS$RMA$ITM" TO "APP";
  GRANT UPDATE ON "SLS"."SLS$RMA$ITM" TO "APP";
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$RMA$ITM" TO "APP";
