--------------------------------------------------------
--  DDL for Table SLS$SO$CALC
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$SO$CALC" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"COA_ID" NUMBER(20,0), 
	"AMT_SP" NUMBER(26,6), 
	"AMT_BS" NUMBER(26,6), 
	"CURR_ID" NUMBER(10,0), 
	"CURR_RATE" NUMBER(26,6), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE DEFAULT SYSDATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"TRAN_TYPE" VARCHAR2(2 BYTE), 
	"SR_NO" NUMBER(10,0), 
	"COA_NM" VARCHAR2(250 BYTE), 
	"TAXABL_VAL" NUMBER(26,6), 
	"CC_ID" VARCHAR2(45 BYTE)
   ) ;

   COMMENT ON COLUMN "SLS"."SLS$SO$CALC"."CC_ID" IS 'Column to store Cost Center Doc Id.';
  GRANT ALTER ON "SLS"."SLS$SO$CALC" TO "PMS";
  GRANT DELETE ON "SLS"."SLS$SO$CALC" TO "PMS";
  GRANT INDEX ON "SLS"."SLS$SO$CALC" TO "PMS";
  GRANT INSERT ON "SLS"."SLS$SO$CALC" TO "PMS";
  GRANT SELECT ON "SLS"."SLS$SO$CALC" TO "PMS";
  GRANT UPDATE ON "SLS"."SLS$SO$CALC" TO "PMS";
  GRANT REFERENCES ON "SLS"."SLS$SO$CALC" TO "PMS";
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$SO$CALC" TO "PMS";
  GRANT QUERY REWRITE ON "SLS"."SLS$SO$CALC" TO "PMS";
  GRANT DEBUG ON "SLS"."SLS$SO$CALC" TO "PMS";
  GRANT FLASHBACK ON "SLS"."SLS$SO$CALC" TO "PMS";
  GRANT ALTER ON "SLS"."SLS$SO$CALC" TO PUBLIC;
  GRANT DELETE ON "SLS"."SLS$SO$CALC" TO PUBLIC;
  GRANT INDEX ON "SLS"."SLS$SO$CALC" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$SO$CALC" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$SO$CALC" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$SO$CALC" TO PUBLIC;
  GRANT REFERENCES ON "SLS"."SLS$SO$CALC" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$SO$CALC" TO PUBLIC;
  GRANT QUERY REWRITE ON "SLS"."SLS$SO$CALC" TO PUBLIC;
  GRANT DEBUG ON "SLS"."SLS$SO$CALC" TO PUBLIC;
  GRANT FLASHBACK ON "SLS"."SLS$SO$CALC" TO PUBLIC;
