--------------------------------------------------------
--  DDL for Table SLS$TRNP$BULK$VR$SRC
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$TRNP$BULK$VR$SRC" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"SRC_DOC_ID" VARCHAR2(40 BYTE), 
	"SRC_DOC_DT" DATE, 
	"EO_ID" NUMBER(20,0), 
	"VEHICLE_TYP" NUMBER(20,0), 
	"LOC_ID" VARCHAR2(20 BYTE), 
	"ROUTE_DOC_ID" VARCHAR2(40 BYTE), 
	"GROSS_WT" NUMBER(26,6), 
	"REQ_TYP" VARCHAR2(1 BYTE), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"DLV_DT" DATE, 
	"WH_ID" VARCHAR2(20 BYTE), 
	"DLV_SCHDL_NO" NUMBER(4,0), 
	"ARRIVAL_PNT" VARCHAR2(40 BYTE), 
	"DEPARTURE_PNT" VARCHAR2(40 BYTE), 
	"BLNC_WT" NUMBER(26,6) DEFAULT 0, 
	"EXT_DOC_NO" VARCHAR2(40 BYTE), 
	"EO_TPT_NO" VARCHAR2(40 BYTE)
   ) ;
  GRANT INSERT ON "SLS"."SLS$TRNP$BULK$VR$SRC" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$TRNP$BULK$VR$SRC" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$TRNP$BULK$VR$SRC" TO PUBLIC;
