--------------------------------------------------------
--  DDL for Table SLS$WMS$STOCK$TAKE$ITEM
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$WMS$STOCK$TAKE$ITEM" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(4 BYTE), 
	"HO_ORG_ID" VARCHAR2(4 BYTE), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"ITM_ID" VARCHAR2(20 BYTE), 
	"ITM_QTY" NUMBER(26,6), 
	"ITM_UOM" VARCHAR2(20 BYTE), 
	"ITM_U_SR_NO" VARCHAR2(50 BYTE), 
	"ATT_GRP_ID" VARCHAR2(20 BYTE), 
	"WH_ID" VARCHAR2(10 BYTE), 
	"VERIFIED_STATUS" CHAR(1 BYTE) DEFAULT 'N', 
	"PROJ_ID" VARCHAR2(50 BYTE), 
	"PHY_VERIFIED" VARCHAR2(2 BYTE) DEFAULT 'N'
   ) ;
  GRANT INSERT ON "SLS"."SLS$WMS$STOCK$TAKE$ITEM" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$WMS$STOCK$TAKE$ITEM" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$WMS$STOCK$TAKE$ITEM" TO PUBLIC;
  GRANT ALTER ON "SLS"."SLS$WMS$STOCK$TAKE$ITEM" TO PUBLIC;
  GRANT DELETE ON "SLS"."SLS$WMS$STOCK$TAKE$ITEM" TO PUBLIC;
  GRANT INDEX ON "SLS"."SLS$WMS$STOCK$TAKE$ITEM" TO PUBLIC;
  GRANT REFERENCES ON "SLS"."SLS$WMS$STOCK$TAKE$ITEM" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$WMS$STOCK$TAKE$ITEM" TO PUBLIC;
  GRANT QUERY REWRITE ON "SLS"."SLS$WMS$STOCK$TAKE$ITEM" TO PUBLIC;
  GRANT DEBUG ON "SLS"."SLS$WMS$STOCK$TAKE$ITEM" TO PUBLIC;
  GRANT FLASHBACK ON "SLS"."SLS$WMS$STOCK$TAKE$ITEM" TO PUBLIC;
