--------------------------------------------------------
--  DDL for Table SLS$OPP$SRC$DTL
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$OPP$SRC$DTL" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"DOC_DT" DATE, 
	"FY_ID" NUMBER(5,0), 
	"EO_ID" NUMBER(22,0), 
	"LEAD_TYPE" NUMBER(5,0), 
	"LEAD_SUB_TYPE" VARCHAR2(20 BYTE), 
	"LEAD_VAL" NUMBER(26,6), 
	"LEAD_NM" VARCHAR2(100 BYTE), 
	"LEAD_PLC" VARCHAR2(100 BYTE), 
	"LEAD_DT" DATE, 
	"EO_PER_NM" VARCHAR2(50 BYTE), 
	"EO_PER_ADD" VARCHAR2(50 BYTE), 
	"EO_PER_EMAIL1" VARCHAR2(50 BYTE), 
	"EO_PER_EMAIL2" VARCHAR2(50 BYTE), 
	"EO_PHON_NO" VARCHAR2(50 BYTE), 
	"EO_MOB_NO" VARCHAR2(20 BYTE), 
	"DLV_SRVC" NUMBER(5,0), 
	"DLV_SRVC_DESC" VARCHAR2(50 BYTE), 
	"NO_OF_STRS" NUMBER(10,0), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"MRKTNG_CMPNY_NM" VARCHAR2(100 BYTE), 
	"SR_NO" NUMBER(4,0), 
	"PORT_ID" VARCHAR2(20 BYTE)
   ) ;
  GRANT INSERT ON "SLS"."SLS$OPP$SRC$DTL" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$OPP$SRC$DTL" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$OPP$SRC$DTL" TO PUBLIC;
