--------------------------------------------------------
--  DDL for Table SLS$DSH$GRP$MNTH$SLS$PRFT
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$DSH$GRP$MNTH$SLS$PRFT" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"SALES_MONTH_YEAR" VARCHAR2(17 BYTE), 
	"SALES_MNTH" NUMBER(2,0), 
	"SALES_YEAR" VARCHAR2(4 BYTE), 
	"GRP_ID" VARCHAR2(20 BYTE), 
	"GRP_NM" VARCHAR2(100 BYTE), 
	"INV_AMT" NUMBER(26,0), 
	"ITM_COST" NUMBER(26,0), 
	"ITM_PROFIT" NUMBER(26,0)
   ) ;
  GRANT INSERT ON "SLS"."SLS$DSH$GRP$MNTH$SLS$PRFT" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$DSH$GRP$MNTH$SLS$PRFT" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$DSH$GRP$MNTH$SLS$PRFT" TO PUBLIC;
