--------------------------------------------------------
--  DDL for Table SLS$SUBC$OPP
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$SUBC$OPP" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"DOC_DT" DATE, 
	"FY_ID" NUMBER(5,0), 
	"EO_ID" NUMBER(22,0), 
	"REMARKS" VARCHAR2(1000 BYTE), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"CURR_ID_SP" NUMBER(10,0), 
	"CURR_RATE" NUMBER(26,6), 
	"CURR_ID_BS" NUMBER(10,0), 
	"DISP_ID" VARCHAR2(20 BYTE), 
	"STATUS" NUMBER(10,0), 
	"PROJ_ID" VARCHAR2(40 BYTE), 
	"SUBC_BASIS" NUMBER(10,0), 
	"SUBC_MODE" NUMBER(10,0), 
	"TRAIL_REQ" VARCHAR2(4 BYTE), 
	"TRAIL_SRT_DT" DATE, 
	"TRAIL_END_DT" DATE, 
	"AMD_NO" NUMBER, 
	"AMD_DATE" DATE, 
	"ASSIGN_TO" NUMBER(10,0)
   ) ;
  GRANT FLASHBACK ON "SLS"."SLS$SUBC$OPP" TO PUBLIC;
  GRANT DEBUG ON "SLS"."SLS$SUBC$OPP" TO PUBLIC;
  GRANT QUERY REWRITE ON "SLS"."SLS$SUBC$OPP" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$SUBC$OPP" TO PUBLIC;
  GRANT REFERENCES ON "SLS"."SLS$SUBC$OPP" TO PUBLIC;
  GRANT INDEX ON "SLS"."SLS$SUBC$OPP" TO PUBLIC;
  GRANT DELETE ON "SLS"."SLS$SUBC$OPP" TO PUBLIC;
  GRANT ALTER ON "SLS"."SLS$SUBC$OPP" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$SUBC$OPP" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$SUBC$OPP" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$SUBC$OPP" TO PUBLIC;
