--------------------------------------------------------
--  DDL for Table SLS$PACK$ITM$GRP
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$PACK$ITM$GRP" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"DOC_DT" DATE, 
	"PACK_TYP_ID" NUMBER(20,0), 
	"ITM_ID" VARCHAR2(50 BYTE), 
	"PICK_QTY" NUMBER(26,6), 
	"ITM_UOM" VARCHAR2(20 BYTE), 
	"PACK_QTY" NUMBER(26,6), 
	"BAL_QTY" NUMBER(26,6), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE DEFAULT SYSDATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"PACK_WT" NUMBER(26,6), 
	"PACK_NET_WT" NUMBER(26,6), 
	"TMP_BAL_QTY" NUMBER(26,6), 
	"ITM_SR_NO" NUMBER(10,0) DEFAULT 1, 
	"PACK_NO" VARCHAR2(50 BYTE), 
	"CNT_QTY" NUMBER(26,6) DEFAULT 0, 
	"PACK_NM" VARCHAR2(100 BYTE)
   ) ;
  GRANT INSERT ON "SLS"."SLS$PACK$ITM$GRP" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$PACK$ITM$GRP" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$PACK$ITM$GRP" TO PUBLIC;
