--------------------------------------------------------
--  DDL for Table SLS$WMS$PUT
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$WMS$PUT" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(4 BYTE), 
	"HO_ORG_ID" VARCHAR2(4 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"VERIFIED_STATUS" CHAR(1 BYTE) DEFAULT 'N', 
	"CAGE_ID" VARCHAR2(50 BYTE), 
	"SCHDL_NO" VARCHAR2(50 BYTE), 
	"VHCL_NO" VARCHAR2(50 BYTE), 
	"SCHDL_DT" DATE
   ) ;
  GRANT INSERT ON "SLS"."SLS$WMS$PUT" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$WMS$PUT" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$WMS$PUT" TO PUBLIC;
