--------------------------------------------------------
--  DDL for Table SLS$CCP$CALC$GL
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$CCP$CALC$GL" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"COA_ID" NUMBER(10,0), 
	"COA_NM" VARCHAR2(100 BYTE), 
	"AMT_SP" NUMBER(26,6), 
	"AMT_BS" NUMBER(26,6), 
	"SR_NO" NUMBER(3,0), 
	"TRAN_TYPE" VARCHAR2(2 BYTE), 
	"TRAN_CAT" VARCHAR2(250 BYTE), 
	"AP_SR_NO" NUMBER(3,0), 
	"CC_ID" VARCHAR2(40 BYTE), 
	"GL_TYPE_ID" NUMBER(5,0), 
	"GL_NO" NUMBER(2,0), 
	"GL_ADD_NARR" VARCHAR2(100 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE) DEFAULT '01', 
	"EO_ID" NUMBER
   ) ;
  GRANT ALTER ON "SLS"."SLS$CCP$CALC$GL" TO PUBLIC;
  GRANT DELETE ON "SLS"."SLS$CCP$CALC$GL" TO PUBLIC;
  GRANT INDEX ON "SLS"."SLS$CCP$CALC$GL" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$CCP$CALC$GL" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$CCP$CALC$GL" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$CCP$CALC$GL" TO PUBLIC;
  GRANT REFERENCES ON "SLS"."SLS$CCP$CALC$GL" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$CCP$CALC$GL" TO PUBLIC;
  GRANT QUERY REWRITE ON "SLS"."SLS$CCP$CALC$GL" TO PUBLIC;
  GRANT DEBUG ON "SLS"."SLS$CCP$CALC$GL" TO PUBLIC;
  GRANT FLASHBACK ON "SLS"."SLS$CCP$CALC$GL" TO PUBLIC;
  GRANT ALTER ON "SLS"."SLS$CCP$CALC$GL" TO "FIN";
  GRANT DELETE ON "SLS"."SLS$CCP$CALC$GL" TO "FIN";
  GRANT INDEX ON "SLS"."SLS$CCP$CALC$GL" TO "FIN";
  GRANT INSERT ON "SLS"."SLS$CCP$CALC$GL" TO "FIN";
  GRANT SELECT ON "SLS"."SLS$CCP$CALC$GL" TO "FIN";
  GRANT UPDATE ON "SLS"."SLS$CCP$CALC$GL" TO "FIN";
  GRANT REFERENCES ON "SLS"."SLS$CCP$CALC$GL" TO "FIN";
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$CCP$CALC$GL" TO "FIN";
  GRANT QUERY REWRITE ON "SLS"."SLS$CCP$CALC$GL" TO "FIN";
  GRANT DEBUG ON "SLS"."SLS$CCP$CALC$GL" TO "FIN";
  GRANT FLASHBACK ON "SLS"."SLS$CCP$CALC$GL" TO "FIN";
