--------------------------------------------------------
--  DDL for Table SLS$BANK$GUARANTEE
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$BANK$GUARANTEE" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"DOC_DT" DATE, 
	"DISP_DOC_ID" VARCHAR2(40 BYTE), 
	"BG_TYPE" VARCHAR2(20 BYTE), 
	"BNK_NAME" VARCHAR2(250 BYTE), 
	"BNK_ID" NUMBER(5,0), 
	"BG_DUE_DT" DATE, 
	"CLAIM_EXP_DT" DATE, 
	"BG_AMOUNT" NUMBER(26,6), 
	"CUST_PO_NUMBER" VARCHAR2(40 BYTE), 
	"FD_AMOUNT" NUMBER(26,6), 
	"SO_NUMBER" VARCHAR2(40 BYTE), 
	"SO_DATE" DATE, 
	"SO_EO_ID" NUMBER(5,0), 
	"SO_EXT_DOC_NO" VARCHAR2(40 BYTE), 
	"SO_EXT_DOC_DT" DATE, 
	"USR_ID_CREATE" NUMBER(5,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(5,0), 
	"USR_ID_MOD_DT" DATE, 
	"BG_STAT" NUMBER(10,0), 
	"BG_MODE" NUMBER(10,0), 
	"BG_NUMBER" VARCHAR2(50 BYTE), 
	"BANK_ACCNT_ID" NUMBER(5,0), 
	"REMARKS" VARCHAR2(250 BYTE), 
	"BG_BASIS" NUMBER(5,0), 
	"SO_DOC_ID" VARCHAR2(50 BYTE)
   ) ;
  GRANT FLASHBACK ON "SLS"."SLS$BANK$GUARANTEE" TO PUBLIC;
  GRANT DEBUG ON "SLS"."SLS$BANK$GUARANTEE" TO PUBLIC;
  GRANT QUERY REWRITE ON "SLS"."SLS$BANK$GUARANTEE" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$BANK$GUARANTEE" TO PUBLIC;
  GRANT REFERENCES ON "SLS"."SLS$BANK$GUARANTEE" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$BANK$GUARANTEE" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$BANK$GUARANTEE" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$BANK$GUARANTEE" TO PUBLIC;
  GRANT INDEX ON "SLS"."SLS$BANK$GUARANTEE" TO PUBLIC;
  GRANT DELETE ON "SLS"."SLS$BANK$GUARANTEE" TO PUBLIC;
  GRANT ALTER ON "SLS"."SLS$BANK$GUARANTEE" TO PUBLIC;
