--------------------------------------------------------
--  DDL for Table SLS$POS$PRICE$EO
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$POS$PRICE$EO" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"PRJ_ID" VARCHAR2(40 BYTE), 
	"ITM_ID" VARCHAR2(50 BYTE), 
	"ITM_UOM" VARCHAR2(20 BYTE), 
	"BASE_PRICE" NUMBER(26,6), 
	"TAXABLE_PRICE" NUMBER(26,6), 
	"EFFECTIVE_DT" TIMESTAMP (8), 
	"ACTIVE" VARCHAR2(2 BYTE), 
	"DEBIT_NOTE_GEN" VARCHAR2(2 BYTE) DEFAULT 'N', 
	"EO_TYP_ID" NUMBER(5,0) DEFAULT -1, 
	"EO_ID" NUMBER(5,0), 
	"ITM_MIN_PRICE" NUMBER(26,6) DEFAULT 0, 
	"USR_CREATE_ID" NUMBER(4,0), 
	"USR_CREATE_DT" DATE DEFAULT sysdate, 
	"USR_MOD_ID" NUMBER(4,0), 
	"USR_MOD_DT" DATE
   ) ;
  GRANT INSERT ON "SLS"."SLS$POS$PRICE$EO" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$POS$PRICE$EO" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$POS$PRICE$EO" TO PUBLIC;
