--------------------------------------------------------
--  DDL for Table SLS$TRNP$BILL$RCNCL$TDS
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$TRNP$BILL$RCNCL$TDS" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"LR_DOC_ID" VARCHAR2(40 BYTE), 
	"TDS_RULE_ID" NUMBER(10,0), 
	"TDS_RULE_FLG" VARCHAR2(1 BYTE), 
	"TDS_EXMPT_FLG" VARCHAR2(1 BYTE), 
	"TDS_AMT" NUMBER(26,6), 
	"TDS_AMT_BS" NUMBER(26,6), 
	"TDS_ON_AMT_SP" NUMBER(26,6), 
	"TDS_ON_AMT_BS" NUMBER(26,6)
   ) ;
  GRANT INSERT ON "SLS"."SLS$TRNP$BILL$RCNCL$TDS" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$TRNP$BILL$RCNCL$TDS" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$TRNP$BILL$RCNCL$TDS" TO PUBLIC;
