--------------------------------------------------------
--  DDL for Table SLS$SUBC$SO
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$SUBC$SO" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"DOC_DT" DATE, 
	"EO_ID" NUMBER(20,0), 
	"SECU_AMT" NUMBER(26,6), 
	"ADV_AMT" NUMBER(26,6), 
	"RENEW_BASIS" NUMBER(5,0), 
	"FIXED_TERM_STRTDT" DATE, 
	"FIXED_TERM_ENDDT" DATE, 
	"RENEW_PRCNT" NUMBER(3,0), 
	"STRT_DT" DATE, 
	"END_DT" DATE, 
	"TRIAL_STRT_DT" DATE, 
	"TRIAL_END_DT" DATE, 
	"ORDER_TYPE" NUMBER(10,0), 
	"SUB_DOC_TYPE" NUMBER(10,0), 
	"CONTACT_PERSON_BILL" VARCHAR2(100 BYTE), 
	"CONTACT_PERSON_TECH" VARCHAR2(100 BYTE), 
	"CURR_ID_SP" NUMBER, 
	"CURR_ID_RATE" NUMBER, 
	"TRIAL_REQ" VARCHAR2(1 BYTE), 
	"BILL_ADDS" VARCHAR2(20 BYTE), 
	"AMD_NO" NUMBER(5,0), 
	"AMD_DT" DATE, 
	"SO_BASIS" NUMBER(5,0), 
	"DISCNTNUE_FLG" VARCHAR2(1 BYTE), 
	"DISCNTNUE_DATE" DATE, 
	"DISCNTNUE_REASON" VARCHAR2(500 BYTE), 
	"DOC_SRC_TXN" VARCHAR2(40 BYTE), 
	"BULIDING_NAME" VARCHAR2(30 BYTE), 
	"FLOOR_NAME" VARCHAR2(30 BYTE), 
	"GLBL_MNU_DOC_ID" NUMBER(8,0), 
	"SUBC_SO_ID" VARCHAR2(20 BYTE), 
	"SUBC_SO_DRFT_ID" VARCHAR2(20 BYTE), 
	"PACKAGE_ID" NUMBER(5,0) DEFAULT 0, 
	"PACKAGE_CHK" VARCHAR2(2 BYTE) DEFAULT 'N', 
	"REMARKS" VARCHAR2(400 BYTE), 
	"CONTRACT_STAT" VARCHAR2(4 BYTE) DEFAULT 'Y', 
	"CONTRACT_STAT_INFO" NUMBER(8,0), 
	"CONTRACT_EXPR_DT" DATE, 
	"TAX_TYPE" NUMBER(5,0), 
	"EFFECTIVE_DATE" DATE, 
	"LAST_RENEW_DATE" DATE, 
	"SUBC_SO_STATUS" NUMBER(5,0), 
	"SUBC_SO_MODE" NUMBER(5,0), 
	"USR_ID_CREATE" NUMBER(5,0), 
	"TOT_AMT_SP" NUMBER(26,6), 
	"TOT_AMT_BS" NUMBER(26,6), 
	"PLC_OF_DLV" VARCHAR2(250 BYTE), 
	"PNT_OF_SPLY" VARCHAR2(20 BYTE), 
	"SHIP_ADDS" VARCHAR2(20 BYTE), 
	"COA_ID" NUMBER(5,0), 
	"FY_ID" NUMBER(5,0), 
	"PROJ_ID" VARCHAR2(40 BYTE), 
	"USR_ID_MOD_DT" DATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE
   ) ;
  GRANT FLASHBACK ON "SLS"."SLS$SUBC$SO" TO "APP";
  GRANT DEBUG ON "SLS"."SLS$SUBC$SO" TO "APP";
  GRANT QUERY REWRITE ON "SLS"."SLS$SUBC$SO" TO "APP";
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$SUBC$SO" TO "APP";
  GRANT REFERENCES ON "SLS"."SLS$SUBC$SO" TO "APP";
  GRANT UPDATE ON "SLS"."SLS$SUBC$SO" TO "APP";
  GRANT SELECT ON "SLS"."SLS$SUBC$SO" TO "APP";
  GRANT INSERT ON "SLS"."SLS$SUBC$SO" TO "APP";
  GRANT INDEX ON "SLS"."SLS$SUBC$SO" TO "APP";
  GRANT DELETE ON "SLS"."SLS$SUBC$SO" TO "APP";
  GRANT ALTER ON "SLS"."SLS$SUBC$SO" TO "APP";
  GRANT FLASHBACK ON "SLS"."SLS$SUBC$SO" TO PUBLIC;
  GRANT DEBUG ON "SLS"."SLS$SUBC$SO" TO PUBLIC;
  GRANT QUERY REWRITE ON "SLS"."SLS$SUBC$SO" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$SUBC$SO" TO PUBLIC;
  GRANT REFERENCES ON "SLS"."SLS$SUBC$SO" TO PUBLIC;
  GRANT INDEX ON "SLS"."SLS$SUBC$SO" TO PUBLIC;
  GRANT DELETE ON "SLS"."SLS$SUBC$SO" TO PUBLIC;
  GRANT ALTER ON "SLS"."SLS$SUBC$SO" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$SUBC$SO" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$SUBC$SO" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$SUBC$SO" TO PUBLIC;
