--------------------------------------------------------
--  DDL for Table SLS$VAULT
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$VAULT" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(1,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"DOC_DT" DATE, 
	"DOC_DISP_ID" VARCHAR2(40 BYTE), 
	"DOC_TYPE" NUMBER(10,0), 
	"SRC_DOC_ID" VARCHAR2(40 BYTE), 
	"SRC_DOC_DT" DATE, 
	"SRC_DISP_ID" VARCHAR2(40 BYTE), 
	"REQ_DOC_ID" VARCHAR2(40 BYTE), 
	"REQ_DISP_ID" VARCHAR2(40 BYTE), 
	"CURR_CONV_FCTR" NUMBER(26,6), 
	"CURR_ID_BS" NUMBER(10,0), 
	"CURR_ID_SP" NUMBER(10,0), 
	"ITM_ID" VARCHAR2(50 BYTE), 
	"ITM_AMT_SP" NUMBER(26,6), 
	"ITM_AMT_BS" NUMBER(26,6), 
	"EO_ID" NUMBER(10,0), 
	"EO_NM" VARCHAR2(250 BYTE), 
	"VAULTD_BY_ID" NUMBER(10,0), 
	"VAULTD_BY_NM" VARCHAR2(250 BYTE), 
	"VAULT_IN_DT" DATE, 
	"VAULT_IN_TIME" VARCHAR2(5 BYTE), 
	"DVAULT_DATE" DATE, 
	"DVAULT_TIME" VARCHAR2(5 BYTE), 
	"DVAULT_BY_ID" NUMBER(10,0), 
	"DVAULT_BY_NM" VARCHAR2(250 BYTE), 
	"ASSIST_BY_ID" NUMBER(10,0), 
	"ASSIST_BY_NM" VARCHAR2(250 BYTE), 
	"VFYD_BY_ID" NUMBER(10,0), 
	"VFYD_BY_NM" VARCHAR2(250 BYTE), 
	"VAULT_TYPE" NUMBER(10,0), 
	"VAULT_ID" NUMBER(10,0), 
	"VAULT_NM" VARCHAR2(250 BYTE), 
	"VAULT_LOC_ID" VARCHAR2(50 BYTE), 
	"VAULT_LOC_NM" VARCHAR2(250 BYTE), 
	"VAULT_SRC_ID" NUMBER(10,0), 
	"VAULT_SRC_NM" VARCHAR2(250 BYTE), 
	"INPUT_TYPE" NUMBER(10,0), 
	"DOC_STAT" NUMBER(10,0), 
	"DOC_MODE" NUMBER(10,0), 
	"PRJ_ID" VARCHAR2(40 BYTE), 
	"FY_ID" NUMBER(4,0), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_NM_CREATE" VARCHAR2(250 BYTE), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_NM_MOD" VARCHAR2(250 BYTE), 
	"USR_ID_MOD_DT" DATE, 
	"ASSIST_BY_VOUT_ID" NUMBER(26,6), 
	"ASSIST_BY_VOUT_NM" VARCHAR2(200 BYTE), 
	"INPT_TYP_BATCH" VARCHAR2(1 BYTE), 
	"INPT_TYP_BAR" VARCHAR2(1 BYTE), 
	"INPT_TYP_SMPL" VARCHAR2(1 BYTE), 
	"TOT_GROSS_WT_GM_IN" NUMBER(26,6), 
	"TOT_GROSS_WT_OZ_IN" NUMBER(26,6), 
	"TOT_NET_WT_GM_IN" NUMBER(26,6), 
	"TOT_NET_WT_OZ_IN" NUMBER(26,6), 
	"TOT_BAT_BAR_SAM_WT" NUMBER(26,6), 
	"TOT_GROSS_WT_GM_OUT" NUMBER(26,6), 
	"TOT_GROSS_WT_OZ_OUT" NUMBER(26,6), 
	"TOT_NET_WT_GM_OUT" NUMBER(26,6), 
	"TOT_NET_WT_OZ_OUT" NUMBER(26,6), 
	"SCRTY_STFF_IN_ID" NUMBER(10,0), 
	"SCRTY_STFF_IN_NM" VARCHAR2(250 BYTE), 
	"SCRTY_STFF_OUT_ID" NUMBER(10,0), 
	"SCRTY_STFF_OUT_NM" VARCHAR2(250 BYTE)
   ) ;
  GRANT FLASHBACK ON "SLS"."SLS$VAULT" TO "MM";
  GRANT DEBUG ON "SLS"."SLS$VAULT" TO "MM";
  GRANT QUERY REWRITE ON "SLS"."SLS$VAULT" TO "MM";
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$VAULT" TO "MM";
  GRANT REFERENCES ON "SLS"."SLS$VAULT" TO "MM";
  GRANT UPDATE ON "SLS"."SLS$VAULT" TO "MM";
  GRANT SELECT ON "SLS"."SLS$VAULT" TO "MM";
  GRANT INSERT ON "SLS"."SLS$VAULT" TO "MM";
  GRANT INDEX ON "SLS"."SLS$VAULT" TO "MM";
  GRANT DELETE ON "SLS"."SLS$VAULT" TO "MM";
  GRANT ALTER ON "SLS"."SLS$VAULT" TO "MM";
