--------------------------------------------------------
--  DDL for Table SLS$DOC$CONF$FLX
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$DOC$CONF$FLX" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"FIELD_ID" VARCHAR2(20 BYTE), 
	"FIELD_VAL" VARCHAR2(500 BYTE), 
	"DATA_TYPE" NUMBER(5,0), 
	"DATA_LEN" NUMBER(5,0), 
	"REQD" VARCHAR2(1 BYTE), 
	"USR_ID_CREATE" NUMBER(10,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(10,0), 
	"USR_ID_MOD_DT" DATE, 
	"DOC_ID_SRC" VARCHAR2(40 BYTE), 
	"DOC_FRZ" VARCHAR2(1 BYTE) DEFAULT 'N'
   ) ;
  GRANT SELECT ON "SLS"."SLS$DOC$CONF$FLX" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$DOC$CONF$FLX" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$DOC$CONF$FLX" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$DOC$CONF$FLX" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$DOC$CONF$FLX" TO "APP" WITH GRANT OPTION;
  GRANT ALTER ON "SLS"."SLS$DOC$CONF$FLX" TO "APP";
  GRANT DEBUG ON "SLS"."SLS$DOC$CONF$FLX" TO "APP";
  GRANT DELETE ON "SLS"."SLS$DOC$CONF$FLX" TO "APP";
  GRANT FLASHBACK ON "SLS"."SLS$DOC$CONF$FLX" TO "APP";
  GRANT INDEX ON "SLS"."SLS$DOC$CONF$FLX" TO "APP";
  GRANT INSERT ON "SLS"."SLS$DOC$CONF$FLX" TO "APP";
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$DOC$CONF$FLX" TO "APP";
  GRANT QUERY REWRITE ON "SLS"."SLS$DOC$CONF$FLX" TO "APP";
  GRANT REFERENCES ON "SLS"."SLS$DOC$CONF$FLX" TO "APP";
  GRANT UPDATE ON "SLS"."SLS$DOC$CONF$FLX" TO "APP";
