--------------------------------------------------------
--  DDL for Table SLS$INTM$SLIP$ITM
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$INTM$SLIP$ITM" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"DOC_DT" DATE, 
	"SHIPMNT_DOC_ID" VARCHAR2(40 BYTE), 
	"ITM_ID" VARCHAR2(50 BYTE), 
	"ITM_UOM" VARCHAR2(20 BYTE), 
	"ITM_PRICE" NUMBER(26,6), 
	"SHIPMNT_ITM_QTY" NUMBER(26,6), 
	"SOLD_QTY" NUMBER(26,6), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE DEFAULT SYSDATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"BAL_QTY" NUMBER(26,6), 
	"SO_ID" VARCHAR2(40 BYTE), 
	"ITM_UOM_BS" VARCHAR2(20 BYTE), 
	"UOM_CONV_FCTR" NUMBER(26,6), 
	"ITM_QTY_BS" NUMBER(26,6), 
	"PICK_ID" VARCHAR2(40 BYTE), 
	"AMC_FLG" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"WTY_ID" VARCHAR2(20 BYTE), 
	"ITM_SR_NO" NUMBER(10,0) DEFAULT 1, 
	"CNT_QTY" NUMBER(26,6) DEFAULT 0
   ) ;
  GRANT DEBUG ON "SLS"."SLS$INTM$SLIP$ITM" TO "MNF" WITH GRANT OPTION;
  GRANT SELECT ON "SLS"."SLS$INTM$SLIP$ITM" TO "SVC";
  GRANT ALTER ON "SLS"."SLS$INTM$SLIP$ITM" TO "MNF" WITH GRANT OPTION;
  GRANT SELECT ON "SLS"."SLS$INTM$SLIP$ITM" TO "APP";
  GRANT ALTER ON "SLS"."SLS$INTM$SLIP$ITM" TO PUBLIC;
  GRANT DELETE ON "SLS"."SLS$INTM$SLIP$ITM" TO PUBLIC;
  GRANT INDEX ON "SLS"."SLS$INTM$SLIP$ITM" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$INTM$SLIP$ITM" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$INTM$SLIP$ITM" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$INTM$SLIP$ITM" TO PUBLIC;
  GRANT REFERENCES ON "SLS"."SLS$INTM$SLIP$ITM" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$INTM$SLIP$ITM" TO PUBLIC;
  GRANT QUERY REWRITE ON "SLS"."SLS$INTM$SLIP$ITM" TO PUBLIC;
  GRANT DEBUG ON "SLS"."SLS$INTM$SLIP$ITM" TO PUBLIC;
  GRANT FLASHBACK ON "SLS"."SLS$INTM$SLIP$ITM" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$INTM$SLIP$ITM" TO "MNF" WITH GRANT OPTION;
  GRANT SELECT ON "SLS"."SLS$INTM$SLIP$ITM" TO "MNF" WITH GRANT OPTION;
  GRANT REFERENCES ON "SLS"."SLS$INTM$SLIP$ITM" TO "MNF" WITH GRANT OPTION;
  GRANT QUERY REWRITE ON "SLS"."SLS$INTM$SLIP$ITM" TO "MNF" WITH GRANT OPTION;
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$INTM$SLIP$ITM" TO "MNF" WITH GRANT OPTION;
  GRANT INSERT ON "SLS"."SLS$INTM$SLIP$ITM" TO "MNF" WITH GRANT OPTION;
  GRANT INDEX ON "SLS"."SLS$INTM$SLIP$ITM" TO "MNF" WITH GRANT OPTION;
  GRANT FLASHBACK ON "SLS"."SLS$INTM$SLIP$ITM" TO "MNF" WITH GRANT OPTION;
  GRANT DELETE ON "SLS"."SLS$INTM$SLIP$ITM" TO "MNF" WITH GRANT OPTION;
