--------------------------------------------------------
--  DDL for Table SLS$SRVC$INV$ITM
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$SRVC$INV$ITM" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"SO_ID" VARCHAR2(40 BYTE), 
	"ITM_ID" VARCHAR2(50 BYTE), 
	"ITM_TYPE_EXPNS" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"ITM_RATE" NUMBER(26,6), 
	"ITM_UOM" VARCHAR2(20 BYTE), 
	"ITM_QTY" NUMBER(26,6), 
	"ITM_DISC_TYP" VARCHAR2(1 BYTE), 
	"ITM_DISC_VAL" NUMBER(26,6), 
	"ITM_AMT_BS" NUMBER(26,6), 
	"ITM_AMT_SP" NUMBER(26,6), 
	"REMARKS" VARCHAR2(1000 BYTE), 
	"TLRNC_QTY_TYPE" VARCHAR2(1 BYTE), 
	"TLRNC_QTY_VAL" NUMBER(26,6), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE DEFAULT SYSDATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"TAX_RULE_FLG" VARCHAR2(1 BYTE), 
	"SCH_ID" VARCHAR2(40 BYTE), 
	"SUPPLI_ITM_RATE" NUMBER, 
	"OLD_ITM_RATE" NUMBER(26,6), 
	"ITM_AMT_GS_SP" NUMBER(26,6), 
	"ITM_AMT_GS_BS" NUMBER(26,6), 
	"WTY_ID" VARCHAR2(20 BYTE), 
	"SCHM_FLG" VARCHAR2(1 BYTE), 
	"ASBL_AMT_BS" NUMBER(26,6), 
	"ASBL_AMT_SP" NUMBER(26,6), 
	"OLD_ITM_SHIP_QTY" NUMBER(26,6), 
	"CC_ID" VARCHAR2(45 BYTE), 
	"EO_PART_NO" VARCHAR2(250 BYTE), 
	"AMC_FLG" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"ITM_SLS_EXP_AMT" NUMBER(26,6) DEFAULT 0, 
	"ITM_GRP_ID_CC" VARCHAR2(20 BYTE), 
	"CNT_QTY" NUMBER(26,6) DEFAULT 0, 
	"OC_AMT_SP" NUMBER(26,6) DEFAULT 0, 
	"OC_AMT_BS" NUMBER(26,6) DEFAULT 0, 
	"INCL_TX" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"ITM_SO_AMT" NUMBER(26,6) DEFAULT 0, 
	"ITM_EXP_AMT" NUMBER(26,6) DEFAULT 0, 
	"ITM_PEND_AMT" NUMBER(26,6) DEFAULT 0, 
	"CURR_CONV_FCTR" NUMBER(26,6), 
	"CURR_ID_SP" NUMBER(10,0), 
	"CURR_ID_BS" NUMBER(10,0), 
	"TAX_AMT_SP" NUMBER(26,6), 
	"TAX_AMT_BS" NUMBER(26,6), 
	"TOT_ITM_AMT_SP" NUMBER(26,6), 
	"TOT_ITM_AMT_BS" NUMBER(26,6), 
	"DLV_QTY" NUMBER(26,6), 
	"DLV_SCHDL_NO" NUMBER(4,0), 
	"ITM_UOM_BS" VARCHAR2(20 BYTE), 
	"DISC_TYPE" NUMBER(4,0) DEFAULT 1420, 
	"DISC_VAL" NUMBER(26,6) DEFAULT 0, 
	"ITM_DISC_VAL_BS" NUMBER(26,6), 
	"ASSESS_AMT" NUMBER(26,6) DEFAULT 0
   ) ;
  GRANT SELECT ON "SLS"."SLS$SRVC$INV$ITM" TO "APP";
  GRANT INSERT ON "SLS"."SLS$SRVC$INV$ITM" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$SRVC$INV$ITM" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$SRVC$INV$ITM" TO PUBLIC;
  GRANT ALTER ON "SLS"."SLS$SRVC$INV$ITM" TO PUBLIC;
  GRANT DELETE ON "SLS"."SLS$SRVC$INV$ITM" TO PUBLIC;
  GRANT INDEX ON "SLS"."SLS$SRVC$INV$ITM" TO PUBLIC;
  GRANT REFERENCES ON "SLS"."SLS$SRVC$INV$ITM" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$SRVC$INV$ITM" TO PUBLIC;
  GRANT QUERY REWRITE ON "SLS"."SLS$SRVC$INV$ITM" TO PUBLIC;
  GRANT DEBUG ON "SLS"."SLS$SRVC$INV$ITM" TO PUBLIC;
  GRANT FLASHBACK ON "SLS"."SLS$SRVC$INV$ITM" TO PUBLIC;
