--------------------------------------------------------
--  DDL for Table SLS$TRNP$VHCL$REG$DTL
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$TRNP$VHCL$REG$DTL" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"VHCL_REG_NO" VARCHAR2(40 BYTE), 
	"MILEAGE_LOAD" NUMBER(26,6), 
	"MILEAGE_EMPTY" NUMBER(26,6), 
	"FULL_TANK" NUMBER(26,6), 
	"GROSS_WT" NUMBER(26,6), 
	"CAP_CC" NUMBER(26,6), 
	"TRNSP_LIC_DT" DATE, 
	"INSPCTN_DUE_DT" DATE, 
	"INSURE_DUE_DT" DATE, 
	"ITM_SR_NO" VARCHAR2(20 BYTE), 
	"ACTV" VARCHAR2(1 BYTE), 
	"INACTV_RESN" VARCHAR2(200 BYTE), 
	"INACTV_DT" DATE, 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"DIST_UOM" VARCHAR2(20 BYTE), 
	"FUEL_UOM" VARCHAR2(20 BYTE), 
	"ENGINE_NO" VARCHAR2(40 BYTE), 
	"CHASIS_NO" VARCHAR2(40 BYTE), 
	"TRNSP_ID" NUMBER(5,0), 
	"VHCL_WT_UOM" VARCHAR2(20 BYTE), 
	"ROUTE_TYP" NUMBER(2,0), 
	"CAP_WT" NUMBER(26,6), 
	"VHCL_REG_DT" DATE, 
	"TRNSP_LIC_EXP_DT" DATE, 
	"INSURE_EXP_DT" DATE, 
	"PERMIT_ISSU_DT" DATE, 
	"PERMIT_EXP_DT" DATE, 
	"SPD_GOV_NO" VARCHAR2(40 BYTE), 
	"INSURE_NO" VARCHAR2(40 BYTE), 
	"YEAR_OF_MNF" DATE, 
	"ENGINE_TYPE" NUMBER(2,0), 
	"VHCL_SERVC_KM" NUMBER(26,6), 
	"HEIGHT_CERT_DT" DATE, 
	"HEIGHT_CERT_NO" VARCHAR2(40 BYTE), 
	"WGHT_TOLRNCE" NUMBER(26,6), 
	"INIT_METR_READ" NUMBER(26,6) DEFAULT 0, 
	"DEF_DRIVER_NM" VARCHAR2(200 BYTE), 
	"CARRIER_LIC_NO" VARCHAR2(40 BYTE), 
	"CARRIER_ISSUE_DT" DATE, 
	"CARRIER_EXPIRY_DT" DATE
   ) ;

   COMMENT ON COLUMN "SLS"."SLS$TRNP$VHCL$REG$DTL"."ROUTE_TYP" IS 'Long Route or Short Route';
   COMMENT ON COLUMN "SLS"."SLS$TRNP$VHCL$REG$DTL"."SPD_GOV_NO" IS 'Stores the speed governing no. of a Vehicle.';
   COMMENT ON COLUMN "SLS"."SLS$TRNP$VHCL$REG$DTL"."INSURE_NO" IS 'To Store the insurance no. of a Vehicle.';
   COMMENT ON COLUMN "SLS"."SLS$TRNP$VHCL$REG$DTL"."ENGINE_TYPE" IS 'Diesel, Petrol, CNG or Lubricant.';
  GRANT INSERT ON "SLS"."SLS$TRNP$VHCL$REG$DTL" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$TRNP$VHCL$REG$DTL" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$TRNP$VHCL$REG$DTL" TO PUBLIC;
