--------------------------------------------------------
--  DDL for Table SLS$QUOT$ITM$SCHM$AMD_MAINTEMP
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$QUOT$ITM$SCHM$AMD_MAINTEMP" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"AMD_NO" VARCHAR2(40 BYTE), 
	"AMD_DT" DATE, 
	"SR_NO" NUMBER(5,0), 
	"SCHM_ID" VARCHAR2(20 BYTE), 
	"DEST_ITM_ID" VARCHAR2(50 BYTE), 
	"ITM_ID" VARCHAR2(50 BYTE), 
	"ITM_FREE_QTY" NUMBER(26,6), 
	"ITM_PRICE" NUMBER(26,6), 
	"ITM_VAL" NUMBER(26,6), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE DEFAULT SYSDATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE
   ) ;
  GRANT REFERENCES ON "SLS"."SLS$QUOT$ITM$SCHM$AMD_MAINTEMP" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$QUOT$ITM$SCHM$AMD_MAINTEMP" TO PUBLIC;
  GRANT QUERY REWRITE ON "SLS"."SLS$QUOT$ITM$SCHM$AMD_MAINTEMP" TO PUBLIC;
  GRANT DEBUG ON "SLS"."SLS$QUOT$ITM$SCHM$AMD_MAINTEMP" TO PUBLIC;
  GRANT FLASHBACK ON "SLS"."SLS$QUOT$ITM$SCHM$AMD_MAINTEMP" TO PUBLIC;
  GRANT ALTER ON "SLS"."SLS$QUOT$ITM$SCHM$AMD_MAINTEMP" TO PUBLIC;
  GRANT DELETE ON "SLS"."SLS$QUOT$ITM$SCHM$AMD_MAINTEMP" TO PUBLIC;
  GRANT INDEX ON "SLS"."SLS$QUOT$ITM$SCHM$AMD_MAINTEMP" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$QUOT$ITM$SCHM$AMD_MAINTEMP" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$QUOT$ITM$SCHM$AMD_MAINTEMP" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$QUOT$ITM$SCHM$AMD_MAINTEMP" TO PUBLIC;
