--------------------------------------------------------
--  DDL for Table SLS$TRNP$RECONCILE$CALC$GL
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$TRNP$RECONCILE$CALC$GL" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"LR_DOC_ID" VARCHAR2(40 BYTE), 
	"COA_ID" NUMBER(10,0), 
	"COA_NM" VARCHAR2(100 BYTE), 
	"AMT_SP" NUMBER(26,6), 
	"AMT_BS" NUMBER(26,6), 
	"SR_NO" NUMBER(3,0), 
	"TRAN_TYPE" VARCHAR2(2 BYTE), 
	"TRAN_CAT" VARCHAR2(20 BYTE), 
	"AP_SR_NO" NUMBER(3,0), 
	"CC_ID" VARCHAR2(40 BYTE), 
	"GL_TYPE_ID" NUMBER(5,0), 
	"GL_NO" NUMBER(2,0), 
	"GL_ADD_NARR" VARCHAR2(100 BYTE)
   ) ;
  GRANT SELECT ON "SLS"."SLS$TRNP$RECONCILE$CALC$GL" TO "FIN";
  GRANT INSERT ON "SLS"."SLS$TRNP$RECONCILE$CALC$GL" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$TRNP$RECONCILE$CALC$GL" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$TRNP$RECONCILE$CALC$GL" TO PUBLIC;
