--------------------------------------------------------
--  DDL for Table SLS$SO$DLV$SCHDL$ASMBL
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$SO$DLV$SCHDL$ASMBL" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"ITM_SR_NO" NUMBER(10,0) DEFAULT 1, 
	"ITM_ID" VARCHAR2(50 BYTE), 
	"ITM_ID_COMP" VARCHAR2(50 BYTE), 
	"DLV_DT" DATE, 
	"TOT_QTY" NUMBER(26,6), 
	"DLV_MODE" NUMBER(20,0), 
	"DLV_QTY" NUMBER(26,6), 
	"DLV_QTY_COMP_ITM" NUMBER(26,6), 
	"TLRNC_QTY_TYPE" VARCHAR2(1 BYTE), 
	"TLRNC_QTY_VAL" NUMBER(26,6), 
	"WH_ID" VARCHAR2(20 BYTE), 
	"DLV_ADDS_ID" VARCHAR2(20 BYTE), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE DEFAULT SYSDATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"DLV_SCHDL_NO" NUMBER(4,0), 
	"AVL_QTY" NUMBER(26,6), 
	"ITM_UOM_BS" VARCHAR2(20 BYTE), 
	"UOM_CONV_FCTR" NUMBER(26,6), 
	"DLV_QTY_BS" NUMBER(26,6), 
	"DLV_QTY_COMP_ITM_BS" NUMBER(26,6), 
	"BAL_QTY" NUMBER(26,6), 
	"ITM_UOM" VARCHAR2(20 BYTE), 
	"REMARKS" VARCHAR2(250 BYTE), 
	"PLN_QTY" NUMBER(26,6), 
	"PRJ_ID" VARCHAR2(40 BYTE) DEFAULT 'PROJ0000', 
	"TMP_BAL_QTY" NUMBER(26,6) DEFAULT 0, 
	"RSRV_QTY" NUMBER(26,6), 
	"CNT_QTY" NUMBER(26,6) DEFAULT 0, 
	"DLV_TYPE" NUMBER(20,0), 
	"GTC_ID" VARCHAR2(40 BYTE), 
	"SHIP_FLG" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"ATC_ID" VARCHAR2(40 BYTE), 
	"PO_DOC_ID" VARCHAR2(40 BYTE), 
	"RETURN_QTY" NUMBER(26,6), 
	"PI_BAL_QTY" NUMBER(26,6) DEFAULT 0
   ) ;
  GRANT ALTER ON "SLS"."SLS$SO$DLV$SCHDL$ASMBL" TO PUBLIC;
  GRANT DELETE ON "SLS"."SLS$SO$DLV$SCHDL$ASMBL" TO PUBLIC;
  GRANT INDEX ON "SLS"."SLS$SO$DLV$SCHDL$ASMBL" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$SO$DLV$SCHDL$ASMBL" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$SO$DLV$SCHDL$ASMBL" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$SO$DLV$SCHDL$ASMBL" TO PUBLIC;
  GRANT REFERENCES ON "SLS"."SLS$SO$DLV$SCHDL$ASMBL" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$SO$DLV$SCHDL$ASMBL" TO PUBLIC;
  GRANT QUERY REWRITE ON "SLS"."SLS$SO$DLV$SCHDL$ASMBL" TO PUBLIC;
  GRANT DEBUG ON "SLS"."SLS$SO$DLV$SCHDL$ASMBL" TO PUBLIC;
  GRANT FLASHBACK ON "SLS"."SLS$SO$DLV$SCHDL$ASMBL" TO PUBLIC;
