--------------------------------------------------------
--  DDL for Table SLS$PRFM$INV$HDR
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$PRFM$INV$HDR" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"DOC_DT" DATE, 
	"CURR_ID_SP" NUMBER(20,0), 
	"CURR_RATE" NUMBER(26,6), 
	"EO_ID" NUMBER(20,0), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"TOT_AMT_SP" NUMBER(26,6), 
	"TOT_AMT_BS" NUMBER(26,6), 
	"DISP_DOC_ID" VARCHAR2(20 BYTE), 
	"TAX_RULE_FLG" VARCHAR2(1 BYTE), 
	"CURR_ID_BS" NUMBER(20,0), 
	"PRFM_STAT" NUMBER(10,0), 
	"COA_ID" NUMBER(10,0), 
	"REMARKS" VARCHAR2(1000 BYTE), 
	"FY_ID" NUMBER(5,0), 
	"PRFM_MODE" NUMBER(10,0), 
	"EXT_DOC_NO" VARCHAR2(100 BYTE), 
	"EXT_DOC_DT" DATE, 
	"TOT_ITM_AMT_GS_SP" NUMBER(26,6), 
	"TOT_ITM_AMT_GS_BS" NUMBER(26,6), 
	"PRJ_ID" VARCHAR2(40 BYTE) DEFAULT 'PROJ0000', 
	"CNFRM_FLG" VARCHAR2(1 BYTE) DEFAULT 'N'
   ) ;
  GRANT FLASHBACK ON "SLS"."SLS$PRFM$INV$HDR" TO PUBLIC;
  GRANT DEBUG ON "SLS"."SLS$PRFM$INV$HDR" TO PUBLIC;
  GRANT QUERY REWRITE ON "SLS"."SLS$PRFM$INV$HDR" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$PRFM$INV$HDR" TO PUBLIC;
  GRANT REFERENCES ON "SLS"."SLS$PRFM$INV$HDR" TO PUBLIC;
  GRANT INDEX ON "SLS"."SLS$PRFM$INV$HDR" TO PUBLIC;
  GRANT DELETE ON "SLS"."SLS$PRFM$INV$HDR" TO PUBLIC;
  GRANT ALTER ON "SLS"."SLS$PRFM$INV$HDR" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$PRFM$INV$HDR" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$PRFM$INV$HDR" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$PRFM$INV$HDR" TO PUBLIC;
