--------------------------------------------------------
--  DDL for Table SLS$RMA$ITM$SR_24012020
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$RMA$ITM$SR_24012020" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"DOC_DT" DATE, 
	"SHIPMNT_ID" VARCHAR2(40 BYTE), 
	"SHIPMNT_DT" DATE, 
	"LOT_ID" VARCHAR2(20 BYTE), 
	"SR_NO" VARCHAR2(100 BYTE), 
	"BIN_ID" VARCHAR2(20 BYTE), 
	"ITM_ID" VARCHAR2(50 BYTE), 
	"ITM_UOM" VARCHAR2(20 BYTE), 
	"SR_QTY" NUMBER(26,6), 
	"SR_QTY_BS" NUMBER(26,6), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"WH_ID" VARCHAR2(20 BYTE), 
	"SO_ID" VARCHAR2(40 BYTE), 
	"PICK_ID" VARCHAR2(40 BYTE), 
	"PRJ_ID" VARCHAR2(40 BYTE), 
	"SR_STAT" VARCHAR2(1 BYTE), 
	"ITM_SR_NO" NUMBER(10,0), 
	"SR_NO1" VARCHAR2(100 BYTE), 
	"SR_NO2" VARCHAR2(100 BYTE), 
	"CNT_QTY" NUMBER(26,6)
   ) ;
