--------------------------------------------------------
--  DDL for Table SLS$EXPNS$INVC$TR$LINES
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$EXPNS$INVC$TR$LINES" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"DOC_ID_SRC" VARCHAR2(40 BYTE), 
	"ITM_ID" VARCHAR2(50 BYTE), 
	"EXP_TYPE" NUMBER(5,0), 
	"EXP_COA_ID" NUMBER(10,0), 
	"TAX_RULE_ID" NUMBER(10,0), 
	"TAX_RULE_FLG" VARCHAR2(1 BYTE), 
	"TAX_TYPE" NUMBER(10,0), 
	"TAX_COA_ID" NUMBER(10,0), 
	"TAX_AMT_SP" NUMBER(26,6), 
	"TAX_AMT_BS" NUMBER(26,6), 
	"TAX_PER" NUMBER(26,6), 
	"TAX_RULE_SLNO" NUMBER(2,0), 
	"TAX_RULE_PRIORITY" NUMBER(2,0), 
	"TAX_CALC_AMT_SP" NUMBER(26,6), 
	"TAX_CALC_AMT_BS" NUMBER(26,6), 
	"EXMPT_PCT" NUMBER(5,2) DEFAULT 0, 
	"EXMPT_AMT" NUMBER(26,6) DEFAULT 0
   ) ;
  GRANT FLASHBACK ON "SLS"."SLS$EXPNS$INVC$TR$LINES" TO PUBLIC;
  GRANT DEBUG ON "SLS"."SLS$EXPNS$INVC$TR$LINES" TO PUBLIC;
  GRANT QUERY REWRITE ON "SLS"."SLS$EXPNS$INVC$TR$LINES" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$EXPNS$INVC$TR$LINES" TO PUBLIC;
  GRANT REFERENCES ON "SLS"."SLS$EXPNS$INVC$TR$LINES" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$EXPNS$INVC$TR$LINES" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$EXPNS$INVC$TR$LINES" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$EXPNS$INVC$TR$LINES" TO PUBLIC;
  GRANT INDEX ON "SLS"."SLS$EXPNS$INVC$TR$LINES" TO PUBLIC;
  GRANT DELETE ON "SLS"."SLS$EXPNS$INVC$TR$LINES" TO PUBLIC;
  GRANT ALTER ON "SLS"."SLS$EXPNS$INVC$TR$LINES" TO PUBLIC;
