--------------------------------------------------------
--  DDL for Table SLS$INCT$PLCY
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$INCT$PLCY" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"PLCY_ID" VARCHAR2(20 BYTE), 
	"PLCY_EFFCT_DT" DATE, 
	"TRGT_TYPE" NUMBER(5,0), 
	"AMT_TYPE" VARCHAR2(1 BYTE), 
	"FREQ_BASIS" NUMBER(20,0), 
	"FY_ID" NUMBER(2,0), 
	"PLCY_STAT" NUMBER(5,0), 
	"PRJ_ID" VARCHAR2(40 BYTE), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"PLCY_ON" NUMBER(10,0) DEFAULT 2231, 
	"TRGT_BASIS" NUMBER(5,0)
   ) ;

   COMMENT ON COLUMN "SLS"."SLS$INCT$PLCY"."TRGT_TYPE" IS '1 - COLLECTION, 2 - REVENUE';
   COMMENT ON COLUMN "SLS"."SLS$INCT$PLCY"."AMT_TYPE" IS 'A - AMOUNT, P - PERCENTAGE';
   COMMENT ON COLUMN "SLS"."SLS$INCT$PLCY"."FREQ_BASIS" IS '1 - DAILY, 2- WEEKLY, 3- QUARTERLY, 4- HALFYEARLY, 5- MONTHLY';
  GRANT FLASHBACK ON "SLS"."SLS$INCT$PLCY" TO PUBLIC;
  GRANT ALTER ON "SLS"."SLS$INCT$PLCY" TO PUBLIC;
  GRANT DELETE ON "SLS"."SLS$INCT$PLCY" TO PUBLIC;
  GRANT INDEX ON "SLS"."SLS$INCT$PLCY" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$INCT$PLCY" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$INCT$PLCY" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$INCT$PLCY" TO PUBLIC;
  GRANT REFERENCES ON "SLS"."SLS$INCT$PLCY" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$INCT$PLCY" TO PUBLIC;
  GRANT QUERY REWRITE ON "SLS"."SLS$INCT$PLCY" TO PUBLIC;
  GRANT DEBUG ON "SLS"."SLS$INCT$PLCY" TO PUBLIC;
