--------------------------------------------------------
--  DDL for Table SLS$SO$ITM$DISC
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$SO$ITM$DISC" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"ITM_ID" VARCHAR2(50 BYTE), 
	"ITM_RATE" NUMBER(26,6), 
	"ITM_UOM" VARCHAR2(20 BYTE), 
	"ITM_QTY" NUMBER(26,6), 
	"ITM_SR_NO" NUMBER(5,0), 
	"SR_NO" NUMBER(5,0), 
	"EXT_DOC_RCVD" VARCHAR2(1 BYTE), 
	"EXT_DOC_NO" VARCHAR2(50 BYTE), 
	"EXT_DOC_DT" DATE, 
	"CUST_NM" VARCHAR2(100 BYTE), 
	"CUST_SHIP_ADD" VARCHAR2(1000 BYTE), 
	"LIST_PRICE" NUMBER(26,6), 
	"LOAD_VAL" NUMBER(26,6), 
	"MAX_SCHM_PRC" NUMBER(26,6), 
	"END_CUST_PRC" NUMBER(26,6), 
	"MAX_DISC_PRCNT" NUMBER(26,6), 
	"MAX_DISC_AMT" NUMBER(26,6), 
	"BASIC_CUST_PRC" NUMBER(26,6), 
	"BASIC_CUST_PRC_CALC" NUMBER(26,6), 
	"BASIC_CUST_PRC_FINAL" NUMBER(26,6), 
	"BASIC_CUST_PRC_ADJ" NUMBER(26,6), 
	"DISC_APLCBL_PRCNT" NUMBER(26,6), 
	"ENQ_FLG" VARCHAR2(1 BYTE), 
	"DISC_VAL" NUMBER(26,6), 
	"PEND_ADJ_AMT" NUMBER(26,6), 
	"DISC_ADJ_REMAIN" NUMBER(26,6), 
	"DISC_ADJ_TYPE" VARCHAR2(1 BYTE), 
	"DISC_ADJ_FLG" VARCHAR2(1 BYTE), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE DEFAULT SYSDATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"SRC_SO_DOC_ID" VARCHAR2(40 BYTE), 
	"ENQ_REF_NO" VARCHAR2(50 BYTE), 
	"ENQ_REF_DT" DATE, 
	"REMARKS" VARCHAR2(1000 BYTE), 
	"EO_REF_ID" NUMBER(20,0), 
	"ASRTMNT_ID" VARCHAR2(50 BYTE)
   ) ;
  GRANT INSERT ON "SLS"."SLS$SO$ITM$DISC" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$SO$ITM$DISC" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$SO$ITM$DISC" TO PUBLIC;
