--------------------------------------------------------
--  DDL for Table SLS$TRNP$RECONCILE$TR
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$TRNP$RECONCILE$TR" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"LR_DOC_ID" VARCHAR2(40 BYTE), 
	"TAX_RULE_ID" NUMBER(10,0), 
	"TAX_RULE_FLG" VARCHAR2(1 BYTE), 
	"TAX_EXMPT_FLG" VARCHAR2(1 BYTE), 
	"TAX_AMT" NUMBER(26,6), 
	"TAX_AMT_BS" NUMBER(26,6), 
	"TAXABLE_AMT_SP" NUMBER(26,6), 
	"TAXABLE_AMT_BS" NUMBER(26,6)
   ) ;
  GRANT INSERT ON "SLS"."SLS$TRNP$RECONCILE$TR" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$TRNP$RECONCILE$TR" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$TRNP$RECONCILE$TR" TO PUBLIC;
