--------------------------------------------------------
--  DDL for Table SLS$RMA_201707
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$RMA_201707" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"DOC_DT" DATE, 
	"EO_ID" NUMBER(20,0), 
	"CURR_ID_SP" NUMBER(10,0), 
	"CURR_CONV_FCTR" NUMBER(26,6), 
	"RMA_TYP_ID" NUMBER(10,0), 
	"REASON" VARCHAR2(100 BYTE), 
	"REMARKS" VARCHAR2(250 BYTE), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"CURR_ID_BS" NUMBER(10,0), 
	"GATEPASS_DOC_ID" VARCHAR2(40 BYTE), 
	"GATEPASS_DOC_DT" DATE, 
	"RMA_ID" VARCHAR2(20 BYTE), 
	"GE_DOC_ID" VARCHAR2(40 BYTE), 
	"GE_DOC_DT" DATE, 
	"COA_ID" NUMBER(10,0), 
	"WH_ID" VARCHAR2(20 BYTE), 
	"FY_ID" NUMBER(5,0), 
	"RMA_MODE" NUMBER(10,0), 
	"COGS_VOU_ID" VARCHAR2(40 BYTE), 
	"CN_VOU_ID" VARCHAR2(40 BYTE), 
	"DISC_REVS_FLG" VARCHAR2(1 BYTE), 
	"PRJ_ID" VARCHAR2(40 BYTE), 
	"DEST_WH_ID" VARCHAR2(20 BYTE), 
	"SVC_CALL_ID" VARCHAR2(40 BYTE), 
	"RMA_STAT" NUMBER(10,0), 
	"ISSU_COGS_VOU_ID" VARCHAR2(40 BYTE)
   ) ;
  GRANT INSERT ON "SLS"."SLS$RMA_201707" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$RMA_201707" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$RMA_201707" TO PUBLIC;
