--------------------------------------------------------
--  DDL for Table SLS$EXPNS$INVC$TDS$RULE
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$EXPNS$INVC$TDS$RULE" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(5,0), 
	"TDS_RULE_APPL_INST_ID" NUMBER(1,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"DOC_ID_SRC" VARCHAR2(40 BYTE), 
	"DLV_SCHDL_NO" NUMBER(5,0), 
	"ITM_ID" VARCHAR2(50 BYTE), 
	"EXP_TYPE" NUMBER(5,0), 
	"EXP_COA_ID" NUMBER(10,0), 
	"TDS_RULE_ID" NUMBER(10,0), 
	"TDS_RULE_STRT_DT" DATE, 
	"TAXABLE_AMT_SP" NUMBER(26,6), 
	"TAXABLE_AMT_BS" NUMBER(26,6), 
	"TDS_AMT_SP" NUMBER(26,6), 
	"TDS_AMT_BS" NUMBER(26,6), 
	"EXMPT_FLG" VARCHAR2(1 BYTE) DEFAULT 'N'
   ) ;
  GRANT UPDATE ON "SLS"."SLS$EXPNS$INVC$TDS$RULE" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$EXPNS$INVC$TDS$RULE" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$EXPNS$INVC$TDS$RULE" TO PUBLIC;
