--------------------------------------------------------
--  DDL for Table SLS$SO$BATCH$CNCL$ITM
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$SO$BATCH$CNCL$ITM" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"DOC_ID_SO" VARCHAR2(40 BYTE), 
	"ITM_SR_NO" NUMBER(20,0), 
	"EO_ID" NUMBER(20,0), 
	"EO_CATG_ID" NUMBER(10,0), 
	"ITM_ID" VARCHAR2(50 BYTE), 
	"ITM_GRP_ID" VARCHAR2(50 BYTE), 
	"ORDER_TYPE" NUMBER(10,0), 
	"CNCL_REASON" VARCHAR2(50 BYTE), 
	"USR_ID_CREATE_SO" NUMBER(4,0), 
	"USR_ID_CREATE_DT_SO" DATE, 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE DEFAULT SYSDATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"DLV_DT" DATE, 
	"WH_ID" VARCHAR2(20 BYTE), 
	"CNSL_TIME" TIMESTAMP (6)
   ) ;
  GRANT INSERT ON "SLS"."SLS$SO$BATCH$CNCL$ITM" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$SO$BATCH$CNCL$ITM" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$SO$BATCH$CNCL$ITM" TO PUBLIC;
