--------------------------------------------------------
--  DDL for Table SLS$TRNP$LO$DOC$SRC
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$TRNP$LO$DOC$SRC" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"EO_ID" NUMBER(20,0), 
	"DEPARTURE_PNT" VARCHAR2(20 BYTE), 
	"ARRIVAL_PNT" VARCHAR2(20 BYTE), 
	"DOC_ID_SRC" VARCHAR2(40 BYTE), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"SCHDL_NO" NUMBER DEFAULT 1, 
	"SHIPMNT_DOC_ID" VARCHAR2(50 BYTE) DEFAULT '0'
   ) ;
  GRANT SELECT ON "SLS"."SLS$TRNP$LO$DOC$SRC" TO "APP";
  GRANT ALTER ON "SLS"."SLS$TRNP$LO$DOC$SRC" TO PUBLIC;
  GRANT DELETE ON "SLS"."SLS$TRNP$LO$DOC$SRC" TO PUBLIC;
  GRANT INDEX ON "SLS"."SLS$TRNP$LO$DOC$SRC" TO PUBLIC;
  GRANT REFERENCES ON "SLS"."SLS$TRNP$LO$DOC$SRC" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$TRNP$LO$DOC$SRC" TO PUBLIC;
  GRANT QUERY REWRITE ON "SLS"."SLS$TRNP$LO$DOC$SRC" TO PUBLIC;
  GRANT DEBUG ON "SLS"."SLS$TRNP$LO$DOC$SRC" TO PUBLIC;
  GRANT FLASHBACK ON "SLS"."SLS$TRNP$LO$DOC$SRC" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$TRNP$LO$DOC$SRC" TO PUBLIC;
  GRANT ALTER ON "SLS"."SLS$TRNP$LO$DOC$SRC" TO "APP";
  GRANT DEBUG ON "SLS"."SLS$TRNP$LO$DOC$SRC" TO "APP";
  GRANT DELETE ON "SLS"."SLS$TRNP$LO$DOC$SRC" TO "APP";
  GRANT FLASHBACK ON "SLS"."SLS$TRNP$LO$DOC$SRC" TO "APP";
  GRANT INDEX ON "SLS"."SLS$TRNP$LO$DOC$SRC" TO "APP";
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$TRNP$LO$DOC$SRC" TO "APP";
  GRANT QUERY REWRITE ON "SLS"."SLS$TRNP$LO$DOC$SRC" TO "APP";
  GRANT REFERENCES ON "SLS"."SLS$TRNP$LO$DOC$SRC" TO "APP";
  GRANT UPDATE ON "SLS"."SLS$TRNP$LO$DOC$SRC" TO "APP";
  GRANT SELECT ON "SLS"."SLS$TRNP$LO$DOC$SRC" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$TRNP$LO$DOC$SRC" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$TRNP$LO$DOC$SRC" TO "APP";
