--------------------------------------------------------
--  DDL for Table SLS$INCT$PLCY$DTL
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$INCT$PLCY$DTL" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"SL_NO" NUMBER(20,0), 
	"AMT_TYPE" VARCHAR2(1 BYTE), 
	"FREQ_BASIS" NUMBER(20,0), 
	"VLU_FROM_AMT" NUMBER(26,6), 
	"VLU_TO_AMT" NUMBER(26,6), 
	"INCT_IN_AMT" NUMBER(26,6), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE
   ) ;

   COMMENT ON COLUMN "SLS"."SLS$INCT$PLCY$DTL"."AMT_TYPE" IS 'A - AMOUNT, P - PERCENTAGE';
   COMMENT ON COLUMN "SLS"."SLS$INCT$PLCY$DTL"."FREQ_BASIS" IS '1 - DAILY, 2- WEEKLY, 3- QUARTERLY, 4- HALFYEARLY, 5- MONTHLY';
  GRANT INSERT ON "SLS"."SLS$INCT$PLCY$DTL" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$INCT$PLCY$DTL" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$INCT$PLCY$DTL" TO PUBLIC;
