--------------------------------------------------------
--  DDL for Table SLS$COM$QUOT$TNC
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$COM$QUOT$TNC" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"TNC_ID" NUMBER(10,0), 
	"PRIORITY" NUMBER(2,0), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE
   ) ;
  GRANT SELECT ON "SLS"."SLS$COM$QUOT$TNC" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$COM$QUOT$TNC" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$COM$QUOT$TNC" TO PUBLIC;
