--------------------------------------------------------
--  DDL for Table SLS$RMA$ITM$TMP
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$RMA$ITM$TMP" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"DOC_DT" DATE, 
	"ITM_ID" VARCHAR2(50 BYTE), 
	"GE_QTY" NUMBER(26,6), 
	"ITM_UOM" VARCHAR2(20 BYTE), 
	"ITM_PRICE" NUMBER(20,6), 
	"ITM_AMT_SP" NUMBER(26,6), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"GE_ID" VARCHAR2(40 BYTE), 
	"PRJ_ID" VARCHAR2(40 BYTE) DEFAULT 'PROJ0000', 
	"ITM_SR_NO" NUMBER(10,0) DEFAULT 1, 
	"CNT_QTY" NUMBER(26,6) DEFAULT 0, 
	"GE_QTY_BS" NUMBER(26,6) DEFAULT 0
   ) ;
  GRANT DELETE ON "SLS"."SLS$RMA$ITM$TMP" TO PUBLIC;
  GRANT ALTER ON "SLS"."SLS$RMA$ITM$TMP" TO PUBLIC;
  GRANT FLASHBACK ON "SLS"."SLS$RMA$ITM$TMP" TO PUBLIC;
  GRANT DEBUG ON "SLS"."SLS$RMA$ITM$TMP" TO PUBLIC;
  GRANT QUERY REWRITE ON "SLS"."SLS$RMA$ITM$TMP" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$RMA$ITM$TMP" TO PUBLIC;
  GRANT REFERENCES ON "SLS"."SLS$RMA$ITM$TMP" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$RMA$ITM$TMP" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$RMA$ITM$TMP" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$RMA$ITM$TMP" TO PUBLIC;
  GRANT INDEX ON "SLS"."SLS$RMA$ITM$TMP" TO PUBLIC;
