--------------------------------------------------------
--  DDL for Table SLS$TRNP$LO$EO$ADV
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$TRNP$LO$EO$ADV" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"EO_ID" NUMBER(20,0), 
	"PAY_MODE" NUMBER(20,0), 
	"PAY_TYPE_NO" VARCHAR2(30 BYTE), 
	"PAY_TYPE_DT" DATE, 
	"BANK_AC_NO" VARCHAR2(50 BYTE), 
	"ADDS_ID" VARCHAR2(20 BYTE), 
	"REMARKS" VARCHAR2(250 BYTE), 
	"SR_NO" NUMBER(5,0), 
	"TOT_AMT_SP" NUMBER(26,6), 
	"TOT_AMT_BS" NUMBER(26,6), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE DEFAULT SYSDATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"BANK_CASH_COA_ID" NUMBER(10,0)
   ) ;
  GRANT INSERT ON "SLS"."SLS$TRNP$LO$EO$ADV" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$TRNP$LO$EO$ADV" TO PUBLIC;
  GRANT ALTER ON "SLS"."SLS$TRNP$LO$EO$ADV" TO "FIN";
  GRANT DELETE ON "SLS"."SLS$TRNP$LO$EO$ADV" TO "FIN";
  GRANT INDEX ON "SLS"."SLS$TRNP$LO$EO$ADV" TO "FIN";
  GRANT INSERT ON "SLS"."SLS$TRNP$LO$EO$ADV" TO "FIN";
  GRANT SELECT ON "SLS"."SLS$TRNP$LO$EO$ADV" TO "FIN";
  GRANT UPDATE ON "SLS"."SLS$TRNP$LO$EO$ADV" TO "FIN";
  GRANT REFERENCES ON "SLS"."SLS$TRNP$LO$EO$ADV" TO "FIN";
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$TRNP$LO$EO$ADV" TO "FIN";
  GRANT QUERY REWRITE ON "SLS"."SLS$TRNP$LO$EO$ADV" TO "FIN";
  GRANT DEBUG ON "SLS"."SLS$TRNP$LO$EO$ADV" TO "FIN";
  GRANT FLASHBACK ON "SLS"."SLS$TRNP$LO$EO$ADV" TO "FIN";
  GRANT UPDATE ON "SLS"."SLS$TRNP$LO$EO$ADV" TO PUBLIC;
  GRANT DEBUG ON "SLS"."SLS$TRNP$LO$EO$ADV" TO PUBLIC;
