--------------------------------------------------------
--  DDL for Table SLS$INV$DTL
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$INV$DTL" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"DOC_DT" DATE, 
	"SHIP_ID" VARCHAR2(40 BYTE), 
	"SHIP_DT" DATE, 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"SHIP_AMT_SP" NUMBER(26,6), 
	"SHIP_AMT_BS" NUMBER(26,6)
   ) ;
  GRANT UPDATE ON "SLS"."SLS$INV$DTL" TO "APP";
  GRANT QUERY REWRITE ON "SLS"."SLS$INV$DTL" TO "APP";
  GRANT ALTER ON "SLS"."SLS$INV$DTL" TO "APP";
  GRANT FLASHBACK ON "SLS"."SLS$INV$DTL" TO PUBLIC;
  GRANT QUERY REWRITE ON "SLS"."SLS$INV$DTL" TO PUBLIC;
  GRANT DEBUG ON "SLS"."SLS$INV$DTL" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$INV$DTL" TO "MM";
  GRANT SELECT ON "SLS"."SLS$INV$DTL" TO "MM";
  GRANT REFERENCES ON "SLS"."SLS$INV$DTL" TO "MM";
  GRANT QUERY REWRITE ON "SLS"."SLS$INV$DTL" TO "MM";
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$INV$DTL" TO "MM";
  GRANT INSERT ON "SLS"."SLS$INV$DTL" TO "MM";
  GRANT INDEX ON "SLS"."SLS$INV$DTL" TO "MM";
  GRANT FLASHBACK ON "SLS"."SLS$INV$DTL" TO "MM";
  GRANT DELETE ON "SLS"."SLS$INV$DTL" TO "MM";
  GRANT DEBUG ON "SLS"."SLS$INV$DTL" TO "MM";
  GRANT ALTER ON "SLS"."SLS$INV$DTL" TO "MM";
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$INV$DTL" TO PUBLIC;
  GRANT REFERENCES ON "SLS"."SLS$INV$DTL" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$INV$DTL" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$INV$DTL" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$INV$DTL" TO PUBLIC;
  GRANT INDEX ON "SLS"."SLS$INV$DTL" TO PUBLIC;
  GRANT DELETE ON "SLS"."SLS$INV$DTL" TO PUBLIC;
  GRANT ALTER ON "SLS"."SLS$INV$DTL" TO PUBLIC;
  GRANT FLASHBACK ON "SLS"."SLS$INV$DTL" TO "APP";
  GRANT DELETE ON "SLS"."SLS$INV$DTL" TO "APP";
  GRANT INSERT ON "SLS"."SLS$INV$DTL" TO "APP";
  GRANT SELECT ON "SLS"."SLS$INV$DTL" TO "APP";
  GRANT REFERENCES ON "SLS"."SLS$INV$DTL" TO "APP";
  GRANT DELETE ON "SLS"."SLS$INV$DTL" TO "MNF" WITH GRANT OPTION;
  GRANT DEBUG ON "SLS"."SLS$INV$DTL" TO "MNF" WITH GRANT OPTION;
  GRANT ALTER ON "SLS"."SLS$INV$DTL" TO "MNF" WITH GRANT OPTION;
  GRANT UPDATE ON "SLS"."SLS$INV$DTL" TO "MNF" WITH GRANT OPTION;
  GRANT SELECT ON "SLS"."SLS$INV$DTL" TO "MNF" WITH GRANT OPTION;
  GRANT REFERENCES ON "SLS"."SLS$INV$DTL" TO "MNF" WITH GRANT OPTION;
  GRANT QUERY REWRITE ON "SLS"."SLS$INV$DTL" TO "MNF" WITH GRANT OPTION;
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$INV$DTL" TO "MNF" WITH GRANT OPTION;
  GRANT INSERT ON "SLS"."SLS$INV$DTL" TO "MNF" WITH GRANT OPTION;
  GRANT FLASHBACK ON "SLS"."SLS$INV$DTL" TO "MNF" WITH GRANT OPTION;
  GRANT INDEX ON "SLS"."SLS$INV$DTL" TO "MNF" WITH GRANT OPTION;
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$INV$DTL" TO "APP";
  GRANT DEBUG ON "SLS"."SLS$INV$DTL" TO "APP";
  GRANT FLASHBACK ON "SLS"."SLS$INV$DTL" TO "PMS";
  GRANT DEBUG ON "SLS"."SLS$INV$DTL" TO "PMS";
  GRANT QUERY REWRITE ON "SLS"."SLS$INV$DTL" TO "PMS";
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$INV$DTL" TO "PMS";
  GRANT REFERENCES ON "SLS"."SLS$INV$DTL" TO "PMS";
  GRANT UPDATE ON "SLS"."SLS$INV$DTL" TO "PMS";
  GRANT SELECT ON "SLS"."SLS$INV$DTL" TO "PMS";
  GRANT INSERT ON "SLS"."SLS$INV$DTL" TO "PMS";
  GRANT INDEX ON "SLS"."SLS$INV$DTL" TO "PMS";
  GRANT DELETE ON "SLS"."SLS$INV$DTL" TO "PMS";
  GRANT ALTER ON "SLS"."SLS$INV$DTL" TO "PMS";
  GRANT INDEX ON "SLS"."SLS$INV$DTL" TO "APP";
