--------------------------------------------------------
--  DDL for Table SLS$SRVC$INV$ITM$DTL
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$SRVC$INV$ITM$DTL" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(5,0), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"PO_ID" VARCHAR2(40 BYTE), 
	"ITM_ID" VARCHAR2(50 BYTE), 
	"SVC_ITM_ID" VARCHAR2(50 BYTE), 
	"ITM_QTY" NUMBER(26,6), 
	"ITM_PRICE" NUMBER(26,6), 
	"ITM_PRICE_BS" NUMBER(26,6), 
	"TOT_TAX_AMT_SP" NUMBER(26,6) DEFAULT 0, 
	"TOT_TAX_AMT_BS" NUMBER(26,6) DEFAULT 0, 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"ITM_UOM" VARCHAR2(20 BYTE), 
	"DISC_TYPE" NUMBER(4,0) DEFAULT 1420, 
	"DISC_VAL" NUMBER(26,6), 
	"SVC_ITM_UOM" VARCHAR2(100 BYTE)
   ) ;
  GRANT ALTER ON "SLS"."SLS$SRVC$INV$ITM$DTL" TO PUBLIC;
  GRANT DELETE ON "SLS"."SLS$SRVC$INV$ITM$DTL" TO PUBLIC;
  GRANT INDEX ON "SLS"."SLS$SRVC$INV$ITM$DTL" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$SRVC$INV$ITM$DTL" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$SRVC$INV$ITM$DTL" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$SRVC$INV$ITM$DTL" TO PUBLIC;
  GRANT REFERENCES ON "SLS"."SLS$SRVC$INV$ITM$DTL" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$SRVC$INV$ITM$DTL" TO PUBLIC;
  GRANT QUERY REWRITE ON "SLS"."SLS$SRVC$INV$ITM$DTL" TO PUBLIC;
  GRANT DEBUG ON "SLS"."SLS$SRVC$INV$ITM$DTL" TO PUBLIC;
  GRANT FLASHBACK ON "SLS"."SLS$SRVC$INV$ITM$DTL" TO PUBLIC;
