--------------------------------------------------------
--  DDL for Table SLS$SO$FREE$ITM$BIN_MAINTEMP
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$SO$FREE$ITM$BIN_MAINTEMP" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"WH_ID" VARCHAR2(20 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"DOC_DT" DATE, 
	"LOT_ID" VARCHAR2(20 BYTE), 
	"BIN_ID" VARCHAR2(20 BYTE), 
	"FREE_ITM_ID" VARCHAR2(50 BYTE), 
	"DEST_ITM_ID" VARCHAR2(50 BYTE), 
	"FREE_ITM_UOM" VARCHAR2(20 BYTE), 
	"FREE_ITM_QTY" NUMBER(26,6), 
	"FREE_ITM_QTY_BS" NUMBER(26,6)
   ) ;
  GRANT INSERT ON "SLS"."SLS$SO$FREE$ITM$BIN_MAINTEMP" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$SO$FREE$ITM$BIN_MAINTEMP" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$SO$FREE$ITM$BIN_MAINTEMP" TO PUBLIC;
