--------------------------------------------------------
--  DDL for Table SLS$USR$CRDT$SETUP
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$USR$CRDT$SETUP" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(1,0), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"CRDT_DISP_ID" VARCHAR2(20 BYTE), 
	"DOC_DT" DATE, 
	"USR_ID" NUMBER(4,0), 
	"CREDIT_LIMIT" NUMBER(26,6), 
	"STRT_DT" DATE, 
	"END_DT" DATE, 
	"STATUS" NUMBER(10,0), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE DEFAULT SYSDATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"FY_ID" NUMBER(5,0)
   ) ;
  GRANT FLASHBACK ON "SLS"."SLS$USR$CRDT$SETUP" TO PUBLIC;
  GRANT DEBUG ON "SLS"."SLS$USR$CRDT$SETUP" TO PUBLIC;
  GRANT QUERY REWRITE ON "SLS"."SLS$USR$CRDT$SETUP" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$USR$CRDT$SETUP" TO PUBLIC;
  GRANT REFERENCES ON "SLS"."SLS$USR$CRDT$SETUP" TO PUBLIC;
  GRANT INDEX ON "SLS"."SLS$USR$CRDT$SETUP" TO PUBLIC;
  GRANT DELETE ON "SLS"."SLS$USR$CRDT$SETUP" TO PUBLIC;
  GRANT ALTER ON "SLS"."SLS$USR$CRDT$SETUP" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$USR$CRDT$SETUP" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$USR$CRDT$SETUP" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$USR$CRDT$SETUP" TO PUBLIC;
