--------------------------------------------------------
--  DDL for Table SLS$SRVC$INV$FLX
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$SRVC$INV$FLX" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"FLD_ID" VARCHAR2(20 BYTE), 
	"FLD_VAL" VARCHAR2(500 BYTE), 
	"DATA_TYPE" NUMBER(5,0), 
	"DATA_LEN" NUMBER(5,0), 
	"REQD" VARCHAR2(1 BYTE), 
	"USR_ID_CREATE" NUMBER(10,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(10,0), 
	"USR_ID_MOD_DT" DATE
   ) ;
  GRANT INSERT ON "SLS"."SLS$SRVC$INV$FLX" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$SRVC$INV$FLX" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$SRVC$INV$FLX" TO PUBLIC;
  GRANT ALTER ON "SLS"."SLS$SRVC$INV$FLX" TO PUBLIC;
  GRANT DELETE ON "SLS"."SLS$SRVC$INV$FLX" TO PUBLIC;
  GRANT INDEX ON "SLS"."SLS$SRVC$INV$FLX" TO PUBLIC;
  GRANT REFERENCES ON "SLS"."SLS$SRVC$INV$FLX" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$SRVC$INV$FLX" TO PUBLIC;
  GRANT QUERY REWRITE ON "SLS"."SLS$SRVC$INV$FLX" TO PUBLIC;
  GRANT DEBUG ON "SLS"."SLS$SRVC$INV$FLX" TO PUBLIC;
  GRANT FLASHBACK ON "SLS"."SLS$SRVC$INV$FLX" TO PUBLIC;
