--------------------------------------------------------
--  DDL for Table SLS$OPP$ITM
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$OPP$ITM" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"ITM_ID" VARCHAR2(50 BYTE), 
	"ITM_PRICE" NUMBER(26,6), 
	"ITM_UOM" VARCHAR2(20 BYTE), 
	"ITM_QTY" NUMBER(26,6), 
	"ITM_EXP_PRICE" NUMBER(26,6), 
	"REMARKS" VARCHAR2(1000 BYTE), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"ITM_AMT_BS" NUMBER(26,6), 
	"ITM_AMT_SP" NUMBER(26,6), 
	"UOM_CONV_FCTR" NUMBER(26,6) DEFAULT 1, 
	"ITM_SR_NO" NUMBER(10,0) DEFAULT 1
   ) ;
  GRANT FLASHBACK ON "SLS"."SLS$OPP$ITM" TO PUBLIC;
  GRANT DEBUG ON "SLS"."SLS$OPP$ITM" TO PUBLIC;
  GRANT QUERY REWRITE ON "SLS"."SLS$OPP$ITM" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$OPP$ITM" TO PUBLIC;
  GRANT REFERENCES ON "SLS"."SLS$OPP$ITM" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$OPP$ITM" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$OPP$ITM" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$OPP$ITM" TO PUBLIC;
  GRANT INDEX ON "SLS"."SLS$OPP$ITM" TO PUBLIC;
  GRANT DELETE ON "SLS"."SLS$OPP$ITM" TO PUBLIC;
  GRANT ALTER ON "SLS"."SLS$OPP$ITM" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$OPP$ITM" TO "APP";
  GRANT REFERENCES ON "SLS"."SLS$OPP$ITM" TO "MNF" WITH GRANT OPTION;
  GRANT UPDATE ON "SLS"."SLS$OPP$ITM" TO "MNF" WITH GRANT OPTION;
  GRANT SELECT ON "SLS"."SLS$OPP$ITM" TO "MNF" WITH GRANT OPTION;
  GRANT INSERT ON "SLS"."SLS$OPP$ITM" TO "MNF" WITH GRANT OPTION;
  GRANT INDEX ON "SLS"."SLS$OPP$ITM" TO "MNF" WITH GRANT OPTION;
  GRANT DELETE ON "SLS"."SLS$OPP$ITM" TO "MNF" WITH GRANT OPTION;
  GRANT ALTER ON "SLS"."SLS$OPP$ITM" TO "MNF" WITH GRANT OPTION;
