--------------------------------------------------------
--  DDL for Table SLS$WMS$PUT$ITEM
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$WMS$PUT$ITEM" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(4 BYTE), 
	"HO_ORG_ID" VARCHAR2(4 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"LR_DOC_ID" VARCHAR2(40 BYTE), 
	"ITM_ID" VARCHAR2(50 BYTE), 
	"ITM_QTY" NUMBER(26,6), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"ITM_QTY_BS" NUMBER(26,6), 
	"UOM_CONV_FCTR" NUMBER(26,6), 
	"ITM_UOM" VARCHAR2(20 BYTE), 
	"ITM_RATE" NUMBER(26,6) DEFAULT 1, 
	"ITM_UOM_BS" VARCHAR2(20 BYTE), 
	"ITM_WT" NUMBER(26,6), 
	"EO_ID" NUMBER(5,0), 
	"DEPARTURE_PNT" VARCHAR2(20 BYTE), 
	"DOC_ID_SRC" VARCHAR2(40 BYTE), 
	"ARRIVAL_PNT" VARCHAR2(20 BYTE), 
	"ITM_CONV_WT" NUMBER(26,6), 
	"SCHDL_NO" VARCHAR2(50 BYTE), 
	"DLV_DT" DATE, 
	"WH_ID" VARCHAR2(10 BYTE), 
	"VERIFIED_QTY" NUMBER(26,6), 
	"VERIFIED_STATUS" CHAR(1 BYTE) DEFAULT 'N', 
	"ITM_COLOR" VARCHAR2(50 BYTE), 
	"SRC_ITM_QTY" NUMBER(26,6), 
	"GRP_ID" VARCHAR2(20 BYTE)
   ) ;
  GRANT INSERT ON "SLS"."SLS$WMS$PUT$ITEM" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$WMS$PUT$ITEM" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$WMS$PUT$ITEM" TO PUBLIC;
