--------------------------------------------------------
--  DDL for Table SLS$TRNP$VHCL$PRF
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$TRNP$VHCL$PRF" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"VHCL_ITM_ID" VARCHAR2(50 BYTE), 
	"VHCL_LEGACY_CODE" VARCHAR2(50 BYTE), 
	"VHCL_DESC" VARCHAR2(100 BYTE), 
	"VHCL_LONG_DESC" VARCHAR2(200 BYTE), 
	"VHCL_TECH_NM" VARCHAR2(200 BYTE), 
	"GRP_ID" VARCHAR2(20 BYTE), 
	"VHCL_TYP" NUMBER(5,0), 
	"UOM_BASIC" VARCHAR2(20 BYTE), 
	"PRICE_BASIC" NUMBER(26,6), 
	"OWNRSHP_TYP" VARCHAR2(1 BYTE), 
	"ACTV" VARCHAR2(1 BYTE), 
	"INACTV_RESN" VARCHAR2(200 BYTE), 
	"INACTV_DT" DATE, 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"VHCL_STATUS" NUMBER(5,0), 
	"TAX_CAT_ID" VARCHAR2(20 BYTE), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"PRMT_ADDS_LBL" VARCHAR2(20 BYTE), 
	"PRMT_RNW_FLG" VARCHAR2(1 BYTE)
   ) ;
  GRANT DEBUG ON "SLS"."SLS$TRNP$VHCL$PRF" TO PUBLIC;
  GRANT DELETE ON "SLS"."SLS$TRNP$VHCL$PRF" TO "FIN";
  GRANT INDEX ON "SLS"."SLS$TRNP$VHCL$PRF" TO "FIN";
  GRANT ALTER ON "SLS"."SLS$TRNP$VHCL$PRF" TO "FIN";
  GRANT INSERT ON "SLS"."SLS$TRNP$VHCL$PRF" TO "FIN";
  GRANT SELECT ON "SLS"."SLS$TRNP$VHCL$PRF" TO "FIN";
  GRANT UPDATE ON "SLS"."SLS$TRNP$VHCL$PRF" TO "FIN";
  GRANT REFERENCES ON "SLS"."SLS$TRNP$VHCL$PRF" TO "FIN";
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$TRNP$VHCL$PRF" TO "FIN";
  GRANT QUERY REWRITE ON "SLS"."SLS$TRNP$VHCL$PRF" TO "FIN";
  GRANT DEBUG ON "SLS"."SLS$TRNP$VHCL$PRF" TO "FIN";
  GRANT FLASHBACK ON "SLS"."SLS$TRNP$VHCL$PRF" TO "FIN";
  GRANT ALTER ON "SLS"."SLS$TRNP$VHCL$PRF" TO "APP";
  GRANT DELETE ON "SLS"."SLS$TRNP$VHCL$PRF" TO "APP";
  GRANT INDEX ON "SLS"."SLS$TRNP$VHCL$PRF" TO "APP";
  GRANT INSERT ON "SLS"."SLS$TRNP$VHCL$PRF" TO "APP";
  GRANT SELECT ON "SLS"."SLS$TRNP$VHCL$PRF" TO "APP";
  GRANT UPDATE ON "SLS"."SLS$TRNP$VHCL$PRF" TO "APP";
  GRANT REFERENCES ON "SLS"."SLS$TRNP$VHCL$PRF" TO "APP";
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$TRNP$VHCL$PRF" TO "APP";
  GRANT QUERY REWRITE ON "SLS"."SLS$TRNP$VHCL$PRF" TO "APP";
  GRANT DEBUG ON "SLS"."SLS$TRNP$VHCL$PRF" TO "APP";
  GRANT FLASHBACK ON "SLS"."SLS$TRNP$VHCL$PRF" TO "APP";
  GRANT ALTER ON "SLS"."SLS$TRNP$VHCL$PRF" TO "MNF";
  GRANT DELETE ON "SLS"."SLS$TRNP$VHCL$PRF" TO "MNF";
  GRANT INDEX ON "SLS"."SLS$TRNP$VHCL$PRF" TO "MNF";
  GRANT INSERT ON "SLS"."SLS$TRNP$VHCL$PRF" TO "MNF";
  GRANT SELECT ON "SLS"."SLS$TRNP$VHCL$PRF" TO "MNF";
  GRANT UPDATE ON "SLS"."SLS$TRNP$VHCL$PRF" TO "MNF";
  GRANT REFERENCES ON "SLS"."SLS$TRNP$VHCL$PRF" TO "MNF";
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$TRNP$VHCL$PRF" TO "MNF";
  GRANT QUERY REWRITE ON "SLS"."SLS$TRNP$VHCL$PRF" TO "MNF";
  GRANT DEBUG ON "SLS"."SLS$TRNP$VHCL$PRF" TO "MNF";
  GRANT FLASHBACK ON "SLS"."SLS$TRNP$VHCL$PRF" TO "MNF";
  GRANT ALTER ON "SLS"."SLS$TRNP$VHCL$PRF" TO "MM";
  GRANT DELETE ON "SLS"."SLS$TRNP$VHCL$PRF" TO "MM";
  GRANT INDEX ON "SLS"."SLS$TRNP$VHCL$PRF" TO "MM";
  GRANT INSERT ON "SLS"."SLS$TRNP$VHCL$PRF" TO "MM";
  GRANT SELECT ON "SLS"."SLS$TRNP$VHCL$PRF" TO "MM";
  GRANT UPDATE ON "SLS"."SLS$TRNP$VHCL$PRF" TO "MM";
  GRANT REFERENCES ON "SLS"."SLS$TRNP$VHCL$PRF" TO "MM";
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$TRNP$VHCL$PRF" TO "MM";
  GRANT QUERY REWRITE ON "SLS"."SLS$TRNP$VHCL$PRF" TO "MM";
  GRANT DEBUG ON "SLS"."SLS$TRNP$VHCL$PRF" TO "MM";
  GRANT FLASHBACK ON "SLS"."SLS$TRNP$VHCL$PRF" TO "MM";
  GRANT INSERT ON "SLS"."SLS$TRNP$VHCL$PRF" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$TRNP$VHCL$PRF" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$TRNP$VHCL$PRF" TO PUBLIC;
