--------------------------------------------------------
--  DDL for Table SLS$INCT$EO$DTL$AMD
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$INCT$EO$DTL$AMD" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"FREQ_BASIS" NUMBER(20,0), 
	"EO_ID" NUMBER(20,0), 
	"INCT_AMT_SP" NUMBER(26,6), 
	"INCT_AMT_BS" NUMBER(26,6), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"AMD_DATE" DATE DEFAULT SYSDATE, 
	"AMD_NUM" NUMBER(26,0) DEFAULT 0, 
	"INCT_QTY_SP" NUMBER(26,6), 
	"INCT_QTY_BS" NUMBER(26,6)
   ) ;
  GRANT INSERT ON "SLS"."SLS$INCT$EO$DTL$AMD" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$INCT$EO$DTL$AMD" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$INCT$EO$DTL$AMD" TO PUBLIC;
