--------------------------------------------------------
--  DDL for Table SLS$TRNP$LR$DOC$SRC
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$TRNP$LR$DOC$SRC" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"EO_ID" NUMBER(20,0), 
	"DEPARTURE_PNT" VARCHAR2(20 BYTE), 
	"ARRIVAL_PNT" VARCHAR2(20 BYTE), 
	"DOC_ID_SRC" VARCHAR2(40 BYTE), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"SCHDL_NO" NUMBER DEFAULT 1, 
	"DLV_DT" DATE DEFAULT to_date(SYSDATE,'DD-MM-YY'), 
	"WH_ID" VARCHAR2(10 BYTE) DEFAULT '0', 
	"DOC_ID_VCH_REQ" VARCHAR2(40 BYTE), 
	"EXT_DOC_NO" VARCHAR2(40 BYTE), 
	"EO_TPT_NO" VARCHAR2(40 BYTE)
   ) ;
  GRANT DELETE ON "SLS"."SLS$TRNP$LR$DOC$SRC" TO "APP";
  GRANT INDEX ON "SLS"."SLS$TRNP$LR$DOC$SRC" TO "APP";
  GRANT DEBUG ON "SLS"."SLS$TRNP$LR$DOC$SRC" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$TRNP$LR$DOC$SRC" TO "APP";
  GRANT SELECT ON "SLS"."SLS$TRNP$LR$DOC$SRC" TO "APP";
  GRANT UPDATE ON "SLS"."SLS$TRNP$LR$DOC$SRC" TO "APP";
  GRANT REFERENCES ON "SLS"."SLS$TRNP$LR$DOC$SRC" TO "APP";
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$TRNP$LR$DOC$SRC" TO "APP";
  GRANT ALTER ON "SLS"."SLS$TRNP$LR$DOC$SRC" TO "APP";
  GRANT QUERY REWRITE ON "SLS"."SLS$TRNP$LR$DOC$SRC" TO "APP";
  GRANT DEBUG ON "SLS"."SLS$TRNP$LR$DOC$SRC" TO "APP";
  GRANT FLASHBACK ON "SLS"."SLS$TRNP$LR$DOC$SRC" TO "APP";
  GRANT SELECT ON "SLS"."SLS$TRNP$LR$DOC$SRC" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$TRNP$LR$DOC$SRC" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$TRNP$LR$DOC$SRC" TO PUBLIC;
  GRANT ALTER ON "SLS"."SLS$TRNP$LR$DOC$SRC" TO PUBLIC;
  GRANT DELETE ON "SLS"."SLS$TRNP$LR$DOC$SRC" TO PUBLIC;
  GRANT INDEX ON "SLS"."SLS$TRNP$LR$DOC$SRC" TO PUBLIC;
  GRANT REFERENCES ON "SLS"."SLS$TRNP$LR$DOC$SRC" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$TRNP$LR$DOC$SRC" TO PUBLIC;
  GRANT QUERY REWRITE ON "SLS"."SLS$TRNP$LR$DOC$SRC" TO PUBLIC;
  GRANT FLASHBACK ON "SLS"."SLS$TRNP$LR$DOC$SRC" TO PUBLIC;
