--------------------------------------------------------
--  DDL for Table SLS$POS$WF$TXN
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$POS$WF$TXN" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"WF_ID" VARCHAR2(40 BYTE), 
	"ITM_PRICE_CHK" VARCHAR2(1 BYTE), 
	"CRDT_LMT_CHK" VARCHAR2(1 BYTE), 
	"ORDUE_AMT_CHK" VARCHAR2(1 BYTE), 
	"DOC_ID" VARCHAR2(50 BYTE), 
	"ITM_PRC_APR_USR" NUMBER, 
	"CRDT_LMT_APR_USR" NUMBER, 
	"ORDU_AMT_APR_USR" NUMBER, 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE DEFAULT SYSDATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE
   ) ;
  GRANT UPDATE ON "SLS"."SLS$POS$WF$TXN" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$POS$WF$TXN" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$POS$WF$TXN" TO PUBLIC;
