--------------------------------------------------------
--  DDL for Table SLS$TRNP$GROUP$ROUTE
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$TRNP$GROUP$ROUTE" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"GROUP_ID" VARCHAR2(40 BYTE), 
	"GROUP_NM" VARCHAR2(100 BYTE), 
	"USR_ID_CREATE" NUMBER(5,0), 
	"USR_DT_CREATE" DATE, 
	"USR_ID_MOD" NUMBER(5,0), 
	"USR_DT_MOD" DATE, 
	"STATUS" NUMBER(5,0), 
	"REMARK" VARCHAR2(100 BYTE), 
	"ACT_FLG" VARCHAR2(1 BYTE) DEFAULT 'Y'
   ) ;
  GRANT UPDATE ON "SLS"."SLS$TRNP$GROUP$ROUTE" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$TRNP$GROUP$ROUTE" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$TRNP$GROUP$ROUTE" TO PUBLIC;
