--------------------------------------------------------
--  DDL for Table SLS$TRNP$LI$DTL
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$TRNP$LI$DTL" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"OL_ID" VARCHAR2(40 BYTE), 
	"ROUND_TRP_FLG" VARCHAR2(1 BYTE), 
	"TOT_KM" NUMBER(26,6), 
	"SL_NO" NUMBER(5,0), 
	"AMT_SP" NUMBER(26,6), 
	"AMT_BS" NUMBER(26,6), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"VHCL_ITM_ID" VARCHAR2(20 BYTE) DEFAULT NULL, 
	"VHCL_NO" VARCHAR2(50 BYTE) DEFAULT NULL
   ) ;

   COMMENT ON COLUMN "SLS"."SLS$TRNP$LI$DTL"."ROUND_TRP_FLG" IS 'Y for Yes, N for NO and R For Round Trip';
   COMMENT ON COLUMN "SLS"."SLS$TRNP$LI$DTL"."SL_NO" IS '1 For Actual Trip, 2 For Round Trip';
  GRANT SELECT ON "SLS"."SLS$TRNP$LI$DTL" TO "APP";
  GRANT INSERT ON "SLS"."SLS$TRNP$LI$DTL" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$TRNP$LI$DTL" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$TRNP$LI$DTL" TO PUBLIC;
