--------------------------------------------------------
--  DDL for Table SLS$QUOT$AMD
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$QUOT$AMD" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"DOC_DT" DATE, 
	"AMD_NO" VARCHAR2(40 BYTE), 
	"AMD_DT" DATE, 
	"EO_CATG" NUMBER(10,0), 
	"EO_ID" NUMBER(20,0), 
	"ENQ_ID" VARCHAR2(40 BYTE), 
	"QUOT_STAT" NUMBER(10,0), 
	"DISC_TYPE" VARCHAR2(1 BYTE), 
	"DISC_VAL" NUMBER(26,6), 
	"VALID_TO_DT" DATE, 
	"EXP_DEL_DT" DATE, 
	"QUOT_PRNT_FLG" VARCHAR2(1 BYTE) DEFAULT 'Y', 
	"QUOT_MAIL_FLG" VARCHAR2(1 BYTE) DEFAULT 'Y', 
	"TAX_RULE_FLG" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"QUOT_AMT_SP" NUMBER(26,6), 
	"QUOT_AMT_BS" NUMBER(26,6), 
	"PAY_MODE" NUMBER(20,0), 
	"CURR_ID_SP" NUMBER(10,0), 
	"CURR_CONV_FCTR" NUMBER(26,6), 
	"CURR_ID_BS" NUMBER(10,0), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"QUOT_ID" VARCHAR2(20 BYTE), 
	"TAX_AFTER_DISC_FLG" VARCHAR2(1 BYTE), 
	"QUOT_BASIS" VARCHAR2(1 BYTE), 
	"FY_ID" NUMBER(5,0), 
	"QUOT_MODE" NUMBER(10,0), 
	"ASSIGNED_TO" NUMBER(10,0)
   ) ;

   COMMENT ON COLUMN "SLS"."SLS$QUOT$AMD"."ASSIGNED_TO" IS 'TO SAVE SALES REPRESENTATIVE';
  GRANT FLASHBACK ON "SLS"."SLS$QUOT$AMD" TO PUBLIC;
  GRANT DEBUG ON "SLS"."SLS$QUOT$AMD" TO PUBLIC;
  GRANT QUERY REWRITE ON "SLS"."SLS$QUOT$AMD" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$QUOT$AMD" TO PUBLIC;
  GRANT REFERENCES ON "SLS"."SLS$QUOT$AMD" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$QUOT$AMD" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$QUOT$AMD" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$QUOT$AMD" TO PUBLIC;
  GRANT INDEX ON "SLS"."SLS$QUOT$AMD" TO PUBLIC;
  GRANT DELETE ON "SLS"."SLS$QUOT$AMD" TO PUBLIC;
  GRANT ALTER ON "SLS"."SLS$QUOT$AMD" TO PUBLIC;
