--------------------------------------------------------
--  DDL for Table SLS$SO$ITM$LOT$ATTR
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$SO$ITM$LOT$ATTR" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"ITM_ID" VARCHAR2(50 BYTE), 
	"ITM_SR_NO" NUMBER(10,0), 
	"SR_NO" NUMBER(10,0), 
	"GSM" NUMBER(26,6), 
	"WIDTH" NUMBER(26,6), 
	"COLOR" NUMBER(10,0), 
	"ITM_QTY" NUMBER(26,6), 
	"COLOR_NM" VARCHAR2(100 BYTE), 
	"NO_OF_ROLL" NUMBER(26,6), 
	"LENGTH_VAL" NUMBER(26,6), 
	"PART_NO" VARCHAR2(100 BYTE), 
	"ITM_TYP" VARCHAR2(50 BYTE), 
	"ITM_SIZE" VARCHAR2(20 BYTE), 
	"ITM_PRICE" NUMBER(26,6), 
	"NO_OF_CUTS" NUMBER(26,6), 
	"CUST_SPEC_LENGTH" NUMBER(26,6), 
	"TOTAL_RMTS" NUMBER(26,6), 
	"LENGTH_IN_INCH" NUMBER(26,6), 
	"TOT_SQMTR" NUMBER(26,6), 
	"PART_QTY" NUMBER(26,6), 
	"TOT_WIDTH_EACH_LIN" NUMBER(26,6), 
	"SQMT_EACH_LINE" NUMBER(26,6), 
	"RMTS_EACH_LINE" NUMBER(26,6), 
	"ROLL_SHEET" NUMBER(6,0), 
	"ITEM_BRAND" VARCHAR2(50 BYTE), 
	"GAUGE" NUMBER(26,6), 
	"DENSITY" NUMBER(26,6)
   ) ;
  GRANT UPDATE ON "SLS"."SLS$SO$ITM$LOT$ATTR" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$SO$ITM$LOT$ATTR" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$SO$ITM$LOT$ATTR" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$SO$ITM$LOT$ATTR" TO "MNF";
