--------------------------------------------------------
--  DDL for Table SLS$TRNP$VHCL$PRF$COUNTY
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$TRNP$VHCL$PRF$COUNTY" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(1,0), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"ITM_SR_NO" VARCHAR2(20 BYTE), 
	"LOC_ID" VARCHAR2(20 BYTE), 
	"LICENSE_NO" VARCHAR2(40 BYTE), 
	"ISSUE_DT" DATE, 
	"EXPIRY_DT" DATE, 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE DEFAULT SYSDATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE
   ) ;
  GRANT INSERT ON "SLS"."SLS$TRNP$VHCL$PRF$COUNTY" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$TRNP$VHCL$PRF$COUNTY" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$TRNP$VHCL$PRF$COUNTY" TO PUBLIC;
