--------------------------------------------------------
--  DDL for Table SLS$TMPL$SO$ITM$SCH
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$TMPL$SO$ITM$SCH" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"SR_NO" NUMBER(5,0), 
	"SR_NO_DEST" NUMBER(5,0), 
	"SCHM_ID" NUMBER(5,0), 
	"ITM_ID" VARCHAR2(50 BYTE), 
	"ITM_FREE_QTY" NUMBER(26,6), 
	"ITM_PRICE" NUMBER(26,6), 
	"ITM_VAL" NUMBER(26,6), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE DEFAULT SYSDATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE
   ) ;
  GRANT FLASHBACK ON "SLS"."SLS$TMPL$SO$ITM$SCH" TO PUBLIC;
  GRANT DEBUG ON "SLS"."SLS$TMPL$SO$ITM$SCH" TO PUBLIC;
  GRANT QUERY REWRITE ON "SLS"."SLS$TMPL$SO$ITM$SCH" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$TMPL$SO$ITM$SCH" TO PUBLIC;
  GRANT REFERENCES ON "SLS"."SLS$TMPL$SO$ITM$SCH" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$TMPL$SO$ITM$SCH" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$TMPL$SO$ITM$SCH" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$TMPL$SO$ITM$SCH" TO PUBLIC;
  GRANT INDEX ON "SLS"."SLS$TMPL$SO$ITM$SCH" TO PUBLIC;
  GRANT DELETE ON "SLS"."SLS$TMPL$SO$ITM$SCH" TO PUBLIC;
  GRANT ALTER ON "SLS"."SLS$TMPL$SO$ITM$SCH" TO PUBLIC;
