--------------------------------------------------------
--  DDL for Table SLS$TRNP$ROUTE$PRF$DTL
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$TRNP$ROUTE$PRF$DTL" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"DEPARTURE_PNT" VARCHAR2(20 BYTE), 
	"ARRIVAL_PNT" VARCHAR2(20 BYTE), 
	"UOM_DIST" VARCHAR2(20 BYTE), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"UOM_FUEL" VARCHAR2(20 BYTE), 
	"DPRT_ALIAS" NUMBER(20,0), 
	"ARRVL_ALIAS" NUMBER(20,0), 
	"SL_NO" NUMBER(5,0), 
	"DIST" NUMBER(26,6), 
	"FUEL_QTY" NUMBER(26,6)
   ) ;
  GRANT FLASHBACK ON "SLS"."SLS$TRNP$ROUTE$PRF$DTL" TO "MM";
  GRANT FLASHBACK ON "SLS"."SLS$TRNP$ROUTE$PRF$DTL" TO "APP";
  GRANT DEBUG ON "SLS"."SLS$TRNP$ROUTE$PRF$DTL" TO "MM";
  GRANT DEBUG ON "SLS"."SLS$TRNP$ROUTE$PRF$DTL" TO "APP";
  GRANT INSERT ON "SLS"."SLS$TRNP$ROUTE$PRF$DTL" TO PUBLIC;
  GRANT QUERY REWRITE ON "SLS"."SLS$TRNP$ROUTE$PRF$DTL" TO "MM";
  GRANT QUERY REWRITE ON "SLS"."SLS$TRNP$ROUTE$PRF$DTL" TO "APP";
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$TRNP$ROUTE$PRF$DTL" TO "MM";
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$TRNP$ROUTE$PRF$DTL" TO "APP";
  GRANT REFERENCES ON "SLS"."SLS$TRNP$ROUTE$PRF$DTL" TO "MM";
  GRANT REFERENCES ON "SLS"."SLS$TRNP$ROUTE$PRF$DTL" TO "APP";
  GRANT ALTER ON "SLS"."SLS$TRNP$ROUTE$PRF$DTL" TO "APP";
  GRANT UPDATE ON "SLS"."SLS$TRNP$ROUTE$PRF$DTL" TO "MM";
  GRANT UPDATE ON "SLS"."SLS$TRNP$ROUTE$PRF$DTL" TO "APP";
  GRANT SELECT ON "SLS"."SLS$TRNP$ROUTE$PRF$DTL" TO "MM";
  GRANT SELECT ON "SLS"."SLS$TRNP$ROUTE$PRF$DTL" TO "APP";
  GRANT INSERT ON "SLS"."SLS$TRNP$ROUTE$PRF$DTL" TO "MM";
  GRANT INSERT ON "SLS"."SLS$TRNP$ROUTE$PRF$DTL" TO "APP";
  GRANT INDEX ON "SLS"."SLS$TRNP$ROUTE$PRF$DTL" TO "MM";
  GRANT INDEX ON "SLS"."SLS$TRNP$ROUTE$PRF$DTL" TO "APP";
  GRANT DELETE ON "SLS"."SLS$TRNP$ROUTE$PRF$DTL" TO "MM";
  GRANT DELETE ON "SLS"."SLS$TRNP$ROUTE$PRF$DTL" TO "APP";
  GRANT ALTER ON "SLS"."SLS$TRNP$ROUTE$PRF$DTL" TO "MM";
  GRANT DEBUG ON "SLS"."SLS$TRNP$ROUTE$PRF$DTL" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$TRNP$ROUTE$PRF$DTL" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$TRNP$ROUTE$PRF$DTL" TO PUBLIC;
