--------------------------------------------------------
--  DDL for Table SLS$TRNP$LI
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$TRNP$LI" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"LI_ID" VARCHAR2(20 BYTE), 
	"LI_DT" DATE, 
	"EO_ID" VARCHAR2(40 BYTE), 
	"TRNSP_ID" NUMBER(20,0), 
	"CURR_ID_SP" NUMBER(20,0), 
	"CURR_CONV_FCTR" NUMBER(26,6), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"LI_STATUS" NUMBER(5,0), 
	"TOT_AMT_SP" NUMBER(26,6), 
	"TOT_AMT_BS" NUMBER(26,6), 
	"COA_ID" NUMBER(10,0), 
	"LI_TYP" VARCHAR2(1 BYTE), 
	"LI_BASIS" NUMBER(5,0), 
	"FY_ID" NUMBER(10,0)
   ) ;

   COMMENT ON COLUMN "SLS"."SLS$TRNP$LI"."LI_TYP" IS 'I - Inhouse, T-Transporter';
  GRANT UPDATE ON "SLS"."SLS$TRNP$LI" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$TRNP$LI" TO PUBLIC;
  GRANT ALTER ON "SLS"."SLS$TRNP$LI" TO "APP";
  GRANT DEBUG ON "SLS"."SLS$TRNP$LI" TO "APP";
  GRANT DELETE ON "SLS"."SLS$TRNP$LI" TO "APP";
  GRANT FLASHBACK ON "SLS"."SLS$TRNP$LI" TO "APP";
  GRANT INDEX ON "SLS"."SLS$TRNP$LI" TO "APP";
  GRANT INSERT ON "SLS"."SLS$TRNP$LI" TO "APP";
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$TRNP$LI" TO "APP";
  GRANT QUERY REWRITE ON "SLS"."SLS$TRNP$LI" TO "APP";
  GRANT REFERENCES ON "SLS"."SLS$TRNP$LI" TO "APP";
  GRANT SELECT ON "SLS"."SLS$TRNP$LI" TO "APP";
  GRANT UPDATE ON "SLS"."SLS$TRNP$LI" TO "APP";
  GRANT INSERT ON "SLS"."SLS$TRNP$LI" TO PUBLIC;
