--------------------------------------------------------
--  DDL for Table SLS$RMA
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$RMA" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"DOC_DT" DATE DEFAULT (SYSDATE), 
	"EO_ID" NUMBER(20,0), 
	"CURR_ID_SP" NUMBER(10,0), 
	"CURR_CONV_FCTR" NUMBER(26,6), 
	"RMA_TYP_ID" NUMBER(10,0), 
	"REASON" VARCHAR2(100 BYTE), 
	"REMARKS" VARCHAR2(250 BYTE), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"CURR_ID_BS" NUMBER(10,0), 
	"GATEPASS_DOC_ID" VARCHAR2(40 BYTE), 
	"GATEPASS_DOC_DT" DATE, 
	"RMA_ID" VARCHAR2(20 BYTE), 
	"GE_DOC_ID" VARCHAR2(40 BYTE), 
	"GE_DOC_DT" DATE, 
	"COA_ID" NUMBER(10,0), 
	"WH_ID" VARCHAR2(20 BYTE) DEFAULT 0, 
	"FY_ID" NUMBER(5,0), 
	"RMA_MODE" NUMBER(10,0), 
	"COGS_VOU_ID" VARCHAR2(40 BYTE), 
	"CN_VOU_ID" VARCHAR2(40 BYTE), 
	"DISC_REVS_FLG" VARCHAR2(1 BYTE) DEFAULT 'Y', 
	"PRJ_ID" VARCHAR2(40 BYTE) DEFAULT 'PROJ0000', 
	"DEST_WH_ID" VARCHAR2(20 BYTE), 
	"SVC_CALL_ID" VARCHAR2(40 BYTE), 
	"RMA_STAT" NUMBER(10,0), 
	"ISSU_COGS_VOU_ID" VARCHAR2(40 BYTE), 
	"EXT_DOC_NO" VARCHAR2(100 BYTE), 
	"EXT_DOC_DT" DATE, 
	"EMP_DESG" VARCHAR2(20 BYTE), 
	"EMP_ID" NUMBER(5,0), 
	"DEDUCTION_VAL" NUMBER(26,6), 
	"DEDUCTION_TYPE" VARCHAR2(1 BYTE), 
	"PARTIAL_PAY_FLG" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"URA_ANTIFAKECODE" VARCHAR2(100 BYTE), 
	"URA_INV_ID" VARCHAR2(100 BYTE), 
	"URA_INV_NO" VARCHAR2(100 BYTE), 
	"URA_ISSUED_DT" DATE, 
	"URA_ISSUED_PDF_DT" DATE, 
	"URA_QR_CODE" VARCHAR2(100 BYTE), 
	"URA_REF_NO" VARCHAR2(100 BYTE), 
	"URA_STAT" VARCHAR2(100 BYTE)
   ) ;

   COMMENT ON COLUMN "SLS"."SLS$RMA"."DEST_WH_ID" IS 'To store the value of the destination Warehouse';
  GRANT INDEX ON "SLS"."SLS$RMA" TO "APP";
  GRANT SELECT ON "SLS"."SLS$RMA" TO "MNF" WITH GRANT OPTION;
  GRANT DEBUG ON "SLS"."SLS$RMA" TO "APP";
  GRANT UPDATE ON "SLS"."SLS$RMA" TO "MNF" WITH GRANT OPTION;
  GRANT SELECT ON "SLS"."SLS$RMA" TO "APP";
  GRANT UPDATE ON "SLS"."SLS$RMA" TO "APP";
  GRANT QUERY REWRITE ON "SLS"."SLS$RMA" TO "MNF" WITH GRANT OPTION;
  GRANT REFERENCES ON "SLS"."SLS$RMA" TO "APP";
  GRANT REFERENCES ON "SLS"."SLS$RMA" TO "MNF" WITH GRANT OPTION;
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$RMA" TO "MNF" WITH GRANT OPTION;
  GRANT ALTER ON "SLS"."SLS$RMA" TO "APP";
  GRANT DELETE ON "SLS"."SLS$RMA" TO "APP";
  GRANT FLASHBACK ON "SLS"."SLS$RMA" TO "APP";
  GRANT INDEX ON "SLS"."SLS$RMA" TO "MNF" WITH GRANT OPTION;
  GRANT ALTER ON "SLS"."SLS$RMA" TO "MNF" WITH GRANT OPTION;
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$RMA" TO "APP";
  GRANT DELETE ON "SLS"."SLS$RMA" TO "MNF" WITH GRANT OPTION;
  GRANT INSERT ON "SLS"."SLS$RMA" TO "APP";
  GRANT QUERY REWRITE ON "SLS"."SLS$RMA" TO "APP";
  GRANT INSERT ON "SLS"."SLS$RMA" TO "MNF" WITH GRANT OPTION;
  GRANT DEBUG ON "SLS"."SLS$RMA" TO "MNF" WITH GRANT OPTION;
  GRANT FLASHBACK ON "SLS"."SLS$RMA" TO "MNF" WITH GRANT OPTION;
  GRANT DEBUG ON "SLS"."SLS$RMA" TO PUBLIC;
  GRANT QUERY REWRITE ON "SLS"."SLS$RMA" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$RMA" TO PUBLIC;
  GRANT REFERENCES ON "SLS"."SLS$RMA" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$RMA" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$RMA" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$RMA" TO PUBLIC;
  GRANT INDEX ON "SLS"."SLS$RMA" TO PUBLIC;
  GRANT DELETE ON "SLS"."SLS$RMA" TO PUBLIC;
  GRANT ALTER ON "SLS"."SLS$RMA" TO PUBLIC;
  GRANT ALTER ON "SLS"."SLS$RMA" TO "MM" WITH GRANT OPTION;
  GRANT DEBUG ON "SLS"."SLS$RMA" TO "MM" WITH GRANT OPTION;
  GRANT DELETE ON "SLS"."SLS$RMA" TO "MM" WITH GRANT OPTION;
  GRANT FLASHBACK ON "SLS"."SLS$RMA" TO "MM" WITH GRANT OPTION;
  GRANT INDEX ON "SLS"."SLS$RMA" TO "MM" WITH GRANT OPTION;
  GRANT INSERT ON "SLS"."SLS$RMA" TO "MM" WITH GRANT OPTION;
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$RMA" TO "MM" WITH GRANT OPTION;
  GRANT QUERY REWRITE ON "SLS"."SLS$RMA" TO "MM" WITH GRANT OPTION;
  GRANT REFERENCES ON "SLS"."SLS$RMA" TO "MM" WITH GRANT OPTION;
  GRANT SELECT ON "SLS"."SLS$RMA" TO "MM" WITH GRANT OPTION;
  GRANT UPDATE ON "SLS"."SLS$RMA" TO "MM" WITH GRANT OPTION;
  GRANT FLASHBACK ON "SLS"."SLS$RMA" TO PUBLIC;
