--------------------------------------------------------
--  DDL for Table SLS$TRNP$LR$PROD$DTL
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$TRNP$LR$PROD$DTL" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"DEPARTURE_PNT" VARCHAR2(20 BYTE), 
	"ARRIVAL_PNT" VARCHAR2(20 BYTE), 
	"ITM_ID" VARCHAR2(50 BYTE), 
	"ITM_WT" NUMBER, 
	"ITM_WT_UOM" VARCHAR2(20 BYTE), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"EO_ID" NUMBER(20,0), 
	"DOC_ID_SRC" VARCHAR2(40 BYTE), 
	"ITM_QTY" NUMBER(26,6), 
	"QTY_UOM" VARCHAR2(20 BYTE), 
	"SCHDL_NO" NUMBER DEFAULT 1, 
	"DLV_DT" DATE DEFAULT to_date(SYSDATE,'DD-MM-YY'), 
	"WH_ID" VARCHAR2(10 BYTE) DEFAULT '0', 
	"PEND_QTY" NUMBER(26,6) DEFAULT 0, 
	"TEMP_SCHDL_QTY" NUMBER(26,6) DEFAULT 0, 
	"ITM_RATE" NUMBER(26,6) DEFAULT 0, 
	"OLD_ITM_QTY" NUMBER(26,6), 
	"ITM_SR_NO" NUMBER(5,0) DEFAULT 1
   ) ;
  GRANT UPDATE ON "SLS"."SLS$TRNP$LR$PROD$DTL" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$TRNP$LR$PROD$DTL" TO PUBLIC;
  GRANT DEBUG ON "SLS"."SLS$TRNP$LR$PROD$DTL" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$TRNP$LR$PROD$DTL" TO PUBLIC;
  GRANT FLASHBACK ON "SLS"."SLS$TRNP$LR$PROD$DTL" TO "APP";
  GRANT DEBUG ON "SLS"."SLS$TRNP$LR$PROD$DTL" TO "APP";
  GRANT QUERY REWRITE ON "SLS"."SLS$TRNP$LR$PROD$DTL" TO "APP";
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$TRNP$LR$PROD$DTL" TO "APP";
  GRANT DELETE ON "SLS"."SLS$TRNP$LR$PROD$DTL" TO "APP";
  GRANT REFERENCES ON "SLS"."SLS$TRNP$LR$PROD$DTL" TO "APP";
  GRANT UPDATE ON "SLS"."SLS$TRNP$LR$PROD$DTL" TO "APP";
  GRANT SELECT ON "SLS"."SLS$TRNP$LR$PROD$DTL" TO "APP";
  GRANT INSERT ON "SLS"."SLS$TRNP$LR$PROD$DTL" TO "APP";
  GRANT INDEX ON "SLS"."SLS$TRNP$LR$PROD$DTL" TO "APP";
  GRANT ALTER ON "SLS"."SLS$TRNP$LR$PROD$DTL" TO "APP";
