--------------------------------------------------------
--  DDL for Table SLS$TRNP$OL$RETURN$ORDER
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$TRNP$OL$RETURN$ORDER" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"SR_NO" NUMBER(5,0), 
	"VHCL_STATUS" VARCHAR2(1 BYTE) DEFAULT 'E', 
	"LO_DOC_ID" VARCHAR2(40 BYTE), 
	"REMARK" VARCHAR2(200 BYTE), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"END_READ" NUMBER(20,0), 
	"STRT_READ" NUMBER(20,0)
   ) ;
  GRANT UPDATE ON "SLS"."SLS$TRNP$OL$RETURN$ORDER" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$TRNP$OL$RETURN$ORDER" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$TRNP$OL$RETURN$ORDER" TO PUBLIC;
