--------------------------------------------------------
--  DDL for Table SLS$SUBC$INV$SRC
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$SUBC$INV$SRC" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"DOC_ID_SRC" VARCHAR2(40 BYTE), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE
   ) ;
  GRANT ALTER ON "SLS"."SLS$SUBC$INV$SRC" TO PUBLIC;
  GRANT DELETE ON "SLS"."SLS$SUBC$INV$SRC" TO PUBLIC;
  GRANT INDEX ON "SLS"."SLS$SUBC$INV$SRC" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$SUBC$INV$SRC" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$SUBC$INV$SRC" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$SUBC$INV$SRC" TO PUBLIC;
  GRANT REFERENCES ON "SLS"."SLS$SUBC$INV$SRC" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$SUBC$INV$SRC" TO PUBLIC;
  GRANT QUERY REWRITE ON "SLS"."SLS$SUBC$INV$SRC" TO PUBLIC;
  GRANT DEBUG ON "SLS"."SLS$SUBC$INV$SRC" TO PUBLIC;
  GRANT FLASHBACK ON "SLS"."SLS$SUBC$INV$SRC" TO PUBLIC;
