--------------------------------------------------------
--  DDL for Table SLS$PICK$ITM
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$PICK$ITM" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"SO_ID" VARCHAR2(40 BYTE), 
	"ITM_ID" VARCHAR2(50 BYTE), 
	"WH_ID" VARCHAR2(20 BYTE), 
	"SO_ITM_QTY" NUMBER(26,6), 
	"ITM_UOM" VARCHAR2(20 BYTE), 
	"PICK_QTY" NUMBER(26,6), 
	"BAL_QTY" NUMBER(26,6), 
	"ITM_PRICE" NUMBER(26,6), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE DEFAULT SYSDATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"SO_DT" DATE, 
	"DLV_DT" DATE, 
	"ITM_UOM_BS" VARCHAR2(20 BYTE), 
	"UOM_CONV_FCTR" NUMBER(26,6), 
	"ITM_QTY_BS" NUMBER(26,6), 
	"BC_NO" VARCHAR2(100 BYTE), 
	"ASBL_AMT_BS" NUMBER(26,6), 
	"ASBL_AMT_SP" NUMBER(26,6), 
	"PRJ_ID" VARCHAR2(40 BYTE) DEFAULT 'PROJ0000', 
	"QC_REQD_FLG" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"QC_OVERRIDE_FLG" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"ITM_SR_NO" NUMBER(10,0) DEFAULT NULL, 
	"CNT_QTY" NUMBER(26,6) DEFAULT 0, 
	"CHK_ASBL" VARCHAR2(1 BYTE) DEFAULT 'N'
   ) ;

   COMMENT ON COLUMN "SLS"."SLS$PICK$ITM"."BC_NO" IS 'BAR CODE NUMBER';
   COMMENT ON COLUMN "SLS"."SLS$PICK$ITM"."QC_REQD_FLG" IS 'Column to check if QC is required or not';
   COMMENT ON COLUMN "SLS"."SLS$PICK$ITM"."QC_OVERRIDE_FLG" IS 'Column to check if QC is being overridden or not';
  GRANT DEBUG ON "SLS"."SLS$PICK$ITM" TO "PMS";
  GRANT QUERY REWRITE ON "SLS"."SLS$PICK$ITM" TO "PMS";
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$PICK$ITM" TO "PMS";
  GRANT REFERENCES ON "SLS"."SLS$PICK$ITM" TO "PMS";
  GRANT UPDATE ON "SLS"."SLS$PICK$ITM" TO "PMS";
  GRANT SELECT ON "SLS"."SLS$PICK$ITM" TO "PMS";
  GRANT INSERT ON "SLS"."SLS$PICK$ITM" TO "PMS";
  GRANT INDEX ON "SLS"."SLS$PICK$ITM" TO "PMS";
  GRANT DELETE ON "SLS"."SLS$PICK$ITM" TO "PMS";
  GRANT ALTER ON "SLS"."SLS$PICK$ITM" TO "PMS";
  GRANT DELETE ON "SLS"."SLS$PICK$ITM" TO "MNF" WITH GRANT OPTION;
  GRANT DEBUG ON "SLS"."SLS$PICK$ITM" TO "MNF" WITH GRANT OPTION;
  GRANT ALTER ON "SLS"."SLS$PICK$ITM" TO "MNF" WITH GRANT OPTION;
  GRANT SELECT ON "SLS"."SLS$PICK$ITM" TO "MM";
  GRANT REFERENCES ON "SLS"."SLS$PICK$ITM" TO "MM";
  GRANT FLASHBACK ON "SLS"."SLS$PICK$ITM" TO PUBLIC;
  GRANT DEBUG ON "SLS"."SLS$PICK$ITM" TO PUBLIC;
  GRANT QUERY REWRITE ON "SLS"."SLS$PICK$ITM" TO PUBLIC;
  GRANT ALTER ON "SLS"."SLS$PICK$ITM" TO "MM";
  GRANT UPDATE ON "SLS"."SLS$PICK$ITM" TO "MM";
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$PICK$ITM" TO PUBLIC;
  GRANT REFERENCES ON "SLS"."SLS$PICK$ITM" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$PICK$ITM" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$PICK$ITM" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$PICK$ITM" TO PUBLIC;
  GRANT INDEX ON "SLS"."SLS$PICK$ITM" TO PUBLIC;
  GRANT DELETE ON "SLS"."SLS$PICK$ITM" TO PUBLIC;
  GRANT ALTER ON "SLS"."SLS$PICK$ITM" TO PUBLIC;
  GRANT QUERY REWRITE ON "SLS"."SLS$PICK$ITM" TO "MM";
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$PICK$ITM" TO "MM";
  GRANT INSERT ON "SLS"."SLS$PICK$ITM" TO "MM";
  GRANT INDEX ON "SLS"."SLS$PICK$ITM" TO "MM";
  GRANT FLASHBACK ON "SLS"."SLS$PICK$ITM" TO "MM";
  GRANT DELETE ON "SLS"."SLS$PICK$ITM" TO "MM";
  GRANT DEBUG ON "SLS"."SLS$PICK$ITM" TO "MM";
  GRANT UPDATE ON "SLS"."SLS$PICK$ITM" TO "MNF" WITH GRANT OPTION;
  GRANT SELECT ON "SLS"."SLS$PICK$ITM" TO "MNF" WITH GRANT OPTION;
  GRANT REFERENCES ON "SLS"."SLS$PICK$ITM" TO "MNF" WITH GRANT OPTION;
  GRANT QUERY REWRITE ON "SLS"."SLS$PICK$ITM" TO "MNF" WITH GRANT OPTION;
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$PICK$ITM" TO "MNF" WITH GRANT OPTION;
  GRANT INSERT ON "SLS"."SLS$PICK$ITM" TO "MNF" WITH GRANT OPTION;
  GRANT INDEX ON "SLS"."SLS$PICK$ITM" TO "MNF" WITH GRANT OPTION;
  GRANT FLASHBACK ON "SLS"."SLS$PICK$ITM" TO "MNF" WITH GRANT OPTION;
  GRANT FLASHBACK ON "SLS"."SLS$PICK$ITM" TO "PMS";
