--------------------------------------------------------
--  DDL for Table SLS$SHIPMNT$ITM$LOT
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$SHIPMNT$ITM$LOT" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"WH_ID" VARCHAR2(20 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"DOC_DT" DATE, 
	"LOT_ID" VARCHAR2(20 BYTE), 
	"ITM_ID" VARCHAR2(50 BYTE), 
	"ITM_UOM" VARCHAR2(20 BYTE), 
	"SHIPMNT_QTY" NUMBER(26,6), 
	"SHIPMNT_QTY_BS" NUMBER(26,6), 
	"SO_ID" VARCHAR2(40 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"ITM_LOT_COST" NUMBER(26,6), 
	"PICK_ID" VARCHAR2(40 BYTE), 
	"PRJ_ID" VARCHAR2(40 BYTE) DEFAULT 'PROJ0000', 
	"ITM_SR_NO" NUMBER(10,0) DEFAULT 1, 
	"CNT_QTY" NUMBER(26,6) DEFAULT 0
   ) ;
  GRANT REFERENCES ON "SLS"."SLS$SHIPMNT$ITM$LOT" TO "MM";
  GRANT SELECT ON "SLS"."SLS$SHIPMNT$ITM$LOT" TO "MM";
  GRANT UPDATE ON "SLS"."SLS$SHIPMNT$ITM$LOT" TO "MM";
  GRANT DELETE ON "SLS"."SLS$SHIPMNT$ITM$LOT" TO PUBLIC;
  GRANT INDEX ON "SLS"."SLS$SHIPMNT$ITM$LOT" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$SHIPMNT$ITM$LOT" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$SHIPMNT$ITM$LOT" TO PUBLIC;
  GRANT ALTER ON "SLS"."SLS$SHIPMNT$ITM$LOT" TO "PMS";
  GRANT DELETE ON "SLS"."SLS$SHIPMNT$ITM$LOT" TO "PMS";
  GRANT INDEX ON "SLS"."SLS$SHIPMNT$ITM$LOT" TO "PMS";
  GRANT INSERT ON "SLS"."SLS$SHIPMNT$ITM$LOT" TO "PMS";
  GRANT SELECT ON "SLS"."SLS$SHIPMNT$ITM$LOT" TO "PMS";
  GRANT UPDATE ON "SLS"."SLS$SHIPMNT$ITM$LOT" TO "PMS";
  GRANT REFERENCES ON "SLS"."SLS$SHIPMNT$ITM$LOT" TO "PMS";
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$SHIPMNT$ITM$LOT" TO "PMS";
  GRANT QUERY REWRITE ON "SLS"."SLS$SHIPMNT$ITM$LOT" TO "PMS";
  GRANT DEBUG ON "SLS"."SLS$SHIPMNT$ITM$LOT" TO "PMS";
  GRANT FLASHBACK ON "SLS"."SLS$SHIPMNT$ITM$LOT" TO "PMS";
  GRANT INSERT ON "SLS"."SLS$SHIPMNT$ITM$LOT" TO "APP";
  GRANT SELECT ON "SLS"."SLS$SHIPMNT$ITM$LOT" TO "APP";
  GRANT DELETE ON "SLS"."SLS$SHIPMNT$ITM$LOT" TO "APP";
  GRANT UPDATE ON "SLS"."SLS$SHIPMNT$ITM$LOT" TO "APP";
  GRANT FLASHBACK ON "SLS"."SLS$SHIPMNT$ITM$LOT" TO "APP";
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$SHIPMNT$ITM$LOT" TO "APP";
  GRANT DEBUG ON "SLS"."SLS$SHIPMNT$ITM$LOT" TO "APP";
  GRANT REFERENCES ON "SLS"."SLS$SHIPMNT$ITM$LOT" TO "APP";
  GRANT QUERY REWRITE ON "SLS"."SLS$SHIPMNT$ITM$LOT" TO "APP";
  GRANT ALTER ON "SLS"."SLS$SHIPMNT$ITM$LOT" TO "APP";
  GRANT INDEX ON "SLS"."SLS$SHIPMNT$ITM$LOT" TO "APP";
  GRANT UPDATE ON "SLS"."SLS$SHIPMNT$ITM$LOT" TO PUBLIC;
  GRANT REFERENCES ON "SLS"."SLS$SHIPMNT$ITM$LOT" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$SHIPMNT$ITM$LOT" TO PUBLIC;
  GRANT QUERY REWRITE ON "SLS"."SLS$SHIPMNT$ITM$LOT" TO PUBLIC;
  GRANT FLASHBACK ON "SLS"."SLS$SHIPMNT$ITM$LOT" TO PUBLIC;
  GRANT DEBUG ON "SLS"."SLS$SHIPMNT$ITM$LOT" TO PUBLIC;
  GRANT ALTER ON "SLS"."SLS$SHIPMNT$ITM$LOT" TO PUBLIC;
  GRANT ALTER ON "SLS"."SLS$SHIPMNT$ITM$LOT" TO "MM";
  GRANT DEBUG ON "SLS"."SLS$SHIPMNT$ITM$LOT" TO "MM";
  GRANT DELETE ON "SLS"."SLS$SHIPMNT$ITM$LOT" TO "MM";
  GRANT FLASHBACK ON "SLS"."SLS$SHIPMNT$ITM$LOT" TO "MM";
  GRANT INDEX ON "SLS"."SLS$SHIPMNT$ITM$LOT" TO "MM";
  GRANT INSERT ON "SLS"."SLS$SHIPMNT$ITM$LOT" TO "MM";
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$SHIPMNT$ITM$LOT" TO "MM";
  GRANT QUERY REWRITE ON "SLS"."SLS$SHIPMNT$ITM$LOT" TO "MM";
