--------------------------------------------------------
--  DDL for Table SLS$CUS$PRC$LST$ITM$EO_HIST
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$CUS$PRC$LST$ITM$EO_HIST" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"CATG_ID" NUMBER(5,0), 
	"ITM_ID" VARCHAR2(40 BYTE), 
	"EO_ID" NUMBER(5,0), 
	"PACK_SIZE" NUMBER(5,0), 
	"ITM_UOM_BS" VARCHAR2(20 BYTE), 
	"ITM_UOM_SP" VARCHAR2(20 BYTE), 
	"ITM_PRICE" NUMBER(26,6), 
	"ITM_PRICE_OLD" NUMBER(26,6), 
	"EFFECTIVE_DT" TIMESTAMP (6), 
	"HIST_DT" TIMESTAMP (6), 
	"EXPRY_DT" TIMESTAMP (6), 
	"PRIC_LIST_TYPE" VARCHAR2(2 BYTE), 
	"USR_ID_CREATE" NUMBER(5,0)
   ) ;
