--------------------------------------------------------
--  DDL for Table SLS$TRNP$VHCL$SCHDL$DTL
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$TRNP$VHCL$SCHDL$DTL" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(4 BYTE), 
	"HO_ORG_ID" VARCHAR2(4 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"LR_DOC_ID" VARCHAR2(40 BYTE), 
	"LR_DT" TIMESTAMP (6), 
	"LR_STRT_DT" TIMESTAMP (6), 
	"LR_END_DT" TIMESTAMP (6), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE
   ) ;
  GRANT INSERT ON "SLS"."SLS$TRNP$VHCL$SCHDL$DTL" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$TRNP$VHCL$SCHDL$DTL" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$TRNP$VHCL$SCHDL$DTL" TO PUBLIC;
