--------------------------------------------------------
--  DDL for Table SLS$PRFM$INV$SRC
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$PRFM$INV$SRC" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"DOC_DT" DATE, 
	"SO_ID" VARCHAR2(40 BYTE), 
	"SO_DT" DATE, 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"SHIP_ADDS" VARCHAR2(20 BYTE), 
	"TAX_TYPE" NUMBER(10,0) DEFAULT 1154, 
	"BILL_ADDS" VARCHAR2(20 BYTE), 
	"PNT_OF_SPLY" VARCHAR2(20 BYTE), 
	"MILESTN_NM" VARCHAR2(100 BYTE), 
	"MILESTN_ID" VARCHAR2(30 BYTE)
   ) ;

   COMMENT ON COLUMN "SLS"."SLS$PRFM$INV$SRC"."MILESTN_NM" IS 'To Store Milestone Name to show on page in view mode.';
   COMMENT ON COLUMN "SLS"."SLS$PRFM$INV$SRC"."MILESTN_ID" IS 'To Store Milestone Id';
  GRANT INSERT ON "SLS"."SLS$PRFM$INV$SRC" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$PRFM$INV$SRC" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$PRFM$INV$SRC" TO PUBLIC;
