--------------------------------------------------------
--  DDL for Table SLS$DC
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$DC" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"DOC_DT" DATE, 
	"EO_ID" NUMBER(20,0), 
	"ASSIGNED_TO" NUMBER(10,0), 
	"DC_ID" VARCHAR2(20 BYTE), 
	"EO_ADDS" VARCHAR2(20 BYTE), 
	"FY_ID" NUMBER(5,0), 
	"DC_DESC" VARCHAR2(250 BYTE), 
	"CONTACT_NM" VARCHAR2(250 BYTE), 
	"CONTACT_TYPE" NUMBER(5,0), 
	"STAGE_ID" NUMBER(5,0), 
	"NEXT_ACTION" VARCHAR2(250 BYTE), 
	"NEXT_DATE" DATE, 
	"EXPCTD_AMT" NUMBER(26,6), 
	"EXPCTD_CLOSER_ON" DATE, 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"EO_PH_NO" VARCHAR2(20 BYTE), 
	"EO_EMAIL_ID" VARCHAR2(100 BYTE), 
	"DC_MODE" NUMBER(10,0), 
	"DESIG_NAME" VARCHAR2(50 BYTE), 
	"CATID" NUMBER(5,0), 
	"ALRT_GEN" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"MULTI_LANG_CHK" VARCHAR2(5 BYTE)
   ) ;
  GRANT INSERT ON "SLS"."SLS$DC" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$DC" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$DC" TO "APP";
  GRANT SELECT ON "SLS"."SLS$DC" TO PUBLIC;
