--------------------------------------------------------
--  DDL for Table SLS$BATCH$SO$CNSL$ITM
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$BATCH$SO$CNSL$ITM" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"SO_ID" VARCHAR2(40 BYTE), 
	"ITM_SR_NO" NUMBER(10,0) DEFAULT 1, 
	"ITM_ID" VARCHAR2(50 BYTE), 
	"DLV_DT" DATE, 
	"WH_ID" VARCHAR2(20 BYTE), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE DEFAULT SYSDATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"CNSL_RSN" VARCHAR2(100 BYTE)
   ) ;
  GRANT INSERT ON "SLS"."SLS$BATCH$SO$CNSL$ITM" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$BATCH$SO$CNSL$ITM" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$BATCH$SO$CNSL$ITM" TO PUBLIC;
