--------------------------------------------------------
--  DDL for Table SLS$TRNP$OUTSTN$FUEL$DTL
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$TRNP$OUTSTN$FUEL$DTL" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"EO_ID" NUMBER(5,0), 
	"INV_NO" VARCHAR2(20 BYTE), 
	"INV_DT" DATE, 
	"FUEL_QTY" NUMBER(26,6), 
	"UOM" VARCHAR2(20 BYTE), 
	"STRT_READ" NUMBER(20,0), 
	"END_READ" NUMBER(20,0), 
	"VEHICLE_NO" VARCHAR2(20 BYTE), 
	"CURR_ID_SP" NUMBER(20,0), 
	"CURR_CONV_FCTR" NUMBER(26,6), 
	"AMT_SP" NUMBER(26,6), 
	"AMT_BS" NUMBER(26,6), 
	"STATUS" NUMBER(5,0), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"FUEL_RATE" NUMBER(26,6), 
	"FUEL_TYPE" NUMBER(5,0), 
	"DRIVER_EO_ID" NUMBER(5,0), 
	"VHCL_ITM_ID" VARCHAR2(20 BYTE)
   ) ;
  GRANT INSERT ON "SLS"."SLS$TRNP$OUTSTN$FUEL$DTL" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$TRNP$OUTSTN$FUEL$DTL" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$TRNP$OUTSTN$FUEL$DTL" TO PUBLIC;
