--------------------------------------------------------
--  DDL for Table SLS$TRNP$RECONCILE$TR$LINES
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$TRNP$RECONCILE$TR$LINES" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"LR_DOC_ID" VARCHAR2(40 BYTE), 
	"TAX_RULE_ID" NUMBER(10,0), 
	"TAX_RULE_FLG" VARCHAR2(1 BYTE), 
	"TAX_TYPE" NUMBER(10,0), 
	"TAX_COA_ID" NUMBER(10,0), 
	"TAX_AMT_SP" NUMBER(26,6), 
	"TAX_AMT_BS" NUMBER(26,6), 
	"TAX_PER" NUMBER(26,6), 
	"TAX_RULE_SLNO" NUMBER(2,0), 
	"TAX_RULE_PRIORITY" NUMBER(2,0), 
	"TAX_CALC_AMT_SP" NUMBER(26,6), 
	"TAX_CALC_AMT_BS" NUMBER(26,6), 
	"EXMPT_PCT" NUMBER(5,2) DEFAULT 0, 
	"EXMPT_AMT" NUMBER(26,6) DEFAULT 0, 
	"TAXABLE_AMT_SP" NUMBER(26,6) DEFAULT 0, 
	"TAXABLE_AMT_BS" NUMBER(26,6) DEFAULT 0
   ) ;
  GRANT INSERT ON "SLS"."SLS$TRNP$RECONCILE$TR$LINES" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$TRNP$RECONCILE$TR$LINES" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$TRNP$RECONCILE$TR$LINES" TO PUBLIC;
