--------------------------------------------------------
--  DDL for Table SLS$SRVC$INV$DTL
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$SRVC$INV$DTL" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"DOC_DT" DATE, 
	"SO_ID" VARCHAR2(40 BYTE), 
	"SO_DT" DATE, 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"SO_AMT_SP" NUMBER(26,6), 
	"SO_AMT_BS" NUMBER(26,6)
   ) ;
  GRANT INSERT ON "SLS"."SLS$SRVC$INV$DTL" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$SRVC$INV$DTL" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$SRVC$INV$DTL" TO PUBLIC;
  GRANT ALTER ON "SLS"."SLS$SRVC$INV$DTL" TO PUBLIC;
  GRANT DELETE ON "SLS"."SLS$SRVC$INV$DTL" TO PUBLIC;
  GRANT INDEX ON "SLS"."SLS$SRVC$INV$DTL" TO PUBLIC;
  GRANT REFERENCES ON "SLS"."SLS$SRVC$INV$DTL" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$SRVC$INV$DTL" TO PUBLIC;
  GRANT QUERY REWRITE ON "SLS"."SLS$SRVC$INV$DTL" TO PUBLIC;
  GRANT DEBUG ON "SLS"."SLS$SRVC$INV$DTL" TO PUBLIC;
  GRANT FLASHBACK ON "SLS"."SLS$SRVC$INV$DTL" TO PUBLIC;
