--------------------------------------------------------
--  DDL for Table SLS$SHIPMNT$ITM$RCPT$CHAR
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$SHIPMNT$ITM$RCPT$CHAR" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"DOC_DT" DATE, 
	"ITM_ID" VARCHAR2(50 BYTE), 
	"SO_ID" VARCHAR2(40 BYTE), 
	"PICK_ID" VARCHAR2(40 BYTE), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"WATER" VARCHAR2(30 BYTE), 
	"TEMP1" VARCHAR2(30 BYTE), 
	"TEMP2" VARCHAR2(30 BYTE), 
	"DENSITY" VARCHAR2(30 BYTE), 
	"ROTARY_GAUGE" VARCHAR2(30 BYTE), 
	"SEALS" VARCHAR2(30 BYTE), 
	"ITM_SR_NO" NUMBER(10,0) DEFAULT 1
   ) ;
  GRANT INSERT ON "SLS"."SLS$SHIPMNT$ITM$RCPT$CHAR" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$SHIPMNT$ITM$RCPT$CHAR" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$SHIPMNT$ITM$RCPT$CHAR" TO PUBLIC;
