--------------------------------------------------------
--  DDL for Table SLS$COM$QUOT$SUPWISE$CALC
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$COM$QUOT$SUPWISE$CALC" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"AMT_SP" NUMBER(26,6), 
	"AMT_BS" NUMBER(26,6), 
	"SUPP_CURR_ID" NUMBER(10,0), 
	"CURR_RATE" NUMBER(26,6), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE DEFAULT sysdate, 
	"SUPP_EO_ID" NUMBER(10,0)
   ) ;
  GRANT INSERT ON "SLS"."SLS$COM$QUOT$SUPWISE$CALC" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$COM$QUOT$SUPWISE$CALC" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$COM$QUOT$SUPWISE$CALC" TO PUBLIC;
