--------------------------------------------------------
--  DDL for Table SLS$INV$EXP$CALC
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$INV$EXP$CALC" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"COA_ID" NUMBER(20,0), 
	"AMT_SP" NUMBER(26,6), 
	"AMT_BS" NUMBER(26,6), 
	"CURR_ID_SP" NUMBER(10,0), 
	"CURR_CONV_RATE" NUMBER(10,0), 
	"TAXABL_VAL" NUMBER(26,6), 
	"TAX_PER" NUMBER(10,4), 
	"TAX_RULE_ID" NUMBER(10,0), 
	"COA_NM" VARCHAR2(100 BYTE), 
	"SR_NO" NUMBER(10,0), 
	"TRAN_TYPE" VARCHAR2(2 BYTE), 
	"AMD_NO" VARCHAR2(40 BYTE), 
	"AMD_DT" DATE, 
	"CURR_ID_BS" NUMBER(10,0), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE
   ) ;

   COMMENT ON COLUMN "SLS"."SLS$INV$EXP$CALC"."AMT_SP" IS 'Specific Amount';
   COMMENT ON COLUMN "SLS"."SLS$INV$EXP$CALC"."AMT_BS" IS 'basic Amount';
   COMMENT ON COLUMN "SLS"."SLS$INV$EXP$CALC"."CURR_ID_SP" IS 'Sales currency unit';
   COMMENT ON COLUMN "SLS"."SLS$INV$EXP$CALC"."CURR_CONV_RATE" IS 'Currency Rate';
   COMMENT ON COLUMN "SLS"."SLS$INV$EXP$CALC"."TAXABL_VAL" IS 'Taxable Amount';
   COMMENT ON COLUMN "SLS"."SLS$INV$EXP$CALC"."TRAN_TYPE" IS 'for Dr. Cr.';
   COMMENT ON COLUMN "SLS"."SLS$INV$EXP$CALC"."CURR_ID_BS" IS 'Base Currency';
  GRANT UPDATE ON "SLS"."SLS$INV$EXP$CALC" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$INV$EXP$CALC" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$INV$EXP$CALC" TO PUBLIC;
