--------------------------------------------------------
--  DDL for Table SLS$TRNP$LR
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$TRNP$LR" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"LR_ID" VARCHAR2(20 BYTE), 
	"LR_DT" DATE, 
	"REQ_TYP" VARCHAR2(1 BYTE), 
	"TRNSP_ID" NUMBER(20,0), 
	"ROUTE_DOC_ID" VARCHAR2(40 BYTE), 
	"VEHICLE_TYP" NUMBER(20,0), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"MULTIPLE_CUST_FLG" VARCHAR2(1 BYTE), 
	"CURR_ID_SP" NUMBER(20,0), 
	"RATE_BASIS" VARCHAR2(1 BYTE), 
	"CURR_CONV_FCTR" NUMBER(26,6), 
	"LR_STATUS" NUMBER(5,0), 
	"LR_BASIS" NUMBER(5,0), 
	"ADHOC_FLG" VARCHAR2(2 BYTE), 
	"DOC_TYP_ID" NUMBER(20,0), 
	"FY_ID" NUMBER(10,0), 
	"DEPT_ID" VARCHAR2(20 BYTE), 
	"REMARKS" VARCHAR2(1000 BYTE), 
	"TO_BILL" NUMBER(20,0), 
	"VEHICLE_NO" VARCHAR2(1000 BYTE)
   ) ;

   COMMENT ON COLUMN "SLS"."SLS$TRNP$LR"."ADHOC_FLG" IS 'Use Loading Request as AdHoc (Custom) document.';
  GRANT FLASHBACK ON "SLS"."SLS$TRNP$LR" TO PUBLIC;
  GRANT QUERY REWRITE ON "SLS"."SLS$TRNP$LR" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$TRNP$LR" TO PUBLIC;
  GRANT REFERENCES ON "SLS"."SLS$TRNP$LR" TO PUBLIC;
  GRANT INDEX ON "SLS"."SLS$TRNP$LR" TO PUBLIC;
  GRANT DELETE ON "SLS"."SLS$TRNP$LR" TO PUBLIC;
  GRANT ALTER ON "SLS"."SLS$TRNP$LR" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$TRNP$LR" TO PUBLIC;
  GRANT DEBUG ON "SLS"."SLS$TRNP$LR" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$TRNP$LR" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$TRNP$LR" TO PUBLIC;
  GRANT ALTER ON "SLS"."SLS$TRNP$LR" TO "APP";
  GRANT DELETE ON "SLS"."SLS$TRNP$LR" TO "APP";
  GRANT INDEX ON "SLS"."SLS$TRNP$LR" TO "APP";
  GRANT INSERT ON "SLS"."SLS$TRNP$LR" TO "APP";
  GRANT SELECT ON "SLS"."SLS$TRNP$LR" TO "APP";
  GRANT UPDATE ON "SLS"."SLS$TRNP$LR" TO "APP";
  GRANT REFERENCES ON "SLS"."SLS$TRNP$LR" TO "APP";
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$TRNP$LR" TO "APP";
  GRANT QUERY REWRITE ON "SLS"."SLS$TRNP$LR" TO "APP";
  GRANT DEBUG ON "SLS"."SLS$TRNP$LR" TO "APP";
  GRANT FLASHBACK ON "SLS"."SLS$TRNP$LR" TO "APP";
