--------------------------------------------------------
--  DDL for Table SLS$USR$TICKER$MAP
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$USR$TICKER$MAP" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER, 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"USR_ID" VARCHAR2(2 BYTE), 
	"SEQ_NO" NUMBER, 
	"TICKER_ID" NUMBER
   ) ;
  GRANT DELETE ON "SLS"."SLS$USR$TICKER$MAP" TO PUBLIC;
  GRANT ALTER ON "SLS"."SLS$USR$TICKER$MAP" TO PUBLIC;
  GRANT FLASHBACK ON "SLS"."SLS$USR$TICKER$MAP" TO PUBLIC;
  GRANT DEBUG ON "SLS"."SLS$USR$TICKER$MAP" TO PUBLIC;
  GRANT QUERY REWRITE ON "SLS"."SLS$USR$TICKER$MAP" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$USR$TICKER$MAP" TO PUBLIC;
  GRANT REFERENCES ON "SLS"."SLS$USR$TICKER$MAP" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$USR$TICKER$MAP" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$USR$TICKER$MAP" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$USR$TICKER$MAP" TO PUBLIC;
  GRANT INDEX ON "SLS"."SLS$USR$TICKER$MAP" TO PUBLIC;
