--------------------------------------------------------
--  DDL for Table SLS$PICK$SR$NOTE
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$PICK$SR$NOTE" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"SO_ID" VARCHAR2(40 BYTE), 
	"ITM_ID" VARCHAR2(50 BYTE), 
	"WH_ID" VARCHAR2(20 BYTE), 
	"DLV_DT" DATE, 
	"ITM_UOM" VARCHAR2(20 BYTE), 
	"SRL_NO" NUMBER(10,0), 
	"SR_NO" VARCHAR2(100 BYTE), 
	"ITM_UOM_BS" VARCHAR2(20 BYTE), 
	"ITM_SR_NO" NUMBER(10,0) DEFAULT NULL
   ) ;
  GRANT INSERT ON "SLS"."SLS$PICK$SR$NOTE" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$PICK$SR$NOTE" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$PICK$SR$NOTE" TO PUBLIC;
