--------------------------------------------------------
--  DDL for Table SLS$TRNP$VHCL$SCHDL$RT$EO
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$TRNP$VHCL$SCHDL$RT$EO" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"DEPARTURE_PNT" VARCHAR2(20 BYTE), 
	"ARRIVAL_PNT" VARCHAR2(20 BYTE), 
	"EO_ID" NUMBER(20,0), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"LR_DOC_ID" VARCHAR2(40 BYTE)
   ) ;
  GRANT UPDATE ON "SLS"."SLS$TRNP$VHCL$SCHDL$RT$EO" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$TRNP$VHCL$SCHDL$RT$EO" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$TRNP$VHCL$SCHDL$RT$EO" TO PUBLIC;
