--------------------------------------------------------
--  DDL for Table SLS$EXP$INVC$TDS$LINES
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$EXP$INVC$TDS$LINES" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"DOC_ID_SRC" VARCHAR2(40 BYTE), 
	"ITM_ID" VARCHAR2(50 BYTE), 
	"DLV_SCHDL_NO" NUMBER(5,0), 
	"EXP_COA_ID" NUMBER(10,0), 
	"EXP_TYPE" NUMBER(5,0), 
	"TDS_RULE_ID" NUMBER(10,0), 
	"TDS_RULE_FLG" VARCHAR2(1 BYTE), 
	"TDS_TYPE" NUMBER(10,0), 
	"TDS_COA_ID" NUMBER(10,0), 
	"TDS_AMT_SP" NUMBER(26,6), 
	"TDS_AMT_BS" NUMBER(26,6), 
	"TDS_PER" NUMBER(26,6), 
	"TDS_RULE_SLNO" NUMBER(2,0), 
	"TDS_RULE_PRIORITY" NUMBER(2,0), 
	"TAX_CALC_AMT_SP" NUMBER(26,6), 
	"TAX_CALC_AMT_BS" NUMBER(26,6)
   ) ;
  GRANT UPDATE ON "SLS"."SLS$EXP$INVC$TDS$LINES" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$EXP$INVC$TDS$LINES" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$EXP$INVC$TDS$LINES" TO PUBLIC;
