--------------------------------------------------------
--  DDL for Table SLS$SO$POS$TRNSPRT$DETAILS
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$SO$POS$TRNSPRT$DETAILS" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"TRNSPRT_NAME" VARCHAR2(250 BYTE), 
	"TOT_WEIGHT" NUMBER(26,0), 
	"TRNSPRT_DT" TIMESTAMP (6), 
	"TRNSPRT_ID" VARCHAR2(40 BYTE), 
	"PHONE_NO" VARCHAR2(40 BYTE), 
	"VEHICLE_NO" VARCHAR2(40 BYTE), 
	"DEST_IN_KM" NUMBER, 
	"DRIVER_NAME" VARCHAR2(40 BYTE)
   ) ;
  GRANT UPDATE ON "SLS"."SLS$SO$POS$TRNSPRT$DETAILS" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$SO$POS$TRNSPRT$DETAILS" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$SO$POS$TRNSPRT$DETAILS" TO PUBLIC;
