--------------------------------------------------------
--  DDL for Table SLS$EXPNS$INVC$COST$CENTER
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$EXPNS$INVC$COST$CENTER" 
   (	"CC_CLD_ID" VARCHAR2(4 BYTE), 
	"CC_SLOC_ID" NUMBER(5,0), 
	"CC_HO_ORG_ID" VARCHAR2(2 BYTE), 
	"CC_ORG_ID" VARCHAR2(2 BYTE), 
	"CC_TXN_ID" VARCHAR2(40 BYTE), 
	"CC_APPL_INST_ID" NUMBER(1,0), 
	"CC_DOC_SL_NO" NUMBER(5,0), 
	"CC_SL_NO" NUMBER(5,0), 
	"CC_SRC" VARCHAR2(1 BYTE), 
	"CC_CCID_LVL1" VARCHAR2(255 BYTE), 
	"CC_CCID_LVL2" VARCHAR2(255 BYTE), 
	"CC_CCID_LVL3" VARCHAR2(255 BYTE), 
	"CC_CCID_LVL4" VARCHAR2(255 BYTE), 
	"CC_CCID_LVL5" VARCHAR2(255 BYTE), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"CC_AMT_SP" NUMBER(26,6), 
	"CC_AMT_TYPE" VARCHAR2(1 BYTE), 
	"CC_ID" VARCHAR2(40 BYTE), 
	"CC_AMT_BS" NUMBER(26,6)
   ) ;
  GRANT ALTER ON "SLS"."SLS$EXPNS$INVC$COST$CENTER" TO PUBLIC;
  GRANT DELETE ON "SLS"."SLS$EXPNS$INVC$COST$CENTER" TO PUBLIC;
  GRANT INDEX ON "SLS"."SLS$EXPNS$INVC$COST$CENTER" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$EXPNS$INVC$COST$CENTER" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$EXPNS$INVC$COST$CENTER" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$EXPNS$INVC$COST$CENTER" TO PUBLIC;
  GRANT REFERENCES ON "SLS"."SLS$EXPNS$INVC$COST$CENTER" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$EXPNS$INVC$COST$CENTER" TO PUBLIC;
  GRANT QUERY REWRITE ON "SLS"."SLS$EXPNS$INVC$COST$CENTER" TO PUBLIC;
  GRANT DEBUG ON "SLS"."SLS$EXPNS$INVC$COST$CENTER" TO PUBLIC;
  GRANT FLASHBACK ON "SLS"."SLS$EXPNS$INVC$COST$CENTER" TO PUBLIC;
