--------------------------------------------------------
--  DDL for Table SLS$SEI$EO
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$SEI$EO" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"EO_ID" NUMBER(20,0), 
	"COA_ID" NUMBER(20,0), 
	"ITM_TOT_SCHM_DISC_VAL" NUMBER(26,6), 
	"EO_TOT_DED_VAL" NUMBER(26,6), 
	"SEI_VOU_ID" VARCHAR2(40 BYTE), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE DEFAULT SYSDATE, 
	"TOT_EO_AMT_SP" NUMBER(26,6) DEFAULT 0, 
	"TOT_EO_AMT_BS" NUMBER(26,6) DEFAULT 0, 
	"TOT_SO_INV_QTY" NUMBER(26,6) DEFAULT 0
   ) ;
  GRANT UPDATE ON "SLS"."SLS$SEI$EO" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$SEI$EO" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$SEI$EO" TO PUBLIC;
