--------------------------------------------------------
--  DDL for Table SLS$OPP
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$OPP" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"DOC_DT" DATE, 
	"FY_ID" NUMBER(5,0), 
	"EO_ID" NUMBER(22,0), 
	"EO_CAT" NUMBER(10,0), 
	"REMARKS" VARCHAR2(1000 BYTE), 
	"SPC_INSTRUCTION" VARCHAR2(1000 BYTE), 
	"ENQ_MEDIA" VARCHAR2(1 BYTE), 
	"ASSIGNED_TO" NUMBER(20,0), 
	"STATUS" NUMBER(10,0), 
	"EXP_DEL_DT" DATE, 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"CURR_ID_SP" NUMBER(10,0), 
	"CURR_RATE" NUMBER(26,6), 
	"CURR_ID_BS" NUMBER(10,0), 
	"ENQ_DESC" VARCHAR2(1000 BYTE), 
	"DISP_DOC_ID" VARCHAR2(20 BYTE), 
	"TOT_AMT_BS" NUMBER(26,6), 
	"TOT_AMT_SP" NUMBER(26,6), 
	"LOST_RMK" VARCHAR2(1000 BYTE), 
	"ASSIGNED_TO_TYPE" NUMBER(5,0), 
	"OPP_MODE" NUMBER(10,0), 
	"OPP_SRC" VARCHAR2(20 BYTE), 
	"EO_RATING" NUMBER(26,6), 
	"LEAD_TYPE" NUMBER(5,0), 
	"LEAD_SUB_TYPE" VARCHAR2(20 BYTE), 
	"LEAD_VAL" NUMBER(26,6), 
	"LEAD_NM" VARCHAR2(100 BYTE), 
	"LEAD_PLC" VARCHAR2(100 BYTE), 
	"LEAD_DT" DATE, 
	"EO_PER_NM" VARCHAR2(50 BYTE), 
	"EO_PER_ADD" VARCHAR2(50 BYTE), 
	"EO_PER_EMAIL1" VARCHAR2(50 BYTE), 
	"EO_PER_EMAIL2" VARCHAR2(50 BYTE), 
	"EO_PHON_NO" VARCHAR2(50 BYTE), 
	"EO_MOB_NO" VARCHAR2(20 BYTE), 
	"DLV_TYPE" NUMBER(5,0), 
	"DLV_TYPE_DESC" VARCHAR2(50 BYTE), 
	"NO_OF_STRS" NUMBER(10,0), 
	"MRKTNG_CMPNY_NM" VARCHAR2(100 BYTE), 
	"SR_NO" NUMBER(4,0), 
	"PORT_ID" VARCHAR2(20 BYTE), 
	"DOC_ID_TXN" VARCHAR2(40 BYTE), 
	"SRC_DOC_ID" NUMBER(10,0), 
	"EST_TYPE" NUMBER(5,0)
   ) ;

   COMMENT ON COLUMN "SLS"."SLS$OPP"."LOST_RMK" IS 'REASON FOR LOST OPPORTUNITY';
  GRANT DEBUG ON "SLS"."SLS$OPP" TO "MNF";
  GRANT FLASHBACK ON "SLS"."SLS$OPP" TO "MNF";
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$OPP" TO "MNF";
  GRANT QUERY REWRITE ON "SLS"."SLS$OPP" TO "MNF";
  GRANT REFERENCES ON "SLS"."SLS$OPP" TO "MNF" WITH GRANT OPTION;
  GRANT UPDATE ON "SLS"."SLS$OPP" TO "MNF" WITH GRANT OPTION;
  GRANT SELECT ON "SLS"."SLS$OPP" TO "MNF" WITH GRANT OPTION;
  GRANT INSERT ON "SLS"."SLS$OPP" TO "MNF" WITH GRANT OPTION;
  GRANT INDEX ON "SLS"."SLS$OPP" TO "MNF" WITH GRANT OPTION;
  GRANT DELETE ON "SLS"."SLS$OPP" TO "MNF" WITH GRANT OPTION;
  GRANT ALTER ON "SLS"."SLS$OPP" TO "MNF" WITH GRANT OPTION;
  GRANT INSERT ON "SLS"."SLS$OPP" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$OPP" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$OPP" TO PUBLIC;
  GRANT REFERENCES ON "SLS"."SLS$OPP" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$OPP" TO PUBLIC;
  GRANT QUERY REWRITE ON "SLS"."SLS$OPP" TO PUBLIC;
  GRANT DEBUG ON "SLS"."SLS$OPP" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$OPP" TO "APP";
  GRANT FLASHBACK ON "SLS"."SLS$OPP" TO PUBLIC;
  GRANT ALTER ON "SLS"."SLS$OPP" TO PUBLIC;
  GRANT DELETE ON "SLS"."SLS$OPP" TO PUBLIC;
  GRANT INDEX ON "SLS"."SLS$OPP" TO PUBLIC;
