--------------------------------------------------------
--  DDL for Table SLS$TRNP$VHCL$PERMIT$DTL
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$TRNP$VHCL$PERMIT$DTL" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"VHCL_REG_NO" VARCHAR2(40 BYTE), 
	"SR_NO" NUMBER(5,0), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"TRNSP_ID" NUMBER(5,0), 
	"PERMIT_ISSU_DT" DATE, 
	"PERMIT_EXP_DT" DATE, 
	"PERMIT_LVL" VARCHAR2(50 BYTE), 
	"LOCATION_ID" VARCHAR2(20 BYTE)
   ) ;
  GRANT INSERT ON "SLS"."SLS$TRNP$VHCL$PERMIT$DTL" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$TRNP$VHCL$PERMIT$DTL" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$TRNP$VHCL$PERMIT$DTL" TO PUBLIC;
