--------------------------------------------------------
--  DDL for Table SLS$SO$TR$LINES$AMD
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$SO$TR$LINES$AMD" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"AMD_NO" VARCHAR2(40 BYTE), 
	"AMD_DT" DATE, 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"SR_NO" NUMBER(5,0), 
	"TAX_ID" NUMBER(10,0), 
	"TAX_COA_ID" NUMBER(10,0), 
	"TAX_RULE_ID" NUMBER(10,0), 
	"TAX_AMT_SP" NUMBER(26,6), 
	"TAX_AMT_BS" NUMBER(26,6), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE DEFAULT SYSDATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"ITM_ID" VARCHAR2(50 BYTE), 
	"TAXABLE_AMT_SP" NUMBER(26,6), 
	"TAXABLE_AMT_BS" NUMBER(26,6), 
	"TAXABLE_AMT_SP_E" NUMBER(26,6), 
	"TAXABLE_AMT_BS_E" NUMBER(26,6), 
	"TAX_TYPE_MAN" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"ITM_SR_NO" NUMBER(10,0) DEFAULT 1, 
	"ADV_TAX_AMT" NUMBER(26,6), 
	"BAL_TAX_AMT" NUMBER(26,6)
   ) ;

   COMMENT ON COLUMN "SLS"."SLS$SO$TR$LINES$AMD"."TAX_TYPE_MAN" IS 'to store is manual tax applicable on row';
  GRANT INSERT ON "SLS"."SLS$SO$TR$LINES$AMD" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$SO$TR$LINES$AMD" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$SO$TR$LINES$AMD" TO PUBLIC;
  GRANT REFERENCES ON "SLS"."SLS$SO$TR$LINES$AMD" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$SO$TR$LINES$AMD" TO PUBLIC;
  GRANT QUERY REWRITE ON "SLS"."SLS$SO$TR$LINES$AMD" TO PUBLIC;
  GRANT DEBUG ON "SLS"."SLS$SO$TR$LINES$AMD" TO PUBLIC;
  GRANT FLASHBACK ON "SLS"."SLS$SO$TR$LINES$AMD" TO PUBLIC;
  GRANT ALTER ON "SLS"."SLS$SO$TR$LINES$AMD" TO PUBLIC;
  GRANT DELETE ON "SLS"."SLS$SO$TR$LINES$AMD" TO PUBLIC;
  GRANT INDEX ON "SLS"."SLS$SO$TR$LINES$AMD" TO PUBLIC;
