--------------------------------------------------------
--  DDL for Table SLS$SUBC$BLK$INV
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$SUBC$BLK$INV" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"DISP_ID" VARCHAR2(20 BYTE), 
	"DOC_DT" DATE, 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"BLK_INV_STAT" NUMBER(10,0), 
	"REMARKS" VARCHAR2(1000 BYTE), 
	"START_DT" DATE, 
	"END_DT" DATE, 
	"EO_ID" NUMBER(5,0), 
	"SEQUENCE_NUM" NUMBER(5,0)
   ) ;
  GRANT INSERT ON "SLS"."SLS$SUBC$BLK$INV" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$SUBC$BLK$INV" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$SUBC$BLK$INV" TO PUBLIC;
