--------------------------------------------------------
--  DDL for Table SLS$SUBC$SO$PAYMNT$AMD
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$SUBC$SO$PAYMNT$AMD" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"AMD_NO" NUMBER(5,0), 
	"AMD_DT" DATE, 
	"ITM_ID" VARCHAR2(50 BYTE), 
	"ITM_SR_NO" NUMBER(10,0), 
	"FREQ_TYPE" NUMBER, 
	"SCHDL_DT" DATE, 
	"TOTAL_AMT" NUMBER, 
	"INV_FLG" VARCHAR2(1 BYTE), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"INV_DOC_TXN" VARCHAR2(50 BYTE), 
	"DISCNTNUE_FLG" VARCHAR2(1 BYTE), 
	"DISCNTNUE_DATE" DATE, 
	"BILL_STRT_DT" DATE, 
	"BILL_AMOUNT" NUMBER(26,6)
   ) ;
  GRANT INSERT ON "SLS"."SLS$SUBC$SO$PAYMNT$AMD" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$SUBC$SO$PAYMNT$AMD" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$SUBC$SO$PAYMNT$AMD" TO PUBLIC;
