--------------------------------------------------------
--  DDL for Table SLS$DOC$CONF$SRC
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$DOC$CONF$SRC" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"DOC_TYPE_SRC" NUMBER(5,0), 
	"DOC_ID_SRC" VARCHAR2(40 BYTE), 
	"DOC_DT_SRC" TIMESTAMP (8), 
	"DOC_FRZ" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"DOC_RCVD" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"DOC_RCVD_DT" DATE, 
	"E_WAY_BILL_NO" VARCHAR2(50 BYTE), 
	"ITEM_NAME" VARCHAR2(50 BYTE)
   ) ;
  GRANT SELECT ON "SLS"."SLS$DOC$CONF$SRC" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$DOC$CONF$SRC" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$DOC$CONF$SRC" TO PUBLIC;
