--------------------------------------------------------
--  DDL for Table SLS$PDR$ITM
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$PDR$ITM" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"DOC_ID_SRC" VARCHAR2(40 BYTE), 
	"SHIP_TXN_ID" VARCHAR2(40 BYTE), 
	"SO_TXN_ID" VARCHAR2(40 BYTE), 
	"ITM_ID" VARCHAR2(50 BYTE), 
	"ITM_RATE" NUMBER(26,6), 
	"ITM_UOM" VARCHAR2(20 BYTE), 
	"ITM_SHIP_QTY" NUMBER(26,6), 
	"ITM_AMT_BS" NUMBER(26,6), 
	"ITM_AMT_SP" NUMBER(26,6), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE DEFAULT SYSDATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"ITM_TOT_DISC_VAL" NUMBER(26,6), 
	"EO_ID" NUMBER(20,0) DEFAULT 0, 
	"ITM_SR_NO" NUMBER(10,0) DEFAULT 1
   ) ;
  GRANT INSERT ON "SLS"."SLS$PDR$ITM" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$PDR$ITM" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$PDR$ITM" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$PDR$ITM" TO "APP";
