--------------------------------------------------------
--  DDL for Table SLS$TMPL$SO$TNC
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$TMPL$SO$TNC" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"TNC_ID" NUMBER(10,0), 
	"PRIORITY" NUMBER(2,0), 
	"AMD_NO" NUMBER(2,0), 
	"AMD_DT" DATE, 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE DEFAULT SYSDATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE
   ) ;
  GRANT FLASHBACK ON "SLS"."SLS$TMPL$SO$TNC" TO PUBLIC;
  GRANT DEBUG ON "SLS"."SLS$TMPL$SO$TNC" TO PUBLIC;
  GRANT QUERY REWRITE ON "SLS"."SLS$TMPL$SO$TNC" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$TMPL$SO$TNC" TO PUBLIC;
  GRANT REFERENCES ON "SLS"."SLS$TMPL$SO$TNC" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$TMPL$SO$TNC" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$TMPL$SO$TNC" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$TMPL$SO$TNC" TO PUBLIC;
  GRANT INDEX ON "SLS"."SLS$TMPL$SO$TNC" TO PUBLIC;
  GRANT DELETE ON "SLS"."SLS$TMPL$SO$TNC" TO PUBLIC;
  GRANT ALTER ON "SLS"."SLS$TMPL$SO$TNC" TO PUBLIC;
