--------------------------------------------------------
--  DDL for Table SLS$COM$QUOT$OC$TMP
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$COM$QUOT$OC$TMP" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"COA_ID" NUMBER(20,0), 
	"OC_DESC" VARCHAR2(40 BYTE), 
	"CURR_ID" NUMBER(10,0), 
	"CURR_RATE" NUMBER(10,0), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"TRAN_TYPE" VARCHAR2(2 BYTE), 
	"OC_ID" VARCHAR2(20 BYTE), 
	"OC_CALCON" NUMBER(26,6), 
	"OC_CALC_TYPE" VARCHAR2(1 BYTE) DEFAULT 'A', 
	"OC_ADD_SUB" VARCHAR2(1 BYTE) DEFAULT 'A', 
	"OC_CALC_VAL" NUMBER(26,6), 
	"OC_SUMM" NUMBER(26,6), 
	"OC_SUMM_FLAG" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"AMT_SP" NUMBER(26,6) DEFAULT 0, 
	"AMT_BS" NUMBER(26,6) DEFAULT 0, 
	"TEMPLT_DESC" VARCHAR2(50 BYTE), 
	"OC_CALC_ON_SRC_ID" VARCHAR2(20 BYTE), 
	"SUP_PAID" VARCHAR2(1 BYTE), 
	"OC_SUMM_SR_NO" NUMBER(26,6), 
	"OC_SUMM_DESC" VARCHAR2(50 BYTE)
   ) ;

   COMMENT ON COLUMN "SLS"."SLS$COM$QUOT$OC$TMP"."OC_CALCON" IS 'Calculation on this value';
   COMMENT ON COLUMN "SLS"."SLS$COM$QUOT$OC$TMP"."OC_CALC_TYPE" IS 'Calculation based on percentage or amount';
   COMMENT ON COLUMN "SLS"."SLS$COM$QUOT$OC$TMP"."OC_ADD_SUB" IS 'addition on subtraction';
   COMMENT ON COLUMN "SLS"."SLS$COM$QUOT$OC$TMP"."OC_CALC_VAL" IS 'value to be calculate';
   COMMENT ON COLUMN "SLS"."SLS$COM$QUOT$OC$TMP"."OC_SUMM" IS 'Total summary value';
   COMMENT ON COLUMN "SLS"."SLS$COM$QUOT$OC$TMP"."OC_SUMM_FLAG" IS 'flag to check as summary';
   COMMENT ON COLUMN "SLS"."SLS$COM$QUOT$OC$TMP"."TEMPLT_DESC" IS 'Saved Template Discription, to identify and select';
   COMMENT ON COLUMN "SLS"."SLS$COM$QUOT$OC$TMP"."OC_CALC_ON_SRC_ID" IS 'Storing OC id, for selected summary, and for basic storing id - 1';
   COMMENT ON COLUMN "SLS"."SLS$COM$QUOT$OC$TMP"."SUP_PAID" IS 'To store is OC paid by supplier';
  GRANT UPDATE ON "SLS"."SLS$COM$QUOT$OC$TMP" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$COM$QUOT$OC$TMP" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$COM$QUOT$OC$TMP" TO PUBLIC;
