--------------------------------------------------------
--  DDL for Table SLS$SO$PMNT$SCHDL$AMD
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$SO$PMNT$SCHDL$AMD" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"AMD_NO" VARCHAR2(40 BYTE), 
	"AMD_DT" DATE, 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"PAY_DT" DATE, 
	"PAY_MODE" NUMBER(20,0), 
	"TOT_AMT" NUMBER(26,6), 
	"PAY_AMT" NUMBER(26,6), 
	"ADV_FLG" VARCHAR2(1 BYTE), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE DEFAULT SYSDATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE
   ) ;
  GRANT INSERT ON "SLS"."SLS$SO$PMNT$SCHDL$AMD" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$SO$PMNT$SCHDL$AMD" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$SO$PMNT$SCHDL$AMD" TO PUBLIC;
  GRANT REFERENCES ON "SLS"."SLS$SO$PMNT$SCHDL$AMD" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$SO$PMNT$SCHDL$AMD" TO PUBLIC;
  GRANT QUERY REWRITE ON "SLS"."SLS$SO$PMNT$SCHDL$AMD" TO PUBLIC;
  GRANT DEBUG ON "SLS"."SLS$SO$PMNT$SCHDL$AMD" TO PUBLIC;
  GRANT FLASHBACK ON "SLS"."SLS$SO$PMNT$SCHDL$AMD" TO PUBLIC;
  GRANT ALTER ON "SLS"."SLS$SO$PMNT$SCHDL$AMD" TO PUBLIC;
  GRANT DELETE ON "SLS"."SLS$SO$PMNT$SCHDL$AMD" TO PUBLIC;
  GRANT INDEX ON "SLS"."SLS$SO$PMNT$SCHDL$AMD" TO PUBLIC;
