--------------------------------------------------------
--  DDL for Table SLS$EO$PRICE$CORRUPT
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$EO$PRICE$CORRUPT" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"EO_ID" NUMBER(20,0), 
	"CATG_ID" NUMBER(10,0), 
	"EFFECTIVE_DT" TIMESTAMP (8), 
	"ITM_ID" VARCHAR2(50 BYTE), 
	"ITM_UOM" VARCHAR2(20 BYTE), 
	"MIN_PRICE" NUMBER(26,6), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(20,0), 
	"USR_ID_MOD_DT" DATE, 
	"BASE_PRICE" NUMBER(26,6), 
	"EXPIRY_DT" TIMESTAMP (8), 
	"ADD_ON" NUMBER(26,6), 
	"ADD_ON_ADD_SUB" VARCHAR2(1 BYTE) DEFAULT 'A', 
	"ADD_ON_TYP" VARCHAR2(1 BYTE) DEFAULT 'A', 
	"REASON" VARCHAR2(100 BYTE)
   ) ;
  GRANT UPDATE ON "SLS"."SLS$EO$PRICE$CORRUPT" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$EO$PRICE$CORRUPT" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$EO$PRICE$CORRUPT" TO PUBLIC;
