--------------------------------------------------------
--  DDL for Table SLS$TRNP$RECONCILE$ITM
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$TRNP$RECONCILE$ITM" 
   (	"CLD_ID" VARCHAR2(20 BYTE), 
	"SLOC_ID" NUMBER(4,0), 
	"ORG_ID" VARCHAR2(20 BYTE), 
	"HO_ORG_ID" VARCHAR2(20 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"LR_DOC_ID" VARCHAR2(40 BYTE), 
	"LR_DOC_DT" DATE, 
	"VHCL_NO" VARCHAR2(40 BYTE), 
	"DOC_TYPE_ID" NUMBER(5,0), 
	"CALC_FREIGHT_AMT" NUMBER(26,6), 
	"BILL_FREIGHT_AMT" NUMBER(26,6), 
	"CALC_TAX_AMT" NUMBER(26,6), 
	"BILL_TAX_AMT" NUMBER(26,6), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"CALC_TDS_AMT" NUMBER(26,6), 
	"BILL_TDS_AMT" NUMBER(26,6), 
	"CN_DN_VOU_ID" VARCHAR2(40 BYTE), 
	"GL_VOU_ID" VARCHAR2(40 BYTE)
   ) ;
  GRANT SELECT ON "SLS"."SLS$TRNP$RECONCILE$ITM" TO "FIN";
  GRANT UPDATE ON "SLS"."SLS$TRNP$RECONCILE$ITM" TO "FIN";
  GRANT ALTER ON "SLS"."SLS$TRNP$RECONCILE$ITM" TO PUBLIC;
  GRANT DELETE ON "SLS"."SLS$TRNP$RECONCILE$ITM" TO PUBLIC;
  GRANT INDEX ON "SLS"."SLS$TRNP$RECONCILE$ITM" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$TRNP$RECONCILE$ITM" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$TRNP$RECONCILE$ITM" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$TRNP$RECONCILE$ITM" TO PUBLIC;
  GRANT REFERENCES ON "SLS"."SLS$TRNP$RECONCILE$ITM" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$TRNP$RECONCILE$ITM" TO PUBLIC;
  GRANT QUERY REWRITE ON "SLS"."SLS$TRNP$RECONCILE$ITM" TO PUBLIC;
  GRANT DEBUG ON "SLS"."SLS$TRNP$RECONCILE$ITM" TO PUBLIC;
  GRANT FLASHBACK ON "SLS"."SLS$TRNP$RECONCILE$ITM" TO PUBLIC;
