--------------------------------------------------------
--  DDL for Table SLS$PDR$EO
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$PDR$EO" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"EO_ID" NUMBER(20,0), 
	"COA_ID" NUMBER(20,0), 
	"EO_CATG_ID" NUMBER(10,0), 
	"ITM_TOT_SCHM_DISC_VAL" NUMBER(26,6), 
	"EO_TOT_DED_VAL" NUMBER(26,6), 
	"PDR_VOU_ID" VARCHAR2(40 BYTE), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE DEFAULT SYSDATE, 
	"TOT_EO_AMT_SP" NUMBER(26,6) DEFAULT 0, 
	"TOT_EO_AMT_BS" NUMBER(26,6) DEFAULT 0, 
	"TOT_INV_QTY" NUMBER(26,6) DEFAULT 0, 
	"TOT_INV_AMT_SP" NUMBER(26,6) DEFAULT 0, 
	"TOT_INV_AMT_BS" NUMBER(26,6) DEFAULT 0
   ) ;

   COMMENT ON COLUMN "SLS"."SLS$PDR$EO"."TOT_INV_AMT_SP" IS 'Total Invoice Amount Specific';
   COMMENT ON COLUMN "SLS"."SLS$PDR$EO"."TOT_INV_AMT_BS" IS 'Total Invoice Amount Basic';
  GRANT INSERT ON "SLS"."SLS$PDR$EO" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$PDR$EO" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$PDR$EO" TO PUBLIC;
