--------------------------------------------------------
--  DDL for Table SLS$SS$ITM
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$SS$ITM" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"DOC_DT" DATE, 
	"CUST_NM" VARCHAR2(250 BYTE), 
	"ITM_ID" VARCHAR2(50 BYTE), 
	"ITM_PRICE" NUMBER(26,6), 
	"ITM_QTY" NUMBER(26,6), 
	"ITM_AMT_BS" NUMBER(26,6), 
	"ITM_AMT_SP" NUMBER(26,6), 
	"REMARKS" VARCHAR2(250 BYTE), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE DEFAULT SYSDATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"DOC_ID_SRC" VARCHAR2(40 BYTE), 
	"ITM_BAL_QTY" NUMBER(26,6) DEFAULT 0, 
	"ITM_SR_NO" NUMBER(10,0) DEFAULT 1, 
	"CNT_QTY" NUMBER(26,6) DEFAULT 0, 
	"UNREG_EO_ID" NUMBER(5,0)
   ) ;
  GRANT SELECT ON "SLS"."SLS$SS$ITM" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$SS$ITM" TO "APP";
  GRANT UPDATE ON "SLS"."SLS$SS$ITM" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$SS$ITM" TO PUBLIC;
