--------------------------------------------------------
--  DDL for Table SLS$DOC$CONF
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$DOC$CONF" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"DOC_DT" DATE, 
	"FY_ID" NUMBER(5,0), 
	"CONF_ID" VARCHAR2(20 BYTE), 
	"CONF_STAT" NUMBER(5,0), 
	"CONF_REV_NO" NUMBER(10,0), 
	"CONF_REV_DT" DATE, 
	"CONF_RMRK" VARCHAR2(250 BYTE), 
	"USR_ID_CREATE" NUMBER(10,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(10,0), 
	"USR_ID_MOD_DT" DATE, 
	"CONF_TYPE" NUMBER(5,0), 
	"EO_ID" NUMBER(20,0)
   ) ;
  GRANT INSERT ON "SLS"."SLS$DOC$CONF" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$DOC$CONF" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$DOC$CONF" TO PUBLIC;
