--------------------------------------------------------
--  DDL for Table SLS$SRVC$INV$TR$LINES
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$SRVC$INV$TR$LINES" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"SR_NO" NUMBER(5,0), 
	"ITM_ID" VARCHAR2(50 BYTE), 
	"SO_ID" VARCHAR2(40 BYTE), 
	"TAX_ID" NUMBER(10,0), 
	"TAX_COA_ID" NUMBER(10,0), 
	"TAX_RULE_ID" NUMBER(10,0), 
	"TAX_AMT_SP" NUMBER(26,6), 
	"TAX_AMT_BS" NUMBER(26,6), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"TAXABLE_AMT_SP" NUMBER(26,6) DEFAULT 0, 
	"TAXABLE_AMT_BS" NUMBER(26,6) DEFAULT 0, 
	"TAXABLE_AMT_SP_E" NUMBER(26,6) DEFAULT 0, 
	"TAXABLE_AMT_BS_E" NUMBER(26,6) DEFAULT 0, 
	"TAX_TYPE_MAN" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"TAX_AMT_RAW" VARCHAR2(20 BYTE), 
	"TAX_PER" NUMBER(6,0), 
	"TAX_RULE_PRIORITY" NUMBER(6,0), 
	"TAX_RULE_SLNO" NUMBER(6,0), 
	"EO_ID" NUMBER(6,0), 
	"ITM_UOM" VARCHAR2(20 BYTE), 
	"TAX_RULE_FLG" VARCHAR2(3 BYTE)
   ) ;
  GRANT ALTER ON "SLS"."SLS$SRVC$INV$TR$LINES" TO PUBLIC;
  GRANT DELETE ON "SLS"."SLS$SRVC$INV$TR$LINES" TO PUBLIC;
  GRANT INDEX ON "SLS"."SLS$SRVC$INV$TR$LINES" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$SRVC$INV$TR$LINES" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$SRVC$INV$TR$LINES" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$SRVC$INV$TR$LINES" TO PUBLIC;
  GRANT REFERENCES ON "SLS"."SLS$SRVC$INV$TR$LINES" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$SRVC$INV$TR$LINES" TO PUBLIC;
  GRANT QUERY REWRITE ON "SLS"."SLS$SRVC$INV$TR$LINES" TO PUBLIC;
  GRANT DEBUG ON "SLS"."SLS$SRVC$INV$TR$LINES" TO PUBLIC;
  GRANT FLASHBACK ON "SLS"."SLS$SRVC$INV$TR$LINES" TO PUBLIC;
