--------------------------------------------------------
--  DDL for Table SLS$SRVC$INV
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$SRVC$INV" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"DOC_DT" DATE, 
	"FY_ID" NUMBER(5,0), 
	"DISP_DOC_ID" VARCHAR2(20 BYTE), 
	"DRFT_INV_ID" VARCHAR2(20 BYTE), 
	"INV_MODE" NUMBER(10,0), 
	"INV_STAT" NUMBER(10,0), 
	"CURR_ID_SP" NUMBER(20,0), 
	"CURR_ID_BS" NUMBER(20,0), 
	"CURR_RATE" NUMBER(26,6), 
	"EO_ID" NUMBER(20,0), 
	"COA_ID" NUMBER(10,0), 
	"BILL_ADD" VARCHAR2(20 BYTE), 
	"EXT_DOC_NO" VARCHAR2(100 BYTE), 
	"EXT_DOC_DT" DATE, 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"TOT_AMT_SP" NUMBER(26,6), 
	"TOT_AMT_BS" NUMBER(26,6), 
	"DISC_TYPE" VARCHAR2(1 BYTE), 
	"DISC_VAL" NUMBER(26,6), 
	"TAX_AFTER_DISC_FLG" VARCHAR2(1 BYTE), 
	"TAX_RULE_FLG" VARCHAR2(1 BYTE), 
	"REMARKS" VARCHAR2(1000 BYTE), 
	"SALES_VOU_ID" VARCHAR2(40 BYTE), 
	"TOT_ITM_AMT_GS_SP" NUMBER(26,6), 
	"TOT_ITM_AMT_GS_BS" NUMBER(26,6), 
	"REV_SALES_VOU_ID" VARCHAR2(40 BYTE), 
	"TAX_FORM_TYP_ID" NUMBER(20,0), 
	"PRJ_ID" VARCHAR2(40 BYTE) DEFAULT 'PROJ0000', 
	"SUPPLI_OPER_TYPE" VARCHAR2(1 BYTE) DEFAULT 'A', 
	"REASON" VARCHAR2(100 BYTE), 
	"PDR_CALCULATED" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"REF_SO_ID" VARCHAR2(50 BYTE), 
	"AMD_NO" NUMBER(10,0), 
	"AMD_DT" DATE, 
	"TAX_TYPE" NUMBER(10,0) DEFAULT 1154, 
	"PNT_OF_SPLY" VARCHAR2(20 BYTE), 
	"RVRS_CHRG_APLICBL" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"FILE_NO" VARCHAR2(50 BYTE), 
	"ORDER_DT" DATE, 
	"DLV_SCHDL_NO" NUMBER(5,0), 
	"DOC_TYPE" NUMBER(5,0) DEFAULT 21532, 
	"CN_VOU_ID" VARCHAR2(40 BYTE), 
	"DOC_SUB_TYPE" NUMBER(5,0) DEFAULT 0, 
	"SI_DISP_ID" VARCHAR2(40 BYTE)
   ) ;

   COMMENT ON COLUMN "SLS"."SLS$SRVC$INV"."SI_DISP_ID" IS 'To Store Sales Invoice Displya Id.';
  GRANT FLASHBACK ON "SLS"."SLS$SRVC$INV" TO PUBLIC;
  GRANT DEBUG ON "SLS"."SLS$SRVC$INV" TO PUBLIC;
  GRANT QUERY REWRITE ON "SLS"."SLS$SRVC$INV" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$SRVC$INV" TO PUBLIC;
  GRANT REFERENCES ON "SLS"."SLS$SRVC$INV" TO PUBLIC;
  GRANT INDEX ON "SLS"."SLS$SRVC$INV" TO PUBLIC;
  GRANT DELETE ON "SLS"."SLS$SRVC$INV" TO PUBLIC;
  GRANT ALTER ON "SLS"."SLS$SRVC$INV" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$SRVC$INV" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$SRVC$INV" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$SRVC$INV" TO PUBLIC;
  GRANT FLASHBACK ON "SLS"."SLS$SRVC$INV" TO "APP";
  GRANT DEBUG ON "SLS"."SLS$SRVC$INV" TO "APP";
  GRANT QUERY REWRITE ON "SLS"."SLS$SRVC$INV" TO "APP";
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$SRVC$INV" TO "APP";
  GRANT REFERENCES ON "SLS"."SLS$SRVC$INV" TO "APP";
  GRANT UPDATE ON "SLS"."SLS$SRVC$INV" TO "APP";
  GRANT SELECT ON "SLS"."SLS$SRVC$INV" TO "APP";
  GRANT INSERT ON "SLS"."SLS$SRVC$INV" TO "APP";
  GRANT INDEX ON "SLS"."SLS$SRVC$INV" TO "APP";
  GRANT DELETE ON "SLS"."SLS$SRVC$INV" TO "APP";
  GRANT ALTER ON "SLS"."SLS$SRVC$INV" TO "APP";
