--------------------------------------------------------
--  DDL for Table SLS$SUBC$OPP$AMD
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$SUBC$OPP$AMD" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"DOC_DT" DATE, 
	"FY_ID" NUMBER(5,0), 
	"EO_ID" NUMBER(22,0), 
	"REMARKS" VARCHAR2(1000 BYTE), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"AMD_NO" VARCHAR2(40 BYTE), 
	"AMD_DATE" DATE, 
	"CURR_ID_SP" NUMBER(10,0), 
	"CURR_RATE" NUMBER(26,6), 
	"CURR_ID_BS" NUMBER(10,0), 
	"DISP_ID" VARCHAR2(20 BYTE), 
	"STATUS" NUMBER(10,0), 
	"PROJ_ID" VARCHAR2(40 BYTE), 
	"ASSIGN_TO" NUMBER(10,0), 
	"SUBC_MODE" NUMBER(10,0), 
	"TRAIL_REQ" VARCHAR2(4 BYTE), 
	"TRAIL_END_DT" DATE, 
	"TRAIL_SRT_DT" DATE, 
	"TRAIL_DAYS" NUMBER(20,0)
   ) ;
