--------------------------------------------------------
--  DDL for Table SLS$TRNP$ROUTE$PRF
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$TRNP$ROUTE$PRF" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"ROUTE_ID" VARCHAR2(20 BYTE), 
	"ROUTE_NM" VARCHAR2(50 BYTE), 
	"ACTV" VARCHAR2(1 BYTE) DEFAULT 'Y', 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"FY_ID" NUMBER(10,0), 
	"GROUP_ID" VARCHAR2(40 BYTE)
   ) ;
  GRANT SELECT ON "SLS"."SLS$TRNP$ROUTE$PRF" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$TRNP$ROUTE$PRF" TO PUBLIC;
  GRANT DEBUG ON "SLS"."SLS$TRNP$ROUTE$PRF" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$TRNP$ROUTE$PRF" TO PUBLIC;
  GRANT ALTER ON "SLS"."SLS$TRNP$ROUTE$PRF" TO "APP";
  GRANT DELETE ON "SLS"."SLS$TRNP$ROUTE$PRF" TO "APP";
  GRANT INDEX ON "SLS"."SLS$TRNP$ROUTE$PRF" TO "APP";
  GRANT INSERT ON "SLS"."SLS$TRNP$ROUTE$PRF" TO "APP";
  GRANT SELECT ON "SLS"."SLS$TRNP$ROUTE$PRF" TO "APP";
  GRANT UPDATE ON "SLS"."SLS$TRNP$ROUTE$PRF" TO "APP";
  GRANT REFERENCES ON "SLS"."SLS$TRNP$ROUTE$PRF" TO "APP";
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$TRNP$ROUTE$PRF" TO "APP";
  GRANT QUERY REWRITE ON "SLS"."SLS$TRNP$ROUTE$PRF" TO "APP";
  GRANT DEBUG ON "SLS"."SLS$TRNP$ROUTE$PRF" TO "APP";
  GRANT FLASHBACK ON "SLS"."SLS$TRNP$ROUTE$PRF" TO "APP";
  GRANT SELECT ON "SLS"."SLS$TRNP$ROUTE$PRF" TO "MNF";
