--------------------------------------------------------
--  DDL for Table SLS$TRNP$FUEL$BILL$DTL
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$TRNP$FUEL$BILL$DTL" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"DOC_ID_FUEL_DTL" VARCHAR2(40 BYTE), 
	"VEHICLE_NO" VARCHAR2(20 BYTE), 
	"EO_INV_NO" VARCHAR2(20 BYTE), 
	"FUEL_QTY" NUMBER(26,6), 
	"FUEL_RATE" NUMBER(26,6), 
	"FUEL_AMT_SP" NUMBER(26,6), 
	"FUEL_AMT_BS" NUMBER(26,6), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"UOM" VARCHAR2(20 BYTE), 
	"VHCL_ITM_ID" VARCHAR2(20 BYTE) DEFAULT 0
   ) ;
  GRANT UPDATE ON "SLS"."SLS$TRNP$FUEL$BILL$DTL" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$TRNP$FUEL$BILL$DTL" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$TRNP$FUEL$BILL$DTL" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$TRNP$FUEL$BILL$DTL" TO "APP";
