--------------------------------------------------------
--  DDL for Table SLS$ANXR
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$ANXR" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"DOC_DT" DATE, 
	"FY_ID" NUMBER(5,0), 
	"ANXR_TYPE" NUMBER(20,0), 
	"EO_ID" NUMBER(20,0), 
	"INVC_DOC_ID" VARCHAR2(40 BYTE), 
	"INVC_DOC_DT" DATE, 
	"ANXR_ID" VARCHAR2(20 BYTE), 
	"ANXR_MODE" NUMBER(10,0), 
	"DRFT_ANXR_ID" VARCHAR2(20 BYTE), 
	"BILL_ADD" VARCHAR2(20 BYTE), 
	"SHIP_ADD" VARCHAR2(20 BYTE), 
	"EXAMNSN_DT" DATE, 
	"EXAMNNG_NM" VARCHAR2(50 BYTE), 
	"SUPRVISR_NM" VARCHAR2(50 BYTE), 
	"CMSNRT_NM" VARCHAR2(50 BYTE), 
	"LOC_CODE" VARCHAR2(50 BYTE), 
	"DESC_OF_GOOD" VARCHAR2(50 BYTE), 
	"SMPL_DRWN" VARCHAR2(50 BYTE), 
	"NMBR_OF_SEAL_PKG" VARCHAR2(50 BYTE), 
	"CSTM_SEAL_NO" VARCHAR2(50 BYTE), 
	"NO_CONTAINRZD_CARGO" VARCHAR2(50 BYTE), 
	"CONTARIZD_CARGO" VARCHAR2(50 BYTE), 
	"AUTHRZD_SIGNATRY" VARCHAR2(50 BYTE), 
	"MOB_NO" NUMBER(10,0), 
	"PRJ_ID" VARCHAR2(40 BYTE) DEFAULT 'PROJ0000', 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE
   ) ;
  GRANT INSERT ON "SLS"."SLS$ANXR" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$ANXR" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$ANXR" TO PUBLIC;
