--------------------------------------------------------
--  DDL for Table SLS$DSH$PRFT$VS$SLS
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$DSH$PRFT$VS$SLS" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"SALES_MONTH_YEAR" VARCHAR2(17 BYTE), 
	"SALES_YEAR" VARCHAR2(4 BYTE), 
	"SALES_MNTH" NUMBER(26,6), 
	"INV_AMT" NUMBER(26,6), 
	"ITM_COST" NUMBER(26,6), 
	"ITM_PROFIT" NUMBER(26,6)
   ) ;
  GRANT INSERT ON "SLS"."SLS$DSH$PRFT$VS$SLS" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$DSH$PRFT$VS$SLS" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$DSH$PRFT$VS$SLS" TO PUBLIC;
