--------------------------------------------------------
--  DDL for Table SLS$SUBC$OPP$DLV$INFO
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$SUBC$OPP$DLV$INFO" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"ITM_ID" VARCHAR2(50 BYTE), 
	"ACTION_ID" NUMBER(5,0), 
	"DLV_STATUS_ID" NUMBER(5,0), 
	"ACTION_EFFEC_DTE" DATE, 
	"LAST_ACTION_DTE" DATE, 
	"DLV_MODE_ID" NUMBER(5,0), 
	"FORMAT" VARCHAR2(300 BYTE), 
	"DISCRIPTION" VARCHAR2(400 BYTE), 
	"USR_ID_CREATE" NUMBER(5,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(5,0), 
	"USR_ID_MOD_DT" DATE, 
	"DLVR_TYPE_ID" NUMBER(5,0), 
	"ITM_SR_NO" NUMBER(10,0), 
	"DOC_ID_SRC" VARCHAR2(40 BYTE), 
	"TRIAL_DAYS" NUMBER(26,0)
   ) ;
