--------------------------------------------------------
--  DDL for Table SLS$SUBC$PACKAGE
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$SUBC$PACKAGE" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"GLBL_DOC_ID" NUMBER(5,0), 
	"PACKAGE_ID" NUMBER(5,0) DEFAULT sls.seq_SLS_SUBC_PACKAGE.nextval, 
	"PACKAGE_NM" VARCHAR2(100 BYTE), 
	"USR_ID_CREATE" NUMBER(5,0), 
	"USR_ID_CREATE_DT" DATE DEFAULT sysdate, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"ACTV" VARCHAR2(1 BYTE) DEFAULT 'Y', 
	"REF_DOC_TXN_ID" VARCHAR2(40 BYTE)
   ) ;
  GRANT INSERT ON "SLS"."SLS$SUBC$PACKAGE" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$SUBC$PACKAGE" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$SUBC$PACKAGE" TO PUBLIC;
