--------------------------------------------------------
--  DDL for Table SLS$TRNP$OL$PROD$DTL
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$TRNP$OL$PROD$DTL" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"DEPARTURE_PNT" VARCHAR2(20 BYTE), 
	"ARRIVAL_PNT" VARCHAR2(20 BYTE), 
	"DOC_ID_SRC" VARCHAR2(40 BYTE), 
	"ITM_ID" VARCHAR2(50 BYTE), 
	"ITM_WT" NUMBER(26,6), 
	"ITM_WT_UOM" VARCHAR2(20 BYTE), 
	"RATE" NUMBER(26,6), 
	"ITM_AMT_SP" NUMBER(26,6), 
	"ITM_AMT_BS" NUMBER(26,6), 
	"SHIP_QTY" NUMBER(26,6), 
	"SHIP_QTY_UOM" VARCHAR2(20 BYTE), 
	"DAMG_QTY" NUMBER(26,6), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"SCHDL_NO" NUMBER DEFAULT 1, 
	"SHIPMNT_DOC_ID" VARCHAR2(50 BYTE) DEFAULT '0', 
	"ITM_SR_NO" NUMBER(5,0) DEFAULT 1
   ) ;
  GRANT SELECT ON "SLS"."SLS$TRNP$OL$PROD$DTL" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$TRNP$OL$PROD$DTL" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$TRNP$OL$PROD$DTL" TO PUBLIC;
