--------------------------------------------------------
--  DDL for Table SLS$TRNP$OL
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$TRNP$OL" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"OL_ID" VARCHAR2(20 BYTE), 
	"OL_DT" DATE, 
	"EO_ID" NUMBER(5,0), 
	"TRNSP_ID" NUMBER(5,0), 
	"LO_DOC_ID" VARCHAR2(40 BYTE), 
	"LO_TYP" VARCHAR2(5 BYTE), 
	"VEHICLE_NO" VARCHAR2(20 BYTE), 
	"CURR_ID_SP" NUMBER(20,0), 
	"CURR_CONV_FCTR" NUMBER(26,6), 
	"TOT_VAL_SP" NUMBER(26,6), 
	"TOT_VAL_BS" NUMBER(26,6), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"RATE_BASIS" VARCHAR2(1 BYTE), 
	"OL_STATUS" NUMBER(5,0), 
	"RATE_FCTR" VARCHAR2(1 BYTE), 
	"TOT_KM" NUMBER(26,6), 
	"OL_BASIS" NUMBER(5,0), 
	"VHCL_ITM_ID" VARCHAR2(50 BYTE), 
	"REQ_TYP" VARCHAR2(1 BYTE), 
	"ADHOC_FLG" VARCHAR2(2 BYTE), 
	"FY_ID" NUMBER(10,0), 
	"ORDER_OUT_TIME" DATE, 
	"ORDER_IN_TIME" DATE, 
	"REMARKS" VARCHAR2(200 BYTE)
   ) ;

   COMMENT ON COLUMN "SLS"."SLS$TRNP$OL"."ADHOC_FLG" IS 'Use Offloading as AdHoc (Custom) document.';
  GRANT INSERT ON "SLS"."SLS$TRNP$OL" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$TRNP$OL" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$TRNP$OL" TO PUBLIC;
