--------------------------------------------------------
--  DDL for Table SLS$INTM$SLIP$SR$NOTE
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$INTM$SLIP$SR$NOTE" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"SHIPMNT_DOC_ID" VARCHAR2(40 BYTE), 
	"SO_ID" VARCHAR2(40 BYTE), 
	"PICK_ID" VARCHAR2(40 BYTE), 
	"ITM_ID" VARCHAR2(50 BYTE), 
	"ITM_SR_NO" NUMBER(10,0) DEFAULT 1, 
	"SRL_NO" NUMBER(10,0), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE DEFAULT SYSDATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"SR_NO" VARCHAR2(100 BYTE)
   ) ;
  GRANT INSERT ON "SLS"."SLS$INTM$SLIP$SR$NOTE" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$INTM$SLIP$SR$NOTE" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$INTM$SLIP$SR$NOTE" TO PUBLIC;
