--------------------------------------------------------
--  DDL for Table SLS$SHIPMNT
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$SHIPMNT" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"DOC_DT" DATE, 
	"EO_ID" NUMBER(20,0), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE DEFAULT SYSDATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"SHIPMNT_ID" VARCHAR2(20 BYTE), 
	"CURR_ID_SP" NUMBER(10,0), 
	"CURR_ID_BS" NUMBER(10,0), 
	"CURR_CONV_FCTR" NUMBER(26,6), 
	"WH_ID" VARCHAR2(20 BYTE), 
	"PICK_ID" VARCHAR2(40 BYTE), 
	"FY_ID" NUMBER(5,0), 
	"SHIPMNT_STAT" NUMBER(10,0), 
	"COGS_VOU_ID" VARCHAR2(40 BYTE), 
	"TRANSPORTER_ID" NUMBER(20,0), 
	"REMARKS" VARCHAR2(1000 BYTE), 
	"TRANS_MODE" NUMBER(5,0), 
	"TRANS_VH_NO" VARCHAR2(50 BYTE), 
	"TRANS_CONTNR_NO" VARCHAR2(50 BYTE), 
	"TRANS_GR_NO" VARCHAR2(50 BYTE), 
	"SHIP_ADDS" VARCHAR2(20 BYTE), 
	"REV_COGS_VOU_ID" VARCHAR2(40 BYTE), 
	"EMP_EO_ID" NUMBER(20,0), 
	"PRJ_ID" VARCHAR2(40 BYTE) DEFAULT 'PROJ0000', 
	"REQ_TYP" VARCHAR2(1 BYTE), 
	"VEHICLE_TYP" NUMBER(20,0), 
	"ROUTE_DOC_ID" VARCHAR2(40 BYTE), 
	"TO_PAY" VARCHAR2(1 BYTE), 
	"EXT_DOC_NO" VARCHAR2(40 BYTE), 
	"EO_TPT_NO" VARCHAR2(40 BYTE)
   ) ;

   COMMENT ON COLUMN "SLS"."SLS$SHIPMNT"."COGS_VOU_ID" IS 'COST OF GOOD SALES VOUCHER ID';
  GRANT FLASHBACK ON "SLS"."SLS$SHIPMNT" TO "PMS";
  GRANT DEBUG ON "SLS"."SLS$SHIPMNT" TO "PMS";
  GRANT QUERY REWRITE ON "SLS"."SLS$SHIPMNT" TO "PMS";
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$SHIPMNT" TO "PMS";
  GRANT REFERENCES ON "SLS"."SLS$SHIPMNT" TO "PMS";
  GRANT UPDATE ON "SLS"."SLS$SHIPMNT" TO "PMS";
  GRANT SELECT ON "SLS"."SLS$SHIPMNT" TO "PMS";
  GRANT INSERT ON "SLS"."SLS$SHIPMNT" TO "PMS";
  GRANT INDEX ON "SLS"."SLS$SHIPMNT" TO "PMS";
  GRANT DELETE ON "SLS"."SLS$SHIPMNT" TO "PMS";
  GRANT ALTER ON "SLS"."SLS$SHIPMNT" TO "PMS";
  GRANT SELECT ON "SLS"."SLS$SHIPMNT" TO "SVC";
  GRANT INSERT ON "SLS"."SLS$SHIPMNT" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$SHIPMNT" TO PUBLIC;
  GRANT INDEX ON "SLS"."SLS$SHIPMNT" TO PUBLIC;
  GRANT DELETE ON "SLS"."SLS$SHIPMNT" TO PUBLIC;
  GRANT ALTER ON "SLS"."SLS$SHIPMNT" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$SHIPMNT" TO "MM";
  GRANT SELECT ON "SLS"."SLS$SHIPMNT" TO "MM" WITH GRANT OPTION;
  GRANT REFERENCES ON "SLS"."SLS$SHIPMNT" TO "MM";
  GRANT QUERY REWRITE ON "SLS"."SLS$SHIPMNT" TO "MM";
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$SHIPMNT" TO "MM";
  GRANT INSERT ON "SLS"."SLS$SHIPMNT" TO "MM";
  GRANT INDEX ON "SLS"."SLS$SHIPMNT" TO "MM";
  GRANT FLASHBACK ON "SLS"."SLS$SHIPMNT" TO "MM";
  GRANT DELETE ON "SLS"."SLS$SHIPMNT" TO "MM";
  GRANT DEBUG ON "SLS"."SLS$SHIPMNT" TO "MM";
  GRANT ALTER ON "SLS"."SLS$SHIPMNT" TO "MM";
  GRANT FLASHBACK ON "SLS"."SLS$SHIPMNT" TO "APP";
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$SHIPMNT" TO "APP";
  GRANT SELECT ON "SLS"."SLS$SHIPMNT" TO "APP";
  GRANT INSERT ON "SLS"."SLS$SHIPMNT" TO "APP";
  GRANT QUERY REWRITE ON "SLS"."SLS$SHIPMNT" TO "APP";
  GRANT UPDATE ON "SLS"."SLS$SHIPMNT" TO "APP";
  GRANT DELETE ON "SLS"."SLS$SHIPMNT" TO "APP";
  GRANT ALTER ON "SLS"."SLS$SHIPMNT" TO "APP";
  GRANT REFERENCES ON "SLS"."SLS$SHIPMNT" TO "APP";
  GRANT INDEX ON "SLS"."SLS$SHIPMNT" TO "APP";
  GRANT ALTER ON "SLS"."SLS$SHIPMNT" TO "MNF" WITH GRANT OPTION;
  GRANT DEBUG ON "SLS"."SLS$SHIPMNT" TO "MNF" WITH GRANT OPTION;
  GRANT DELETE ON "SLS"."SLS$SHIPMNT" TO "MNF" WITH GRANT OPTION;
  GRANT FLASHBACK ON "SLS"."SLS$SHIPMNT" TO "MNF" WITH GRANT OPTION;
  GRANT INDEX ON "SLS"."SLS$SHIPMNT" TO "MNF" WITH GRANT OPTION;
  GRANT INSERT ON "SLS"."SLS$SHIPMNT" TO "MNF" WITH GRANT OPTION;
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$SHIPMNT" TO "MNF" WITH GRANT OPTION;
  GRANT QUERY REWRITE ON "SLS"."SLS$SHIPMNT" TO "MNF" WITH GRANT OPTION;
  GRANT REFERENCES ON "SLS"."SLS$SHIPMNT" TO "MNF" WITH GRANT OPTION;
  GRANT SELECT ON "SLS"."SLS$SHIPMNT" TO "MNF" WITH GRANT OPTION;
  GRANT UPDATE ON "SLS"."SLS$SHIPMNT" TO "MNF" WITH GRANT OPTION;
  GRANT DEBUG ON "SLS"."SLS$SHIPMNT" TO "APP";
  GRANT FLASHBACK ON "SLS"."SLS$SHIPMNT" TO PUBLIC;
  GRANT DEBUG ON "SLS"."SLS$SHIPMNT" TO PUBLIC;
  GRANT QUERY REWRITE ON "SLS"."SLS$SHIPMNT" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$SHIPMNT" TO PUBLIC;
  GRANT REFERENCES ON "SLS"."SLS$SHIPMNT" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$SHIPMNT" TO PUBLIC;
