--------------------------------------------------------
--  DDL for Table SLS$TRNP$RATE$CNTRCT
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$TRNP$RATE$CNTRCT" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"EO_ID" NUMBER(20,0), 
	"EFFECTIVE_DT" DATE, 
	"ACTV" VARCHAR2(1 BYTE), 
	"CNTRCT_BASIS" VARCHAR2(1 BYTE), 
	"RATE_FCTR" VARCHAR2(1 BYTE), 
	"RATE" NUMBER(26,6), 
	"RATE_UOM" VARCHAR2(20 BYTE), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"VHCL_TYPE" NUMBER(5,0), 
	"INACTV_DT" DATE, 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"RC_ID" VARCHAR2(20 BYTE), 
	"CURR_ID_SP" NUMBER(5,0), 
	"CURR_CONV" NUMBER(26,6), 
	"EO_TYPE" NUMBER(5,0), 
	"DAY_MIN_AMT" NUMBER(26,6), 
	"MIN_DIST_RATE" NUMBER(26,6), 
	"MIN_DIST" NUMBER(26,6), 
	"ROUTE_ID" VARCHAR2(40 BYTE), 
	"DEPARTURE_PNT" VARCHAR2(20 BYTE), 
	"ARRIVAL_PNT" VARCHAR2(20 BYTE), 
	"AMND_DOC_ID" VARCHAR2(40 BYTE), 
	"STATUS_ID" NUMBER, 
	"MIN_LOAD_CPCTY" NUMBER(26,6) DEFAULT 0, 
	"MAX_DROP_OFF" NUMBER(26,6) DEFAULT 0, 
	"DROP_OFF_CHRGS" NUMBER(26,6) DEFAULT 0
   ) ;
  GRANT INSERT ON "SLS"."SLS$TRNP$RATE$CNTRCT" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$TRNP$RATE$CNTRCT" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$TRNP$RATE$CNTRCT" TO PUBLIC;
