--------------------------------------------------------
--  DDL for Table SLS$SO$PAYMNT
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$SO$PAYMNT" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"CURR_ID_SP" NUMBER(10,0), 
	"CURR_CONV_FCTR" NUMBER(26,6), 
	"CURR_ID_BS" NUMBER(10,0), 
	"TOT_AMT_SP" NUMBER(26,6), 
	"TOT_AMT_BS" NUMBER(26,6), 
	"AMD_NO" VARCHAR2(40 BYTE), 
	"AMD_DT" DATE, 
	"PAY_MODE" NUMBER(20,0), 
	"PAY_TYPE_NO" VARCHAR2(30 BYTE), 
	"PAY_TYPE_DT" DATE, 
	"BANK_AC_NO" VARCHAR2(50 BYTE), 
	"ADDS_ID" VARCHAR2(20 BYTE), 
	"REMARKS" VARCHAR2(250 BYTE), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE DEFAULT SYSDATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"SR_NO" NUMBER(5,0), 
	"BANK_NM" VARCHAR2(50 BYTE), 
	"PHONE_NO" VARCHAR2(50 BYTE), 
	"INSTRUMENT_NO" NUMBER(26,6), 
	"ACT_RECVD_AMT" NUMBER(26,6), 
	"ACC_ID" NUMBER(26,6), 
	"MACHINE_ID" VARCHAR2(100 BYTE), 
	"VOU_GENRTD" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"INSTRU_DATE" DATE, 
	"INSTRU_AMOUNT" NUMBER(26,6), 
	"NARR" VARCHAR2(1000 BYTE), 
	"BANK_COA_ID" NUMBER(20,0), 
	"BANK_SP_CURR" NUMBER(20,0), 
	"INSTRU_NO" VARCHAR2(100 BYTE), 
	"BP_BR_VOU_ID" VARCHAR2(40 BYTE), 
	"INSTRU_NM" VARCHAR2(250 BYTE), 
	"POS_ADV_FLG" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"RCVD_AMT_SP" NUMBER(26,6)
   ) ;

   COMMENT ON COLUMN "SLS"."SLS$SO$PAYMNT"."PHONE_NO" IS 'FIELD TO STORE PHONE NO. IN CASE PAYMENT MODE IS MPESA.';
  GRANT FLASHBACK ON "SLS"."SLS$SO$PAYMNT" TO PUBLIC;
  GRANT QUERY REWRITE ON "SLS"."SLS$SO$PAYMNT" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$SO$PAYMNT" TO PUBLIC;
  GRANT REFERENCES ON "SLS"."SLS$SO$PAYMNT" TO PUBLIC;
  GRANT INDEX ON "SLS"."SLS$SO$PAYMNT" TO PUBLIC;
  GRANT DELETE ON "SLS"."SLS$SO$PAYMNT" TO PUBLIC;
  GRANT ALTER ON "SLS"."SLS$SO$PAYMNT" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$SO$PAYMNT" TO PUBLIC;
  GRANT FLASHBACK ON "SLS"."SLS$SO$PAYMNT" TO "FIN";
  GRANT DEBUG ON "SLS"."SLS$SO$PAYMNT" TO "FIN";
  GRANT QUERY REWRITE ON "SLS"."SLS$SO$PAYMNT" TO "FIN";
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$SO$PAYMNT" TO "FIN";
  GRANT REFERENCES ON "SLS"."SLS$SO$PAYMNT" TO "FIN";
  GRANT UPDATE ON "SLS"."SLS$SO$PAYMNT" TO "FIN";
  GRANT SELECT ON "SLS"."SLS$SO$PAYMNT" TO "FIN";
  GRANT INSERT ON "SLS"."SLS$SO$PAYMNT" TO "FIN";
  GRANT INDEX ON "SLS"."SLS$SO$PAYMNT" TO "FIN";
  GRANT DELETE ON "SLS"."SLS$SO$PAYMNT" TO "FIN";
  GRANT ALTER ON "SLS"."SLS$SO$PAYMNT" TO "FIN";
  GRANT UPDATE ON "SLS"."SLS$SO$PAYMNT" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$SO$PAYMNT" TO PUBLIC;
  GRANT DEBUG ON "SLS"."SLS$SO$PAYMNT" TO PUBLIC;
  GRANT FLASHBACK ON "SLS"."SLS$SO$PAYMNT" TO "PMS";
  GRANT DEBUG ON "SLS"."SLS$SO$PAYMNT" TO "PMS";
  GRANT QUERY REWRITE ON "SLS"."SLS$SO$PAYMNT" TO "PMS";
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$SO$PAYMNT" TO "PMS";
  GRANT REFERENCES ON "SLS"."SLS$SO$PAYMNT" TO "PMS";
  GRANT UPDATE ON "SLS"."SLS$SO$PAYMNT" TO "PMS";
  GRANT SELECT ON "SLS"."SLS$SO$PAYMNT" TO "PMS";
  GRANT INSERT ON "SLS"."SLS$SO$PAYMNT" TO "PMS";
  GRANT INDEX ON "SLS"."SLS$SO$PAYMNT" TO "PMS";
  GRANT DELETE ON "SLS"."SLS$SO$PAYMNT" TO "PMS";
  GRANT ALTER ON "SLS"."SLS$SO$PAYMNT" TO "PMS";
