--------------------------------------------------------
--  DDL for Table SLS$RMA$ISSU$BIN
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$RMA$ISSU$BIN" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"DOC_DT" DATE, 
	"SHIPMNT_ID" VARCHAR2(40 BYTE), 
	"PICK_ID" VARCHAR2(40 BYTE), 
	"SO_ID" VARCHAR2(40 BYTE), 
	"WH_ID" VARCHAR2(20 BYTE) DEFAULT 0, 
	"ITM_ID_RCV" VARCHAR2(50 BYTE), 
	"ITM_SR_NO" NUMBER(10,0) DEFAULT 1, 
	"WH_ID_ISSU" VARCHAR2(20 BYTE), 
	"ITM_ID_ISSU" VARCHAR2(50 BYTE), 
	"ITM_UOM" VARCHAR2(20 BYTE), 
	"LOT_ID" VARCHAR2(20 BYTE), 
	"BIN_ID" VARCHAR2(20 BYTE), 
	"ISSU_QTY" NUMBER(26,6), 
	"REMARKS" VARCHAR2(1000 BYTE), 
	"PRJ_ID" VARCHAR2(40 BYTE) DEFAULT 'PROJ0000', 
	"CNT_QTY" NUMBER(26,6) DEFAULT 0, 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE DEFAULT SYSDATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"ISSU_QTY_BS" NUMBER(26,6) DEFAULT 0
   ) ;
  GRANT INSERT ON "SLS"."SLS$RMA$ISSU$BIN" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$RMA$ISSU$BIN" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$RMA$ISSU$BIN" TO PUBLIC;
