--------------------------------------------------------
--  DDL for Table SLS$INV$PMNT$SCHDL
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$INV$PMNT$SCHDL" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"PAY_DT" DATE, 
	"PAY_MODE" NUMBER(20,0), 
	"TOT_AMT" NUMBER(26,6), 
	"PAY_AMT" NUMBER(26,6), 
	"ADV_FLG" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"PHONE_NO" VARCHAR2(50 BYTE)
   ) ;

   COMMENT ON COLUMN "SLS"."SLS$INV$PMNT$SCHDL"."PHONE_NO" IS 'FIELD TO STORE PHONE NO. IN CASE PAYMENT MODE IS MPESA.';
  GRANT FLASHBACK ON "SLS"."SLS$INV$PMNT$SCHDL" TO "PMS";
  GRANT DEBUG ON "SLS"."SLS$INV$PMNT$SCHDL" TO "PMS";
  GRANT QUERY REWRITE ON "SLS"."SLS$INV$PMNT$SCHDL" TO "PMS";
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$INV$PMNT$SCHDL" TO "PMS";
  GRANT REFERENCES ON "SLS"."SLS$INV$PMNT$SCHDL" TO "PMS";
  GRANT UPDATE ON "SLS"."SLS$INV$PMNT$SCHDL" TO "PMS";
  GRANT SELECT ON "SLS"."SLS$INV$PMNT$SCHDL" TO "PMS";
  GRANT INSERT ON "SLS"."SLS$INV$PMNT$SCHDL" TO "PMS";
  GRANT INDEX ON "SLS"."SLS$INV$PMNT$SCHDL" TO "PMS";
  GRANT DELETE ON "SLS"."SLS$INV$PMNT$SCHDL" TO "PMS";
  GRANT ALTER ON "SLS"."SLS$INV$PMNT$SCHDL" TO "PMS";
  GRANT FLASHBACK ON "SLS"."SLS$INV$PMNT$SCHDL" TO PUBLIC;
  GRANT DEBUG ON "SLS"."SLS$INV$PMNT$SCHDL" TO PUBLIC;
  GRANT QUERY REWRITE ON "SLS"."SLS$INV$PMNT$SCHDL" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$INV$PMNT$SCHDL" TO PUBLIC;
  GRANT REFERENCES ON "SLS"."SLS$INV$PMNT$SCHDL" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$INV$PMNT$SCHDL" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$INV$PMNT$SCHDL" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$INV$PMNT$SCHDL" TO PUBLIC;
  GRANT INDEX ON "SLS"."SLS$INV$PMNT$SCHDL" TO PUBLIC;
  GRANT DELETE ON "SLS"."SLS$INV$PMNT$SCHDL" TO PUBLIC;
  GRANT ALTER ON "SLS"."SLS$INV$PMNT$SCHDL" TO PUBLIC;
