--------------------------------------------------------
--  DDL for Table SLS$RMA$ITM$ASMBL$STK$DTL
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$RMA$ITM$ASMBL$STK$DTL" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"SHIPMNT_ID" VARCHAR2(40 BYTE), 
	"SHIPMNT_DT" DATE, 
	"LOT_ID" VARCHAR2(20 BYTE), 
	"SR_NO" VARCHAR2(100 BYTE), 
	"BIN_ID" VARCHAR2(20 BYTE), 
	"ITM_ID" VARCHAR2(50 BYTE), 
	"ITM_ID_COMP" VARCHAR2(50 BYTE), 
	"ITM_UOM" VARCHAR2(20 BYTE), 
	"RCPT_QTY" NUMBER(26,6), 
	"RCPT_QTY_BS" NUMBER(26,6), 
	"OK_QTY" NUMBER(26,6), 
	"OK_QTY_BS" NUMBER(26,6), 
	"RWK_QTY" NUMBER(26,6), 
	"RWK_QTY_BS" NUMBER(26,6), 
	"REJ_QTY" NUMBER(26,6), 
	"REJ_QTY_BS" NUMBER(26,6), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"WH_ID" VARCHAR2(20 BYTE), 
	"SO_ID" VARCHAR2(40 BYTE), 
	"PICK_ID" VARCHAR2(40 BYTE), 
	"PRJ_ID" VARCHAR2(40 BYTE) DEFAULT 'PROJ0000', 
	"ITM_SR_NO" NUMBER(10,0) DEFAULT 1, 
	"CNT_QTY" NUMBER(26,6) DEFAULT 0
   ) ;
