--------------------------------------------------------
--  DDL for Table SLS$POS$PRICE
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$POS$PRICE" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"PRJ_ID" VARCHAR2(40 BYTE), 
	"ITM_ID" VARCHAR2(50 BYTE), 
	"ITM_UOM" VARCHAR2(20 BYTE), 
	"BASE_PRICE" NUMBER(26,6), 
	"TAXABLE_PRICE" NUMBER(26,6), 
	"EFFECTIVE_DT" TIMESTAMP (8), 
	"ACTIVE" VARCHAR2(2 BYTE), 
	"DEBIT_NOTE_GEN" VARCHAR2(2 BYTE) DEFAULT 'N', 
	"EO_TYP_ID" NUMBER(5,0) DEFAULT -1, 
	"ITM_MIN_PRICE" NUMBER(26,6) DEFAULT 0, 
	"USR_CREATE_ID" NUMBER(4,0), 
	"USR_CREATE_DT" DATE DEFAULT sysdate, 
	"USR_MOD_ID" NUMBER(4,0), 
	"USR_MOD_DT" DATE
   ) ;
  GRANT ALTER ON "SLS"."SLS$POS$PRICE" TO PUBLIC;
  GRANT DELETE ON "SLS"."SLS$POS$PRICE" TO PUBLIC;
  GRANT INDEX ON "SLS"."SLS$POS$PRICE" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$POS$PRICE" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$POS$PRICE" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$POS$PRICE" TO PUBLIC;
  GRANT REFERENCES ON "SLS"."SLS$POS$PRICE" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$POS$PRICE" TO PUBLIC;
  GRANT QUERY REWRITE ON "SLS"."SLS$POS$PRICE" TO PUBLIC;
  GRANT DEBUG ON "SLS"."SLS$POS$PRICE" TO PUBLIC;
  GRANT FLASHBACK ON "SLS"."SLS$POS$PRICE" TO PUBLIC;
  GRANT ALTER ON "SLS"."SLS$POS$PRICE" TO "MM";
  GRANT DELETE ON "SLS"."SLS$POS$PRICE" TO "MM";
  GRANT INDEX ON "SLS"."SLS$POS$PRICE" TO "MM";
  GRANT INSERT ON "SLS"."SLS$POS$PRICE" TO "MM";
  GRANT SELECT ON "SLS"."SLS$POS$PRICE" TO "MM";
  GRANT UPDATE ON "SLS"."SLS$POS$PRICE" TO "MM";
  GRANT REFERENCES ON "SLS"."SLS$POS$PRICE" TO "MM";
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$POS$PRICE" TO "MM";
  GRANT QUERY REWRITE ON "SLS"."SLS$POS$PRICE" TO "MM";
  GRANT DEBUG ON "SLS"."SLS$POS$PRICE" TO "MM";
  GRANT FLASHBACK ON "SLS"."SLS$POS$PRICE" TO "MM";
