--------------------------------------------------------
--  DDL for Table SLS$SO$ITM$TRF
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$SO$ITM$TRF" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"ITM_ID" VARCHAR2(50 BYTE), 
	"FY_ID" NUMBER(5,0), 
	"ORG_ID_SRC" VARCHAR2(2 BYTE), 
	"WH_ID_SRC" VARCHAR2(20 BYTE), 
	"ORG_ID_DEST" VARCHAR2(2 BYTE), 
	"WH_ID_DEST" VARCHAR2(20 BYTE), 
	"ITM_UOM" VARCHAR2(20 BYTE), 
	"ITM_UOM_BS" VARCHAR2(20 BYTE), 
	"UOM_CONV_FCTR" NUMBER(26,6), 
	"ITM_TRF_QTY" NUMBER(26,6), 
	"ITM_TRF_QTY_BS" NUMBER(26,6), 
	"AVL_QTY" NUMBER(26,6), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"DLV_SCHDL_NO" NUMBER(4,0), 
	"DLV_DT" DATE, 
	"TRF_STAT" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"ITM_SR_NO" NUMBER(10,0) DEFAULT 1, 
	"CNT_QTY" NUMBER(26,6) DEFAULT 0
   ) ;
  GRANT REFERENCES ON "SLS"."SLS$SO$ITM$TRF" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$SO$ITM$TRF" TO PUBLIC;
  GRANT QUERY REWRITE ON "SLS"."SLS$SO$ITM$TRF" TO PUBLIC;
  GRANT DEBUG ON "SLS"."SLS$SO$ITM$TRF" TO PUBLIC;
  GRANT FLASHBACK ON "SLS"."SLS$SO$ITM$TRF" TO PUBLIC;
  GRANT ALTER ON "SLS"."SLS$SO$ITM$TRF" TO PUBLIC;
  GRANT DELETE ON "SLS"."SLS$SO$ITM$TRF" TO PUBLIC;
  GRANT INDEX ON "SLS"."SLS$SO$ITM$TRF" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$SO$ITM$TRF" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$SO$ITM$TRF" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$SO$ITM$TRF" TO PUBLIC;
