--------------------------------------------------------
--  DDL for Table SLS$PACK
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$PACK" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"DOC_DT" DATE, 
	"PACK_TYP_ID" NUMBER(20,0), 
	"PACK_ID" VARCHAR2(20 BYTE), 
	"PACK_DIMEN_LEN" NUMBER(26,6), 
	"PACK_DIMEN_WID" NUMBER(26,6), 
	"PACK_DIMEN_HIG" NUMBER(26,6), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"PACK_WT" NUMBER(26,6), 
	"PICK_ID" VARCHAR2(40 BYTE), 
	"PICK_DT" DATE, 
	"DIMEN_UNIT" VARCHAR2(20 BYTE), 
	"FY_ID" NUMBER(5,0), 
	"FREEZE_PACK_ITM" VARCHAR2(1 BYTE), 
	"WH_ID" VARCHAR2(20 BYTE), 
	"EO_ID" NUMBER(20,0), 
	"COGS_VOU_ID" VARCHAR2(40 BYTE), 
	"PACK_STAT" NUMBER(5,0), 
	"REV_COGS_VOU_ID" VARCHAR2(40 BYTE), 
	"PRJ_ID" VARCHAR2(40 BYTE) DEFAULT 'PROJ0000', 
	"PACK_NET_WT" NUMBER(26,6), 
	"SHIP_PACK_TYP" NUMBER(10,0), 
	"GATE_PASS_DOC_ID" VARCHAR2(40 BYTE), 
	"GATE_PASS_DISP_ID" VARCHAR2(40 BYTE)
   ) ;

   COMMENT ON COLUMN "SLS"."SLS$PACK"."PACK_WT" IS 'Pack Weight';
   COMMENT ON COLUMN "SLS"."SLS$PACK"."DIMEN_UNIT" IS 'Unit for packing dimesion';
  GRANT FLASHBACK ON "SLS"."SLS$PACK" TO PUBLIC;
  GRANT ALTER ON "SLS"."SLS$PACK" TO "MM";
  GRANT ALTER ON "SLS"."SLS$PACK" TO "MNF" WITH GRANT OPTION;
  GRANT DEBUG ON "SLS"."SLS$PACK" TO "MNF" WITH GRANT OPTION;
  GRANT DELETE ON "SLS"."SLS$PACK" TO "MNF" WITH GRANT OPTION;
  GRANT FLASHBACK ON "SLS"."SLS$PACK" TO "MNF" WITH GRANT OPTION;
  GRANT INDEX ON "SLS"."SLS$PACK" TO "MNF" WITH GRANT OPTION;
  GRANT INSERT ON "SLS"."SLS$PACK" TO "MNF" WITH GRANT OPTION;
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$PACK" TO "MNF" WITH GRANT OPTION;
  GRANT QUERY REWRITE ON "SLS"."SLS$PACK" TO "MNF" WITH GRANT OPTION;
  GRANT REFERENCES ON "SLS"."SLS$PACK" TO "MNF" WITH GRANT OPTION;
  GRANT SELECT ON "SLS"."SLS$PACK" TO "MNF" WITH GRANT OPTION;
  GRANT UPDATE ON "SLS"."SLS$PACK" TO "MNF" WITH GRANT OPTION;
  GRANT DEBUG ON "SLS"."SLS$PACK" TO "MM";
  GRANT UPDATE ON "SLS"."SLS$PACK" TO "MM";
  GRANT DELETE ON "SLS"."SLS$PACK" TO "MM";
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$PACK" TO "MM";
  GRANT INSERT ON "SLS"."SLS$PACK" TO "MM";
  GRANT REFERENCES ON "SLS"."SLS$PACK" TO "MM";
  GRANT QUERY REWRITE ON "SLS"."SLS$PACK" TO "MM";
  GRANT FLASHBACK ON "SLS"."SLS$PACK" TO "MM";
  GRANT SELECT ON "SLS"."SLS$PACK" TO "MM";
  GRANT INDEX ON "SLS"."SLS$PACK" TO "MM";
  GRANT ALTER ON "SLS"."SLS$PACK" TO PUBLIC;
  GRANT DELETE ON "SLS"."SLS$PACK" TO PUBLIC;
  GRANT INDEX ON "SLS"."SLS$PACK" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$PACK" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$PACK" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$PACK" TO PUBLIC;
  GRANT REFERENCES ON "SLS"."SLS$PACK" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$PACK" TO PUBLIC;
  GRANT QUERY REWRITE ON "SLS"."SLS$PACK" TO PUBLIC;
  GRANT DEBUG ON "SLS"."SLS$PACK" TO PUBLIC;
