--------------------------------------------------------
--  DDL for Table SLS$DSH$OPP$ANLYS
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$DSH$OPP$ANLYS" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_MONTH_YEAR" VARCHAR2(17 BYTE), 
	"DOC_MNTH" NUMBER(26,6), 
	"DOC_YEAR" VARCHAR2(4 BYTE), 
	"DOC_CLOSED" NUMBER(26,0), 
	"DOC_CANCEL" NUMBER(26,0), 
	"DOC_AMT_CLOSED" NUMBER(26,0), 
	"DOC_AMT_PEND" NUMBER(26,0), 
	"DOC_AMT_CANCEL" NUMBER(26,0), 
	"DOC_ID" NUMBER(10,0), 
	"DOC_PEND" NUMBER(20,0)
   ) ;
  GRANT INSERT ON "SLS"."SLS$DSH$OPP$ANLYS" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$DSH$OPP$ANLYS" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$DSH$OPP$ANLYS" TO PUBLIC;
