--------------------------------------------------------
--  DDL for Table SLS$INCT$PRF
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$INCT$PRF" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"PRD_START_DT" DATE, 
	"PRD_END_DT" DATE, 
	"INCT_ID" VARCHAR2(20 BYTE), 
	"TRGT_TYPE" NUMBER(5,0), 
	"FREQ_BASIS" NUMBER(20,0), 
	"INCT_START_DT" DATE, 
	"INCT_END_DT" DATE, 
	"FY_ID" NUMBER(2,0), 
	"INCT_STAT" NUMBER(5,0), 
	"FINALIZE" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"PRJ_ID" VARCHAR2(40 BYTE), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"ACT_FLG" CHAR(1 BYTE), 
	"ACT_RES" VARCHAR2(1000 BYTE), 
	"AMD_NUM" NUMBER(26,0) DEFAULT 0, 
	"AMD_DATE" DATE DEFAULT sysdate, 
	"TRGT_BASIS" NUMBER(5,0) DEFAULT 2220
   ) ;

   COMMENT ON COLUMN "SLS"."SLS$INCT$PRF"."TRGT_TYPE" IS '1 - COLLECTION, 2 - REVENUE';
   COMMENT ON COLUMN "SLS"."SLS$INCT$PRF"."FREQ_BASIS" IS '1 - DAILY, 2- WEEKLY, 3- QUARTERLY, 4- HALFYEARLY, 5- MONTHLY';
  GRANT ALTER ON "SLS"."SLS$INCT$PRF" TO PUBLIC;
  GRANT DELETE ON "SLS"."SLS$INCT$PRF" TO PUBLIC;
  GRANT INDEX ON "SLS"."SLS$INCT$PRF" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$INCT$PRF" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$INCT$PRF" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$INCT$PRF" TO PUBLIC;
  GRANT REFERENCES ON "SLS"."SLS$INCT$PRF" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$INCT$PRF" TO PUBLIC;
  GRANT QUERY REWRITE ON "SLS"."SLS$INCT$PRF" TO PUBLIC;
  GRANT DEBUG ON "SLS"."SLS$INCT$PRF" TO PUBLIC;
  GRANT FLASHBACK ON "SLS"."SLS$INCT$PRF" TO PUBLIC;
