--------------------------------------------------------
--  DDL for Table SLS$CCP$SRC
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$CCP$SRC" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"DOC_ID_SRC" VARCHAR2(40 BYTE), 
	"DOC_ID_SRC_DT" DATE, 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"SRC_TYPE" NUMBER(10,0), 
	"SRC_DISP_ID" VARCHAR2(40 BYTE), 
	"EO_ID" NUMBER(20,0), 
	"PRCS_FLG" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"INV_ADJT_AMT" NUMBER
   ) ;

   COMMENT ON COLUMN "SLS"."SLS$CCP$SRC"."EO_ID" IS 'to store customer for invoice.';
  GRANT ALTER ON "SLS"."SLS$CCP$SRC" TO PUBLIC;
  GRANT DELETE ON "SLS"."SLS$CCP$SRC" TO PUBLIC;
  GRANT INDEX ON "SLS"."SLS$CCP$SRC" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$CCP$SRC" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$CCP$SRC" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$CCP$SRC" TO PUBLIC;
  GRANT REFERENCES ON "SLS"."SLS$CCP$SRC" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$CCP$SRC" TO PUBLIC;
  GRANT QUERY REWRITE ON "SLS"."SLS$CCP$SRC" TO PUBLIC;
  GRANT DEBUG ON "SLS"."SLS$CCP$SRC" TO PUBLIC;
  GRANT FLASHBACK ON "SLS"."SLS$CCP$SRC" TO PUBLIC;
