--------------------------------------------------------
--  DDL for Table SLS$EXPNS$INVC$DTL
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$EXPNS$INVC$DTL" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"DOC_ID_SRC" VARCHAR2(40 BYTE), 
	"DLV_SCHDL_NO" NUMBER(4,0), 
	"WH_ID" VARCHAR2(20 BYTE), 
	"ITM_ID" VARCHAR2(50 BYTE), 
	"ITM_SR_NO" NUMBER(10,0), 
	"EXP_COA_ID" NUMBER(10,0), 
	"EXP_AMT_SP" NUMBER(26,6), 
	"EXP_AMT_BS" NUMBER(26,6), 
	"TAX_AMT_SP" NUMBER(26,6), 
	"TAX_AMT_BS" NUMBER(26,6), 
	"TOT_AMT_SP" NUMBER(26,6), 
	"TOT_AMT_BS" NUMBER(26,6), 
	"TDS_AMT_SP" NUMBER(26,6), 
	"TDS_AMT_BS" NUMBER(26,6), 
	"INCL_FLG" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"ITM_EXP_STAT" NUMBER(4,0)
   ) ;
  GRANT UPDATE ON "SLS"."SLS$EXPNS$INVC$DTL" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$EXPNS$INVC$DTL" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$EXPNS$INVC$DTL" TO PUBLIC;
