--------------------------------------------------------
--  DDL for Table SLS$TRNP$RECONCILE
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$TRNP$RECONCILE" 
   (	"CLD_ID" VARCHAR2(20 BYTE), 
	"SLOC_ID" NUMBER(4,0), 
	"ORG_ID" VARCHAR2(20 BYTE), 
	"HO_ORG_ID" VARCHAR2(20 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"DOC_DT" DATE, 
	"EO_ID" NUMBER(5,0), 
	"DISP_DOC_ID" VARCHAR2(40 BYTE), 
	"FRM_DT" DATE, 
	"TO_DT" DATE, 
	"TRNP_BILL_NO" VARCHAR2(40 BYTE), 
	"TRNP_BILL_DT" DATE, 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"PRJ_ID" VARCHAR2(250 BYTE), 
	"CURR_ID_SP" NUMBER(10,0), 
	"CURR_CONV_FCTR" NUMBER(26,6), 
	"COA_ID" NUMBER(10,0), 
	"DOC_STAT" NUMBER(20,0), 
	"TAX_TYPE" NUMBER(10,0), 
	"PNT_OF_SPLY" VARCHAR2(20 BYTE), 
	"BILL_ADDS" VARCHAR2(20 BYTE), 
	"FY_ID" NUMBER(5,0), 
	"TRNSPRTR_BILL_NO" VARCHAR2(40 BYTE), 
	"TRNSPRTR_BILL_DT" DATE
   ) ;
  GRANT SELECT ON "SLS"."SLS$TRNP$RECONCILE" TO "FIN";
  GRANT UPDATE ON "SLS"."SLS$TRNP$RECONCILE" TO "FIN";
  GRANT SELECT ON "SLS"."SLS$TRNP$RECONCILE" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$TRNP$RECONCILE" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$TRNP$RECONCILE" TO PUBLIC;
