--------------------------------------------------------
--  DDL for Table SLS$SO$ITM
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$SO$ITM" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"ITM_ID" VARCHAR2(50 BYTE), 
	"ITM_RATE" NUMBER(26,6), 
	"ITM_UOM" VARCHAR2(20 BYTE), 
	"ITM_QTY" NUMBER(26,6), 
	"ITM_DISC_TYP" VARCHAR2(1 BYTE), 
	"ITM_DISC_VAL" NUMBER(26,6), 
	"ITM_AMT_BS" NUMBER(26,6), 
	"ITM_AMT_SP" NUMBER(26,6), 
	"REMARKS" VARCHAR2(1000 BYTE), 
	"TLRNC_QTY_TYPE" VARCHAR2(1 BYTE), 
	"TLRNC_QTY_VAL" NUMBER(26,6), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE DEFAULT SYSDATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"TAX_RULE_FLG" VARCHAR2(1 BYTE), 
	"SCH_ID" VARCHAR2(40 BYTE), 
	"PO_DOC_ID" VARCHAR2(40 BYTE), 
	"BAL_QTY" NUMBER(26,6), 
	"ITM_UOM_BS" VARCHAR2(20 BYTE), 
	"UOM_CONV_FCTR" NUMBER(26,6), 
	"ITM_QTY_BS" NUMBER(26,6), 
	"BC_NO" VARCHAR2(100 BYTE), 
	"ITM_AMT_GS_SP" NUMBER(26,6), 
	"ITM_AMT_GS_BS" NUMBER(26,6), 
	"TEMP_AMT_SP" NUMBER(26,6), 
	"ASBL_AMT_BS" NUMBER(26,6), 
	"ASBL_AMT_SP" NUMBER(26,6), 
	"SCHM_FLG" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"WTY_ID" VARCHAR2(20 BYTE), 
	"TMP_BAL_QTY" NUMBER(26,6) DEFAULT 0, 
	"CC_ID" VARCHAR2(45 BYTE), 
	"AMC_FLG" VARCHAR2(1 BYTE), 
	"EO_PART_NO" VARCHAR2(250 BYTE), 
	"ITM_BASIS" NUMBER(5,0), 
	"QC_REQD_FLG" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"QC_OVERRIDE_FLG" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"ITM_SR_NO" NUMBER(10,0) DEFAULT 1, 
	"ITM_SR_NO_SRC" NUMBER(10,0), 
	"ITM_ID_SRC" VARCHAR2(50 BYTE), 
	"STORAGE_TYPE_FLG" NUMBER(5,0), 
	"CNT_QTY" NUMBER(26,6) DEFAULT 0, 
	"ITM_MIN_SEL_RATE" NUMBER(26,6) DEFAULT 0, 
	"PYMNT_TRMS_ID" NUMBER(5,0) DEFAULT 0, 
	"WH_ID" VARCHAR2(20 BYTE), 
	"PHNTM_ITM_ID" VARCHAR2(50 BYTE), 
	"OC_AMT_SP" NUMBER(26,6) DEFAULT 0, 
	"OC_AMT_BS" NUMBER(26,6) DEFAULT 0, 
	"INCL_TX" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"ASSIGNED_TO" NUMBER(10,0), 
	"FRZ_LOT_ATT" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"BAR_CODE_NO" VARCHAR2(40 BYTE), 
	"BAR_CODE_DESC" VARCHAR2(40 BYTE), 
	"PEND_REASON" VARCHAR2(50 BYTE), 
	"COLOR_ATT_GRP_ID" VARCHAR2(20 BYTE), 
	"INNER_PACK" NUMBER(5,0) DEFAULT 0, 
	"OUTER_PACK" NUMBER(5,0) DEFAULT 0, 
	"REMAINING_SPLIT_QTY" NUMBER DEFAULT 0, 
	"BOM_DOC_ID" VARCHAR2(40 BYTE), 
	"BOM_DISP_ID" VARCHAR2(40 BYTE), 
	"COST_PRICE" NUMBER(26,6), 
	"COST_DISC" NUMBER(26,6), 
	"COST_AMT" NUMBER(26,6), 
	"COST_DISC_TYP" VARCHAR2(1 BYTE), 
	"BAL_AMT" NUMBER(26,6), 
	"TEMP_BAL_AMT" NUMBER(26,6), 
	"PROC_OTHR_CHRG" NUMBER(26,6), 
	"OC_TAX_AMT_SP" NUMBER(26,6), 
	"OC_TAX_AMT_BS" NUMBER(26,6), 
	"MULTI_SCHM_FLG" VARCHAR2(1 BYTE) DEFAULT 'N'
   ) ;

   COMMENT ON COLUMN "SLS"."SLS$SO$ITM"."PO_DOC_ID" IS 'THIS IS DRAFT PO NUMBER WHICH HAS GENERATED AT THE TIME OF BACK ORDER';
   COMMENT ON COLUMN "SLS"."SLS$SO$ITM"."BC_NO" IS 'BAR CODE NUMBER';
   COMMENT ON COLUMN "SLS"."SLS$SO$ITM"."SCHM_FLG" IS 'Y-FOR SCHEME APPLICABLE
N-FOR SCHEME NOT APPLICABLE
A-APPLIED SCHEME IN CASE OF AMOUNT FREE';
   COMMENT ON COLUMN "SLS"."SLS$SO$ITM"."QC_REQD_FLG" IS 'Column to check if QC is required or not';
   COMMENT ON COLUMN "SLS"."SLS$SO$ITM"."QC_OVERRIDE_FLG" IS 'Column to check if QC is being overridden or not';
   COMMENT ON COLUMN "SLS"."SLS$SO$ITM"."STORAGE_TYPE_FLG" IS 'To store Storage Flag';
   COMMENT ON COLUMN "SLS"."SLS$SO$ITM"."ITM_MIN_SEL_RATE" IS 'To Store Minimum Selling price of item';
   COMMENT ON COLUMN "SLS"."SLS$SO$ITM"."INCL_TX" IS 'In Case Of Gst Tax Is Inclusive Or Not';
   COMMENT ON COLUMN "SLS"."SLS$SO$ITM"."FRZ_LOT_ATT" IS 'To Freeze Lot Attribute';
  GRANT ALTER ON "SLS"."SLS$SO$ITM" TO "PMS";
  GRANT DELETE ON "SLS"."SLS$SO$ITM" TO "PMS";
  GRANT INDEX ON "SLS"."SLS$SO$ITM" TO "PMS";
  GRANT INSERT ON "SLS"."SLS$SO$ITM" TO "PMS";
  GRANT SELECT ON "SLS"."SLS$SO$ITM" TO "PMS";
  GRANT UPDATE ON "SLS"."SLS$SO$ITM" TO "PMS";
  GRANT REFERENCES ON "SLS"."SLS$SO$ITM" TO "PMS";
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$SO$ITM" TO "PMS";
  GRANT QUERY REWRITE ON "SLS"."SLS$SO$ITM" TO "PMS";
  GRANT DEBUG ON "SLS"."SLS$SO$ITM" TO "PMS";
  GRANT FLASHBACK ON "SLS"."SLS$SO$ITM" TO "PMS";
  GRANT UPDATE ON "SLS"."SLS$SO$ITM" TO "MNF" WITH GRANT OPTION;
  GRANT REFERENCES ON "SLS"."SLS$SO$ITM" TO "MNF" WITH GRANT OPTION;
  GRANT QUERY REWRITE ON "SLS"."SLS$SO$ITM" TO "MNF" WITH GRANT OPTION;
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$SO$ITM" TO "MNF" WITH GRANT OPTION;
  GRANT INSERT ON "SLS"."SLS$SO$ITM" TO "MNF" WITH GRANT OPTION;
  GRANT INDEX ON "SLS"."SLS$SO$ITM" TO "MNF" WITH GRANT OPTION;
  GRANT FLASHBACK ON "SLS"."SLS$SO$ITM" TO "MNF" WITH GRANT OPTION;
  GRANT DELETE ON "SLS"."SLS$SO$ITM" TO "MNF" WITH GRANT OPTION;
  GRANT DEBUG ON "SLS"."SLS$SO$ITM" TO "MNF" WITH GRANT OPTION;
  GRANT ALTER ON "SLS"."SLS$SO$ITM" TO "MNF" WITH GRANT OPTION;
  GRANT FLASHBACK ON "SLS"."SLS$SO$ITM" TO "APP";
  GRANT DELETE ON "SLS"."SLS$SO$ITM" TO "APP";
  GRANT DEBUG ON "SLS"."SLS$SO$ITM" TO "APP";
  GRANT ALTER ON "SLS"."SLS$SO$ITM" TO "APP";
  GRANT UPDATE ON "SLS"."SLS$SO$ITM" TO "MM";
  GRANT SELECT ON "SLS"."SLS$SO$ITM" TO "SVC";
  GRANT FLASHBACK ON "SLS"."SLS$SO$ITM" TO PUBLIC;
  GRANT DEBUG ON "SLS"."SLS$SO$ITM" TO PUBLIC;
  GRANT QUERY REWRITE ON "SLS"."SLS$SO$ITM" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$SO$ITM" TO PUBLIC;
  GRANT REFERENCES ON "SLS"."SLS$SO$ITM" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$SO$ITM" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$SO$ITM" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$SO$ITM" TO PUBLIC;
  GRANT INDEX ON "SLS"."SLS$SO$ITM" TO PUBLIC;
  GRANT DELETE ON "SLS"."SLS$SO$ITM" TO PUBLIC;
  GRANT ALTER ON "SLS"."SLS$SO$ITM" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$SO$ITM" TO "MNF" WITH GRANT OPTION;
  GRANT SELECT ON "SLS"."SLS$SO$ITM" TO "MM";
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$SO$ITM" TO "MM";
  GRANT REFERENCES ON "SLS"."SLS$SO$ITM" TO "MM";
  GRANT QUERY REWRITE ON "SLS"."SLS$SO$ITM" TO "MM";
  GRANT INSERT ON "SLS"."SLS$SO$ITM" TO "MM";
  GRANT INDEX ON "SLS"."SLS$SO$ITM" TO "MM";
  GRANT FLASHBACK ON "SLS"."SLS$SO$ITM" TO "MM";
  GRANT DELETE ON "SLS"."SLS$SO$ITM" TO "MM";
  GRANT DEBUG ON "SLS"."SLS$SO$ITM" TO "MM";
  GRANT ALTER ON "SLS"."SLS$SO$ITM" TO "MM";
  GRANT UPDATE ON "SLS"."SLS$SO$ITM" TO "APP";
  GRANT SELECT ON "SLS"."SLS$SO$ITM" TO "APP";
  GRANT REFERENCES ON "SLS"."SLS$SO$ITM" TO "APP";
  GRANT INSERT ON "SLS"."SLS$SO$ITM" TO "APP";
  GRANT INDEX ON "SLS"."SLS$SO$ITM" TO "APP";
  GRANT QUERY REWRITE ON "SLS"."SLS$SO$ITM" TO "APP";
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$SO$ITM" TO "APP";
