--------------------------------------------------------
--  DDL for Table SLS$QUOT
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$QUOT" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"DOC_DT" DATE, 
	"EO_CATG" NUMBER(10,0), 
	"EO_ID" NUMBER(20,0), 
	"ENQ_ID" VARCHAR2(40 BYTE), 
	"QUOT_STAT" NUMBER(10,0), 
	"DISC_TYPE" VARCHAR2(1 BYTE), 
	"DISC_VAL" NUMBER(26,6), 
	"VALID_TO_DT" DATE, 
	"EXP_DEL_DT" DATE, 
	"QUOT_PRNT_FLG" VARCHAR2(1 BYTE) DEFAULT 'Y', 
	"QUOT_MAIL_FLG" VARCHAR2(1 BYTE) DEFAULT 'Y', 
	"TAX_RULE_FLG" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"QUOT_AMT_SP" NUMBER(26,6), 
	"QUOT_AMT_BS" NUMBER(26,6), 
	"PAY_MODE" NUMBER(20,0), 
	"CURR_ID_SP" NUMBER(10,0), 
	"CURR_CONV_FCTR" NUMBER(26,6), 
	"CURR_ID_BS" NUMBER(10,0), 
	"AMD_NO" VARCHAR2(40 BYTE), 
	"AMD_DT" DATE, 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"QUOT_ID" VARCHAR2(20 BYTE), 
	"TAX_AFTER_DISC_FLG" VARCHAR2(1 BYTE), 
	"QUOT_BASIS" VARCHAR2(1 BYTE), 
	"FY_ID" NUMBER(5,0), 
	"QUOT_MODE" NUMBER(10,0), 
	"ASSIGNED_TO" NUMBER(10,0), 
	"EO_PRICE_PLC" VARCHAR2(20 BYTE), 
	"REMARKS" VARCHAR2(1000 BYTE), 
	"QUOT_AMT_GS_SP" NUMBER(26,6), 
	"QUOT_AMT_GS_BS" NUMBER(26,6), 
	"TAX_FORM_TYP_ID" NUMBER(20,0), 
	"EXPCTD_ORD_CONFRM_DT" DATE, 
	"CRS_SLS_EXECTIV" NUMBER(10,0), 
	"QUOT_TYPE" NUMBER(10,0) DEFAULT 1056, 
	"DOC_ID_SRC" VARCHAR2(40 BYTE), 
	"CASH_CUST_NM" VARCHAR2(50 BYTE), 
	"CASH_CUST_ADDRS" VARCHAR2(500 BYTE), 
	"BUSNES_PATNR_ID" NUMBER(20,0), 
	"TAX_TYPE" NUMBER(10,0) DEFAULT 1154, 
	"PNT_OF_SPLY" VARCHAR2(20 BYTE), 
	"BILL_ADDS" VARCHAR2(20 BYTE), 
	"MULTI_SHCM_ID" VARCHAR2(40 BYTE), 
	"CASH_CUST_EMAIL_ID" VARCHAR2(100 BYTE), 
	"CASH_CUST_VAT_NO" VARCHAR2(100 BYTE), 
	"CASH_CUST_MOB_NO" VARCHAR2(100 BYTE), 
	"EO_REF_UID" VARCHAR2(50 BYTE), 
	"EO_REF_VAT_NO" VARCHAR2(50 BYTE), 
	"EO_REF_MOB_NO" NUMBER(26,0), 
	"EO_REF_EMAIL_ID" VARCHAR2(100 BYTE), 
	"PRJ_ID" VARCHAR2(40 BYTE), 
	"DLV_TYPE" NUMBER(5,0), 
	"PORT_ID" VARCHAR2(50 BYTE), 
	"EXT_DOC_NO" VARCHAR2(20 BYTE), 
	"EXT_DOC_DATE" DATE, 
	"EXEC_ID" NUMBER(5,0), 
	"CNCL_RSN" VARCHAR2(255 BYTE), 
	"WLK_IN_ATTN" VARCHAR2(1000 BYTE), 
	"EST_TYPE" NUMBER(5,0), 
	"PORT_OF_LANDING" VARCHAR2(20 BYTE), 
	"PORT_OF_DISCHRG" VARCHAR2(20 BYTE), 
	"NOTIFY" NUMBER(20,0), 
	"PLC_OF_DLV" VARCHAR2(250 BYTE), 
	"FINAL_DEST" VARCHAR2(250 BYTE), 
	"QUOT_TYP" NUMBER(10,0), 
	"SUP_ID" VARCHAR2(1000 BYTE)
   ) ;

   COMMENT ON COLUMN "SLS"."SLS$QUOT"."ASSIGNED_TO" IS 'TO SAVE SALES REPRESENTATIVE';
   COMMENT ON COLUMN "SLS"."SLS$QUOT"."CRS_SLS_EXECTIV" IS 'To Store Cross Sales Executive EO ID';
   COMMENT ON COLUMN "SLS"."SLS$QUOT"."QUOT_TYPE" IS 'Direct Quotation Type: Manual or Copy Previous Quotation.';
   COMMENT ON COLUMN "SLS"."SLS$QUOT"."DOC_ID_SRC" IS 'Previous Quotation Id.';
   COMMENT ON COLUMN "SLS"."SLS$QUOT"."CASH_CUST_NM" IS 'To Store Cash Customer Name';
   COMMENT ON COLUMN "SLS"."SLS$QUOT"."CASH_CUST_ADDRS" IS 'To Store Cash Customer Address';
   COMMENT ON COLUMN "SLS"."SLS$QUOT"."BUSNES_PATNR_ID" IS 'Business Partner EO ID';
   COMMENT ON COLUMN "SLS"."SLS$QUOT"."TAX_TYPE" IS 'To store which type of Tax will be applicable on the Sales order. i.e. GST or Legacy Tax. "1153" :GST | "1154" : Legacy tax System ';
   COMMENT ON COLUMN "SLS"."SLS$QUOT"."PNT_OF_SPLY" IS 'To store the value of point of supply for GST Calculation';
   COMMENT ON COLUMN "SLS"."SLS$QUOT"."BILL_ADDS" IS 'Storing Billing address for  customer';
   COMMENT ON COLUMN "SLS"."SLS$QUOT"."MULTI_SHCM_ID" IS 'STORE MULTI SCHEME ID WHEN APPLIED IN AN ORDER';
   COMMENT ON COLUMN "SLS"."SLS$QUOT"."CNCL_RSN" IS 'To store Quotation Cancellation Reason';
  GRANT FLASHBACK ON "SLS"."SLS$QUOT" TO PUBLIC;
  GRANT DEBUG ON "SLS"."SLS$QUOT" TO PUBLIC;
  GRANT QUERY REWRITE ON "SLS"."SLS$QUOT" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$QUOT" TO PUBLIC;
  GRANT REFERENCES ON "SLS"."SLS$QUOT" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$QUOT" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$QUOT" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$QUOT" TO PUBLIC;
  GRANT INDEX ON "SLS"."SLS$QUOT" TO PUBLIC;
  GRANT DELETE ON "SLS"."SLS$QUOT" TO PUBLIC;
  GRANT ALTER ON "SLS"."SLS$QUOT" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$QUOT" TO "APP";
  GRANT SELECT ON "SLS"."SLS$QUOT" TO "APP";
  GRANT REFERENCES ON "SLS"."SLS$QUOT" TO "APP";
  GRANT QUERY REWRITE ON "SLS"."SLS$QUOT" TO "APP";
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$QUOT" TO "APP";
  GRANT INSERT ON "SLS"."SLS$QUOT" TO "APP";
  GRANT ALTER ON "SLS"."SLS$QUOT" TO "MNF" WITH GRANT OPTION;
  GRANT DELETE ON "SLS"."SLS$QUOT" TO "MNF" WITH GRANT OPTION;
  GRANT INDEX ON "SLS"."SLS$QUOT" TO "APP";
  GRANT FLASHBACK ON "SLS"."SLS$QUOT" TO "APP";
  GRANT INDEX ON "SLS"."SLS$QUOT" TO "MNF" WITH GRANT OPTION;
  GRANT INSERT ON "SLS"."SLS$QUOT" TO "MNF" WITH GRANT OPTION;
  GRANT SELECT ON "SLS"."SLS$QUOT" TO "MNF" WITH GRANT OPTION;
  GRANT UPDATE ON "SLS"."SLS$QUOT" TO "MNF" WITH GRANT OPTION;
  GRANT REFERENCES ON "SLS"."SLS$QUOT" TO "MNF" WITH GRANT OPTION;
  GRANT DEBUG ON "SLS"."SLS$QUOT" TO "MNF";
  GRANT FLASHBACK ON "SLS"."SLS$QUOT" TO "MNF";
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$QUOT" TO "MNF";
  GRANT QUERY REWRITE ON "SLS"."SLS$QUOT" TO "MNF";
  GRANT DELETE ON "SLS"."SLS$QUOT" TO "APP";
  GRANT DEBUG ON "SLS"."SLS$QUOT" TO "APP";
  GRANT ALTER ON "SLS"."SLS$QUOT" TO "APP";
