--------------------------------------------------------
--  DDL for Table SLS$SRF
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$SRF" 
   (	"CLD_ID" VARCHAR2(20 BYTE), 
	"SLOC_ID" NUMBER(4,0), 
	"ORG_ID" VARCHAR2(20 BYTE), 
	"HO_ORG_ID" VARCHAR2(20 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"DOC_DT" DATE, 
	"DOC_ID_SRC" VARCHAR2(40 BYTE), 
	"SRF_ID" VARCHAR2(20 BYTE), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"CNTRY_ID" NUMBER(5,0), 
	"DRFT_SRF_ID" VARCHAR2(20 BYTE), 
	"FY_ID" NUMBER(4,0), 
	"EO_ID" NUMBER(22,0), 
	"EO_CAT" NUMBER(10,0), 
	"CURR_ID_SP" NUMBER(10,0), 
	"CURR_ID_BS" NUMBER(10,0), 
	"CURR_RATE" NUMBER(26,6), 
	"TOT_SAMPLE" NUMBER(26,6), 
	"DISPATCH_MODE" NUMBER(5,0), 
	"SRF_STAT" NUMBER(5,0), 
	"AUTH_STAT" VARCHAR2(1 BYTE), 
	"PRJ_ID" VARCHAR2(40 BYTE), 
	"REF_DOC_ID" VARCHAR2(50 BYTE), 
	"AMND_NO" NUMBER(5,0), 
	"EXW_DT" DATE
   ) ;
  GRANT INSERT ON "SLS"."SLS$SRF" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$SRF" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$SRF" TO PUBLIC;
