--------------------------------------------------------
--  DDL for Table SLS$CATG$DISC
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$CATG$DISC" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"CATG_ID" NUMBER(20,0), 
	"DISC_NO" VARCHAR2(20 BYTE), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE DEFAULT SYSDATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"FY_ID" NUMBER(5,0), 
	"EFFECTIVE_DT" DATE
   ) ;
  GRANT FLASHBACK ON "SLS"."SLS$CATG$DISC" TO PUBLIC;
  GRANT DEBUG ON "SLS"."SLS$CATG$DISC" TO PUBLIC;
  GRANT QUERY REWRITE ON "SLS"."SLS$CATG$DISC" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$CATG$DISC" TO PUBLIC;
  GRANT REFERENCES ON "SLS"."SLS$CATG$DISC" TO PUBLIC;
  GRANT INDEX ON "SLS"."SLS$CATG$DISC" TO PUBLIC;
  GRANT DELETE ON "SLS"."SLS$CATG$DISC" TO PUBLIC;
  GRANT ALTER ON "SLS"."SLS$CATG$DISC" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$CATG$DISC" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$CATG$DISC" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$CATG$DISC" TO PUBLIC;
