--------------------------------------------------------
--  DDL for Table SLS$SO$ITM$UPLOAD
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$SO$ITM$UPLOAD" 
   (	"ITEM_ID" VARCHAR2(40 BYTE), 
	"ITM_RATE" NUMBER(26,6), 
	"ITM_QTY" NUMBER(26,6), 
	"TLRNC_QTY_TYPE" VARCHAR2(1 BYTE), 
	"TLRNC_QTY_VAL" NUMBER(26,6), 
	"ITM_DISC_TYP" VARCHAR2(1 BYTE), 
	"ITM_DISC_VAL" NUMBER(26,6), 
	"ITEM_UOM" VARCHAR2(20 BYTE), 
	"ITM_AMT_SP" NUMBER(26,6), 
	"ITM_AMT_BS" NUMBER(26,6), 
	"ASBL_AMT_SP" NUMBER(26,6), 
	"ITM_BASIS" NUMBER(5,0), 
	"FETCH_ITM_PRICE" VARCHAR2(1 BYTE), 
	"ITEM_DESC" VARCHAR2(100 BYTE), 
	"SUCCSES_FLG" VARCHAR2(1 BYTE), 
	"CLD_ID" VARCHAR2(4 BYTE) DEFAULT '0000', 
	"SLOC_ID" NUMBER(2,0) DEFAULT 1, 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"ATT_GRP_ID" VARCHAR2(40 BYTE), 
	"COST_DISC" NUMBER(26,6), 
	"COST_AMT" NUMBER(26,6), 
	"COST_PRICE" NUMBER(26,6)
   ) ;
  GRANT INSERT ON "SLS"."SLS$SO$ITM$UPLOAD" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$SO$ITM$UPLOAD" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$SO$ITM$UPLOAD" TO PUBLIC;
