--------------------------------------------------------
--  DDL for Table SLS$TRNP$TYR$PRF
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$TRNP$TYR$PRF" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"DOC_DT" DATE, 
	"DOC_SRC_TYPE" NUMBER(5,0), 
	"DOC_ID_SRC" VARCHAR2(40 BYTE), 
	"EO_ID" NUMBER(5,0), 
	"TYRE_NO" VARCHAR2(20 BYTE), 
	"DOC_SRC_DT" DATE, 
	"DOC_STAT" NUMBER(5,0), 
	"REMARKS" VARCHAR2(100 BYTE), 
	"USR_ID_CREATE" NUMBER(5,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(5,0), 
	"USR_ID_MOD_DT" DATE
   ) ;
  GRANT INSERT ON "SLS"."SLS$TRNP$TYR$PRF" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$TRNP$TYR$PRF" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$TRNP$TYR$PRF" TO PUBLIC;
