--------------------------------------------------------
--  DDL for Table SLS$SRF$ITM$DTL
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$SRF$ITM$DTL" 
   (	"CLD_ID" VARCHAR2(20 BYTE), 
	"SLOC_ID" NUMBER(4,0), 
	"ORG_ID" VARCHAR2(20 BYTE), 
	"HO_ORG_ID" VARCHAR2(20 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"ITM_ID" VARCHAR2(40 BYTE), 
	"ITM_UOM" VARCHAR2(20 BYTE), 
	"ITM_SR_NO" NUMBER(4,0), 
	"ATT_ID" VARCHAR2(20 BYTE), 
	"ATT_VAL" VARCHAR2(100 BYTE), 
	"ITM_RMRKS" VARCHAR2(4000 BYTE), 
	"ATT_TYPE_ID" VARCHAR2(20 BYTE), 
	"ITM_QTY" NUMBER(26,6), 
	"CNTR_QTY" NUMBER(26,6)
   ) ;
  GRANT INSERT ON "SLS"."SLS$SRF$ITM$DTL" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$SRF$ITM$DTL" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$SRF$ITM$DTL" TO PUBLIC;
