--------------------------------------------------------
--  DDL for Table SLS$COURIER$PLCY$DTL
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$COURIER$PLCY$DTL" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"SL_NO" NUMBER(20,0), 
	"WEIGHT_FROM_AMT" NUMBER(26,6), 
	"WEIGHT_TO_AMT" NUMBER(26,6), 
	"MIN_CHARGE" NUMBER(26,6), 
	"BASE_CHARGE" NUMBER(26,6), 
	"LOC_ID" VARCHAR2(20 BYTE), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"PIN_CODE" NUMBER(26,6), 
	"STATE_ID" VARCHAR2(50 BYTE), 
	"CITY_ID" VARCHAR2(50 BYTE), 
	"ZONE_NM" VARCHAR2(50 BYTE), 
	"COURIER_NM" VARCHAR2(50 BYTE), 
	"COURIER_MODE" NUMBER(10,0), 
	"RATE_IN_KG" NUMBER(26,6), 
	"MINIMUM_AMT" NUMBER(26,6), 
	"COD" VARCHAR2(1 BYTE), 
	"COD_CHARGES" NUMBER(26,6), 
	"OTHER_CHARGES" NUMBER(26,6), 
	"FUEL_SC" NUMBER(26,6), 
	"FOV_PER_VAL" NUMBER(26,6), 
	"FOV_MIN_VAL" NUMBER(26,6), 
	"DOCUMENTS" NUMBER(10,0), 
	"COUR_PLCY_TYP" VARCHAR2(50 BYTE), 
	"COURIER_NM_ID" NUMBER(20,0)
   ) ;
