--------------------------------------------------------
--  DDL for Table SLS$INCT$EO$DTL
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$INCT$EO$DTL" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"FREQ_BASIS" NUMBER(20,0), 
	"EO_ID" NUMBER(20,0), 
	"INCT_AMT_SP" NUMBER(26,6), 
	"INCT_AMT_BS" NUMBER(26,6), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"INCT_BONS_AMT" NUMBER(26,6) DEFAULT 0, 
	"INCT_QTY_SP" NUMBER(26,6), 
	"INCT_QTY_BS" NUMBER(26,6)
   ) ;

   COMMENT ON COLUMN "SLS"."SLS$INCT$EO$DTL"."FREQ_BASIS" IS '1 - DAILY, 2- WEEKLY, 3- QUARTERLY, 4- HALFYEARLY, 5- MONTHLY';
  GRANT INSERT ON "SLS"."SLS$INCT$EO$DTL" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$INCT$EO$DTL" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$INCT$EO$DTL" TO PUBLIC;
