--------------------------------------------------------
--  DDL for Table SLS$SHIPMNT$ITM
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$SHIPMNT$ITM" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"DOC_DT" DATE, 
	"PACK_NO" VARCHAR2(250 BYTE), 
	"WH_ID" VARCHAR2(20 BYTE), 
	"SHIPMNT_QTY" NUMBER(26,6), 
	"ITM_UOM" VARCHAR2(20 BYTE), 
	"PICK_QTY" NUMBER(26,6), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"ITM_PRICE" NUMBER(26,6), 
	"ITM_AMT_SP" NUMBER(26,6), 
	"ITM_ID" VARCHAR2(50 BYTE), 
	"SO_ID" VARCHAR2(40 BYTE), 
	"PICK_ID" VARCHAR2(40 BYTE), 
	"ITM_AMT_BS" NUMBER(26,6), 
	"ITM_UOM_BS" VARCHAR2(20 BYTE), 
	"UOM_CONV_FCTR" NUMBER(26,6), 
	"ITM_QTY_BS" NUMBER(26,6), 
	"BAL_QTY" NUMBER(26,6), 
	"TMP_BAL_QTY" NUMBER(26,6), 
	"ITM_DISC_TYP" VARCHAR2(1 BYTE), 
	"ITM_DISC_VAL" NUMBER(26,6), 
	"ITM_AMT_GS_SP" NUMBER(26,6), 
	"ITM_AMT_GS_BS" NUMBER(26,6), 
	"ASBL_AMT_BS" NUMBER(26,6), 
	"ASBL_AMT_SP" NUMBER(26,6), 
	"CC_ID" VARCHAR2(40 BYTE), 
	"PRJ_ID" VARCHAR2(40 BYTE) DEFAULT 'PROJ0000', 
	"SS_BAL_QTY" NUMBER(26,6) DEFAULT 0, 
	"ITM_SR_NO" NUMBER(10,0) DEFAULT 1, 
	"CNT_QTY" NUMBER(26,6) DEFAULT 0, 
	"BAR_CODE_NO" VARCHAR2(40 BYTE), 
	"BAR_CODE_DESC" VARCHAR2(40 BYTE), 
	"REMARKS" VARCHAR2(250 BYTE)
   ) ;

   COMMENT ON COLUMN "SLS"."SLS$SHIPMNT$ITM"."BAL_QTY" IS 'TO UPDATE BAL_QTY AFTER MAKING INTIMATION SLIP';
   COMMENT ON COLUMN "SLS"."SLS$SHIPMNT$ITM"."SS_BAL_QTY" IS 'Column to Store remaining balance after Secondary sales calculation.';
  GRANT SELECT ON "SLS"."SLS$SHIPMNT$ITM" TO "APP";
  GRANT ALTER ON "SLS"."SLS$SHIPMNT$ITM" TO "MNF" WITH GRANT OPTION;
  GRANT DEBUG ON "SLS"."SLS$SHIPMNT$ITM" TO "MNF" WITH GRANT OPTION;
  GRANT DELETE ON "SLS"."SLS$SHIPMNT$ITM" TO "MNF" WITH GRANT OPTION;
  GRANT FLASHBACK ON "SLS"."SLS$SHIPMNT$ITM" TO "MNF" WITH GRANT OPTION;
  GRANT INDEX ON "SLS"."SLS$SHIPMNT$ITM" TO "MNF" WITH GRANT OPTION;
  GRANT INSERT ON "SLS"."SLS$SHIPMNT$ITM" TO "MNF" WITH GRANT OPTION;
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$SHIPMNT$ITM" TO "MNF" WITH GRANT OPTION;
  GRANT QUERY REWRITE ON "SLS"."SLS$SHIPMNT$ITM" TO "MNF" WITH GRANT OPTION;
  GRANT REFERENCES ON "SLS"."SLS$SHIPMNT$ITM" TO "MNF" WITH GRANT OPTION;
  GRANT SELECT ON "SLS"."SLS$SHIPMNT$ITM" TO "MNF" WITH GRANT OPTION;
  GRANT UPDATE ON "SLS"."SLS$SHIPMNT$ITM" TO "MNF" WITH GRANT OPTION;
  GRANT FLASHBACK ON "SLS"."SLS$SHIPMNT$ITM" TO "FIN";
  GRANT DEBUG ON "SLS"."SLS$SHIPMNT$ITM" TO "FIN";
  GRANT QUERY REWRITE ON "SLS"."SLS$SHIPMNT$ITM" TO "FIN";
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$SHIPMNT$ITM" TO "FIN";
  GRANT REFERENCES ON "SLS"."SLS$SHIPMNT$ITM" TO "FIN";
  GRANT UPDATE ON "SLS"."SLS$SHIPMNT$ITM" TO "FIN";
  GRANT SELECT ON "SLS"."SLS$SHIPMNT$ITM" TO "FIN";
  GRANT INSERT ON "SLS"."SLS$SHIPMNT$ITM" TO "FIN";
  GRANT INDEX ON "SLS"."SLS$SHIPMNT$ITM" TO "FIN";
  GRANT DELETE ON "SLS"."SLS$SHIPMNT$ITM" TO "FIN";
  GRANT ALTER ON "SLS"."SLS$SHIPMNT$ITM" TO "FIN";
  GRANT FLASHBACK ON "SLS"."SLS$SHIPMNT$ITM" TO PUBLIC;
  GRANT DEBUG ON "SLS"."SLS$SHIPMNT$ITM" TO PUBLIC;
  GRANT QUERY REWRITE ON "SLS"."SLS$SHIPMNT$ITM" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$SHIPMNT$ITM" TO PUBLIC;
  GRANT REFERENCES ON "SLS"."SLS$SHIPMNT$ITM" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$SHIPMNT$ITM" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$SHIPMNT$ITM" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$SHIPMNT$ITM" TO PUBLIC;
  GRANT INDEX ON "SLS"."SLS$SHIPMNT$ITM" TO PUBLIC;
  GRANT DELETE ON "SLS"."SLS$SHIPMNT$ITM" TO PUBLIC;
  GRANT ALTER ON "SLS"."SLS$SHIPMNT$ITM" TO PUBLIC;
  GRANT ALTER ON "SLS"."SLS$SHIPMNT$ITM" TO "MM";
  GRANT DEBUG ON "SLS"."SLS$SHIPMNT$ITM" TO "MM";
  GRANT DELETE ON "SLS"."SLS$SHIPMNT$ITM" TO "MM";
  GRANT FLASHBACK ON "SLS"."SLS$SHIPMNT$ITM" TO "MM";
  GRANT INDEX ON "SLS"."SLS$SHIPMNT$ITM" TO "MM";
  GRANT INSERT ON "SLS"."SLS$SHIPMNT$ITM" TO "MM";
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$SHIPMNT$ITM" TO "MM";
  GRANT QUERY REWRITE ON "SLS"."SLS$SHIPMNT$ITM" TO "MM";
  GRANT ALTER ON "SLS"."SLS$SHIPMNT$ITM" TO "PMS";
  GRANT DELETE ON "SLS"."SLS$SHIPMNT$ITM" TO "PMS";
  GRANT INDEX ON "SLS"."SLS$SHIPMNT$ITM" TO "PMS";
  GRANT INSERT ON "SLS"."SLS$SHIPMNT$ITM" TO "PMS";
  GRANT SELECT ON "SLS"."SLS$SHIPMNT$ITM" TO "PMS";
  GRANT UPDATE ON "SLS"."SLS$SHIPMNT$ITM" TO "PMS";
  GRANT REFERENCES ON "SLS"."SLS$SHIPMNT$ITM" TO "PMS";
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$SHIPMNT$ITM" TO "PMS";
  GRANT QUERY REWRITE ON "SLS"."SLS$SHIPMNT$ITM" TO "PMS";
  GRANT DEBUG ON "SLS"."SLS$SHIPMNT$ITM" TO "PMS";
  GRANT FLASHBACK ON "SLS"."SLS$SHIPMNT$ITM" TO "PMS";
  GRANT REFERENCES ON "SLS"."SLS$SHIPMNT$ITM" TO "MM";
  GRANT SELECT ON "SLS"."SLS$SHIPMNT$ITM" TO "MM";
  GRANT UPDATE ON "SLS"."SLS$SHIPMNT$ITM" TO "MM";
