--------------------------------------------------------
--  DDL for Table SLS$COM$QUOT$OC$AMD
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$COM$QUOT$OC$AMD" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"AMD_NO" VARCHAR2(40 BYTE), 
	"AMD_DT" DATE, 
	"COA_ID" NUMBER(20,0), 
	"OC_DESC" VARCHAR2(40 BYTE), 
	"CURR_ID" NUMBER(10,0), 
	"CURR_RATE" NUMBER(10,0), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"TRAN_TYPE" VARCHAR2(2 BYTE), 
	"OC_ID" VARCHAR2(20 BYTE), 
	"OC_CALCON" NUMBER(26,6), 
	"OC_CALC_TYPE" VARCHAR2(1 BYTE) DEFAULT 'A', 
	"OC_ADD_SUB" VARCHAR2(1 BYTE) DEFAULT 'A', 
	"OC_CALC_VAL" NUMBER(26,6), 
	"OC_SUMM" NUMBER(26,6), 
	"OC_SUMM_FLAG" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"AMT_SP" NUMBER(26,6) DEFAULT 0, 
	"AMT_BS" NUMBER(26,6) DEFAULT 0, 
	"OC_CALC_ON_SRC_ID" VARCHAR2(20 BYTE), 
	"SUP_PAID" VARCHAR2(1 BYTE)
   ) ;

   COMMENT ON COLUMN "SLS"."SLS$COM$QUOT$OC$AMD"."SUP_PAID" IS 'To store is OC paid by supplier';
  GRANT UPDATE ON "SLS"."SLS$COM$QUOT$OC$AMD" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$COM$QUOT$OC$AMD" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$COM$QUOT$OC$AMD" TO PUBLIC;
