--------------------------------------------------------
--  DDL for Table SLS$SO$ITM$LOT$ATTR$AMD
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$SO$ITM$LOT$ATTR$AMD" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"AMD_NO" VARCHAR2(40 BYTE), 
	"AMD_DT" DATE, 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"ITM_ID" VARCHAR2(50 BYTE), 
	"ITM_SR_NO" NUMBER(10,0), 
	"SR_NO" NUMBER(10,0), 
	"GSM" NUMBER(26,6), 
	"WIDTH" NUMBER(26,6), 
	"COLOR" NUMBER(10,0), 
	"ITM_QTY" NUMBER(26,6), 
	"COLOR_NM" VARCHAR2(100 BYTE), 
	"NO_OF_ROLL" NUMBER(26,6), 
	"LENGTH_VAL" NUMBER(26,6), 
	"PART_NO" VARCHAR2(100 BYTE), 
	"ITM_SIZE" VARCHAR2(20 BYTE)
   ) ;
  GRANT INSERT ON "SLS"."SLS$SO$ITM$LOT$ATTR$AMD" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$SO$ITM$LOT$ATTR$AMD" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$SO$ITM$LOT$ATTR$AMD" TO PUBLIC;
