--------------------------------------------------------
--  DDL for Table SLS$TRNP$LO$ROUTE$DTL
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$TRNP$LO$ROUTE$DTL" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"DEPARTURE_PNT" VARCHAR2(20 BYTE), 
	"DEPARTURE_DATE" DATE, 
	"ARRIVAL_PNT" VARCHAR2(20 BYTE), 
	"ARRIVAL_DATE" DATE, 
	"TOT_VAL" NUMBER(26,6), 
	"UOM" VARCHAR2(20 BYTE), 
	"RATE" NUMBER(26,6), 
	"AMT_SP" NUMBER(26,6), 
	"AMT_BS" NUMBER(26,6), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"SL_NO" NUMBER(5,0), 
	"REMARKS" VARCHAR2(200 BYTE)
   ) ;
  GRANT FLASHBACK ON "SLS"."SLS$TRNP$LO$ROUTE$DTL" TO "APP";
  GRANT DEBUG ON "SLS"."SLS$TRNP$LO$ROUTE$DTL" TO "APP";
  GRANT QUERY REWRITE ON "SLS"."SLS$TRNP$LO$ROUTE$DTL" TO "APP";
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$TRNP$LO$ROUTE$DTL" TO "APP";
  GRANT REFERENCES ON "SLS"."SLS$TRNP$LO$ROUTE$DTL" TO "APP";
  GRANT UPDATE ON "SLS"."SLS$TRNP$LO$ROUTE$DTL" TO "APP";
  GRANT SELECT ON "SLS"."SLS$TRNP$LO$ROUTE$DTL" TO "APP";
  GRANT INSERT ON "SLS"."SLS$TRNP$LO$ROUTE$DTL" TO "APP";
  GRANT INDEX ON "SLS"."SLS$TRNP$LO$ROUTE$DTL" TO "APP";
  GRANT DELETE ON "SLS"."SLS$TRNP$LO$ROUTE$DTL" TO "APP";
  GRANT ALTER ON "SLS"."SLS$TRNP$LO$ROUTE$DTL" TO "APP";
  GRANT DEBUG ON "SLS"."SLS$TRNP$LO$ROUTE$DTL" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$TRNP$LO$ROUTE$DTL" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$TRNP$LO$ROUTE$DTL" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$TRNP$LO$ROUTE$DTL" TO PUBLIC;
