--------------------------------------------------------
--  DDL for Table SLS$CCP$EO
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$CCP$EO" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"EO_ID" NUMBER(20,0), 
	"COA_ID" NUMBER(20,0), 
	"ITM_TOT_SCHM_DISC_VAL" NUMBER(26,6), 
	"EO_TOT_DED_VAL" NUMBER(26,6), 
	"CCP_VOU_ID" VARCHAR2(40 BYTE), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"TOT_EO_AMT_SP" NUMBER(26,6), 
	"TOT_EO_AMT_BS" NUMBER(26,6), 
	"TOT_INV_QTY" NUMBER(26,6), 
	"EO_CATG_ID" NUMBER(10,0), 
	"TOT_INV_AMT_SP" NUMBER(26,6), 
	"TOT_INV_AMT_BS" NUMBER(26,6), 
	"GL_VOU_ID" VARCHAR2(40 BYTE)
   ) ;

   COMMENT ON COLUMN "SLS"."SLS$CCP$EO"."TOT_INV_AMT_SP" IS 'Total Invoice Amount Specific';
   COMMENT ON COLUMN "SLS"."SLS$CCP$EO"."TOT_INV_AMT_BS" IS 'Total Invoice Amount Basic';
  GRANT ALTER ON "SLS"."SLS$CCP$EO" TO PUBLIC;
  GRANT DELETE ON "SLS"."SLS$CCP$EO" TO PUBLIC;
  GRANT INDEX ON "SLS"."SLS$CCP$EO" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$CCP$EO" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$CCP$EO" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$CCP$EO" TO PUBLIC;
  GRANT REFERENCES ON "SLS"."SLS$CCP$EO" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$CCP$EO" TO PUBLIC;
  GRANT QUERY REWRITE ON "SLS"."SLS$CCP$EO" TO PUBLIC;
  GRANT DEBUG ON "SLS"."SLS$CCP$EO" TO PUBLIC;
  GRANT FLASHBACK ON "SLS"."SLS$CCP$EO" TO PUBLIC;
