--------------------------------------------------------
--  DDL for Table SLS$DS$ATT$TYPE
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$DS$ATT$TYPE" 
   (	"ATT_TYPE_ID" NUMBER(5,0), 
	"ATT_TYPE_NM" VARCHAR2(50 BYTE), 
	"ATT_TYPE_RESV" VARCHAR2(1 BYTE) DEFAULT 'Y', 
	"ATT_TYPE_ACTV" VARCHAR2(1 BYTE) DEFAULT 'Y', 
	"ATT_TYPE_FROZEN" VARCHAR2(1 BYTE) DEFAULT 'Y', 
	"ATT_TYPE_MREF" VARCHAR2(1 BYTE) DEFAULT 'Y', 
	"ATT_TYPE_VAL_CNT" VARCHAR2(1 BYTE) DEFAULT 'Y'
   ) ;
  GRANT INSERT ON "SLS"."SLS$DS$ATT$TYPE" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$DS$ATT$TYPE" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$DS$ATT$TYPE" TO PUBLIC;
