--------------------------------------------------------
--  DDL for Table SLS$TRNP$FUEL$BILL
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$TRNP$FUEL$BILL" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"BILL_NO" VARCHAR2(20 BYTE), 
	"BILL_DT" DATE, 
	"EO_ID" NUMBER(5,0), 
	"EO_INV_DT" DATE, 
	"REMARKS" VARCHAR2(200 BYTE), 
	"CURR_ID" NUMBER(5,0), 
	"CURR_CONV" NUMBER(26,6), 
	"TOT_AMT_SP" NUMBER(26,6), 
	"TOT_AMT_BS" NUMBER(26,6), 
	"STATUS" NUMBER(5,0), 
	"USR_ID_CREATE" NUMBER(5,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(5,0), 
	"USR_ID_MOD_DT" DATE, 
	"COA_ID" NUMBER, 
	"INV_STRT_DT" DATE, 
	"INV_END_DT" DATE, 
	"FY_ID" NUMBER(10,0)
   ) ;
  GRANT INSERT ON "SLS"."SLS$TRNP$FUEL$BILL" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$TRNP$FUEL$BILL" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$TRNP$FUEL$BILL" TO PUBLIC;
