--------------------------------------------------------
--  DDL for Table SLS$QUOT$ITM$SCHM_MAINTEMP
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$QUOT$ITM$SCHM_MAINTEMP" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"SR_NO" NUMBER(5,0), 
	"SCHM_ID" VARCHAR2(40 BYTE), 
	"DEST_ITM_ID" VARCHAR2(50 BYTE), 
	"ITM_ID" VARCHAR2(50 BYTE), 
	"ITM_FREE_QTY" NUMBER(26,6), 
	"ITM_PRICE" NUMBER(26,6), 
	"ITM_VAL" NUMBER(26,6), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE DEFAULT SYSDATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"GRP_ITM_FLG" VARCHAR2(1 BYTE), 
	"ITM_SEL_TYPE" VARCHAR2(1 BYTE), 
	"GRP_ID" VARCHAR2(20 BYTE), 
	"ITM_UOM_BS" VARCHAR2(20 BYTE), 
	"UOM_CONV_FCTR" NUMBER(26,6), 
	"ITM_UOM" VARCHAR2(20 BYTE), 
	"ITM_FREE_QTY_BS" NUMBER(26,6)
   ) ;
  GRANT UPDATE ON "SLS"."SLS$QUOT$ITM$SCHM_MAINTEMP" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$QUOT$ITM$SCHM_MAINTEMP" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$QUOT$ITM$SCHM_MAINTEMP" TO PUBLIC;
  GRANT INDEX ON "SLS"."SLS$QUOT$ITM$SCHM_MAINTEMP" TO PUBLIC;
  GRANT DELETE ON "SLS"."SLS$QUOT$ITM$SCHM_MAINTEMP" TO PUBLIC;
  GRANT ALTER ON "SLS"."SLS$QUOT$ITM$SCHM_MAINTEMP" TO PUBLIC;
  GRANT FLASHBACK ON "SLS"."SLS$QUOT$ITM$SCHM_MAINTEMP" TO PUBLIC;
  GRANT DEBUG ON "SLS"."SLS$QUOT$ITM$SCHM_MAINTEMP" TO PUBLIC;
  GRANT QUERY REWRITE ON "SLS"."SLS$QUOT$ITM$SCHM_MAINTEMP" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$QUOT$ITM$SCHM_MAINTEMP" TO PUBLIC;
  GRANT REFERENCES ON "SLS"."SLS$QUOT$ITM$SCHM_MAINTEMP" TO PUBLIC;
