--------------------------------------------------------
--  DDL for Table SLS$TRNP$PETROL$PRF
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$TRNP$PETROL$PRF" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(4 BYTE), 
	"HO_ORG_ID" VARCHAR2(4 BYTE), 
	"STATION_ID" VARCHAR2(20 BYTE), 
	"STATION_NM" VARCHAR2(50 BYTE), 
	"EO_ID" NUMBER(20,0), 
	"ADDS_ID" VARCHAR2(20 BYTE), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE
   ) ;
  GRANT SELECT ON "SLS"."SLS$TRNP$PETROL$PRF" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$TRNP$PETROL$PRF" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$TRNP$PETROL$PRF" TO PUBLIC;
