--------------------------------------------------------
--  DDL for Table SLS$TRNP$VHCL$SCHDL
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$TRNP$VHCL$SCHDL" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(4 BYTE), 
	"HO_ORG_ID" VARCHAR2(4 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"SCHDL_NO" VARCHAR2(20 BYTE), 
	"SCHDL_DT" TIMESTAMP (6), 
	"ROUTE_DOC_ID" VARCHAR2(40 BYTE), 
	"VHCL_NO" VARCHAR2(40 BYTE), 
	"VHCL_ITM_ID" VARCHAR2(40 BYTE), 
	"STATUS" NUMBER(5,0), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"REQ_STRT_DT" DATE, 
	"REQ_END_DT" DATE, 
	"LR_DOC_ID" VARCHAR2(40 BYTE), 
	"FY_ID" NUMBER(10,0), 
	"LO_GENRTD" VARCHAR2(5 BYTE) DEFAULT 'N', 
	"WEGHT_TOT_WT" NUMBER(26,6), 
	"WEGHT_SLIP_NO" VARCHAR2(40 BYTE), 
	"ORDER_OUT_TIME" DATE, 
	"DRIVER_NM" VARCHAR2(200 BYTE), 
	"DRIVER_EO_ID" NUMBER, 
	"VHCL_CAP_UOM" VARCHAR2(20 BYTE), 
	"CAGE_ID" VARCHAR2(50 BYTE), 
	"VERIFY_STATUS" CHAR(1 BYTE) DEFAULT 'N', 
	"OLD_VHCL_NO" VARCHAR2(40 BYTE)
   ) ;
  GRANT INSERT ON "SLS"."SLS$TRNP$VHCL$SCHDL" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$TRNP$VHCL$SCHDL" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$TRNP$VHCL$SCHDL" TO PUBLIC;
