--------------------------------------------------------
--  DDL for Table SLS$INV
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$INV" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"DOC_DT" DATE, 
	"CURR_ID_SP" NUMBER(20,0), 
	"CURR_RATE" NUMBER(26,6), 
	"INV_TYPE" NUMBER(20,0), 
	"EO_ID" NUMBER(20,0), 
	"INTIM_SLIP_ID" VARCHAR2(40 BYTE), 
	"BILL_ADD" VARCHAR2(20 BYTE), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"TOT_AMT_SP" NUMBER(26,6), 
	"TOT_AMT_BS" NUMBER(26,6), 
	"DISC_TYPE" VARCHAR2(1 BYTE), 
	"DISC_VAL" NUMBER(26,6), 
	"TAX_AFTER_DISC_FLG" VARCHAR2(1 BYTE), 
	"DISP_DOC_ID" VARCHAR2(20 BYTE), 
	"TAX_RULE_FLG" VARCHAR2(1 BYTE), 
	"CURR_ID_BS" NUMBER(20,0), 
	"INV_STAT" NUMBER(10,0), 
	"COA_ID" NUMBER(10,0), 
	"REMARKS" VARCHAR2(1000 BYTE), 
	"FY_ID" NUMBER(5,0), 
	"INV_MODE" NUMBER(10,0), 
	"EXT_DOC_NO" VARCHAR2(100 BYTE), 
	"EXT_DOC_DT" DATE, 
	"CASH_CUST_NM" VARCHAR2(100 BYTE), 
	"SALES_VOU_ID" VARCHAR2(40 BYTE), 
	"REF_DOC_ID" VARCHAR2(40 BYTE), 
	"TOT_ITM_AMT_GS_SP" NUMBER(26,6), 
	"TOT_ITM_AMT_GS_BS" NUMBER(26,6), 
	"INV_SUB_TYPE" NUMBER(10,0), 
	"LC_ID" VARCHAR2(40 BYTE), 
	"PEND_LC_AMT" NUMBER(26,6), 
	"REV_SALES_VOU_ID" VARCHAR2(40 BYTE), 
	"DRFT_INV_ID" VARCHAR2(20 BYTE), 
	"INCL_SRVC_ITM" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"TAX_FORM_TYP_ID" NUMBER(20,0), 
	"PRJ_ID" VARCHAR2(40 BYTE) DEFAULT 'PROJ0000', 
	"SHIP_TO_NM" VARCHAR2(50 BYTE), 
	"SHIP_TO_ADDS" VARCHAR2(250 BYTE), 
	"FORM_RCVD" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"FORM_RCVD_DT" DATE, 
	"FORM_RCVD_RMRK" VARCHAR2(1000 BYTE), 
	"FORM_NO" VARCHAR2(50 BYTE), 
	"FORM_AMT" NUMBER(26,6), 
	"SUPPLI_OPER_TYPE" VARCHAR2(1 BYTE) DEFAULT 'A', 
	"EX_TRD_FLG" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"REASON" VARCHAR2(100 BYTE), 
	"PDR_CALCULATED" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"EXP_VOU_ID" VARCHAR2(40 BYTE), 
	"REV_EXP_VOU_ID" VARCHAR2(40 BYTE), 
	"MAIL_SENT_CHK" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"DIRCT_PRNT_CHK" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"MANUL_REMOV_DT" DATE, 
	"DIRCT_PRNT_CHK_FR_INV_RPT" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"RPRT_PRNT_CNT" NUMBER(26,0) DEFAULT 0, 
	"SEI_CALCULATED" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"BUSNES_PATNR_ID" NUMBER(20,0), 
	"INV_RE_UPDTED" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"AMD_NO" NUMBER(10,0), 
	"AMD_DT" DATE, 
	"TAX_TYPE" NUMBER(22,0) DEFAULT 1154, 
	"REF_SO_ID" VARCHAR2(50 BYTE), 
	"PNT_OF_SPLY" VARCHAR2(20 BYTE), 
	"E_WAY_BILL_NO" VARCHAR2(50 BYTE), 
	"RVRS_CHRG_APLICBL" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"POST_AS_DEBIT_NOTE" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"CUST_LEG_CODE" VARCHAR2(20 BYTE), 
	"PORT_ID" VARCHAR2(50 BYTE), 
	"FRIEGHT" NUMBER(5,0), 
	"CNTRY_ORIG" NUMBER(5,0), 
	"NOTIFY" NUMBER(20,0), 
	"LOAD_PORT" VARCHAR2(50 BYTE), 
	"DISCHRG_PORT" VARCHAR2(50 BYTE), 
	"FINAL_DEST" VARCHAR2(250 BYTE), 
	"CNTRY_FINAL_DEST" NUMBER(5,0), 
	"CRR_ACC_NO" VARCHAR2(20 BYTE), 
	"PLC_OF_DLV" VARCHAR2(250 BYTE), 
	"VESSEL_NO" VARCHAR2(250 BYTE), 
	"LUT_FLG" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"SHIP_SEQ" NUMBER(26,6), 
	"SUBC_DONE" VARCHAR2(1 BYTE) DEFAULT 'Y', 
	"REF_GLBL_DOC_ID" NUMBER(5,0), 
	"MERCHANT_EXPORTER" VARCHAR2(5 BYTE) DEFAULT 'N', 
	"INS_AMT_SP" NUMBER(26,6), 
	"FRGHT_AMT_SP" NUMBER(26,6), 
	"SOFTEX_NO" VARCHAR2(40 BYTE), 
	"POS_PNT_CNT" NUMBER, 
	"DOC_PO_NO" VARCHAR2(40 BYTE), 
	"DOC_REMARKS" VARCHAR2(250 BYTE), 
	"URA_ANTIFAKECODE" VARCHAR2(100 BYTE), 
	"URA_INV_NO" VARCHAR2(100 BYTE), 
	"URA_ISSUED_DT" DATE, 
	"GST_REGN_NO" VARCHAR2(40 BYTE)
   ) ;

   COMMENT ON COLUMN "SLS"."SLS$INV"."EXT_DOC_NO" IS 'To save party bill no';
   COMMENT ON COLUMN "SLS"."SLS$INV"."EXT_DOC_DT" IS 'To save party bill Date';
   COMMENT ON COLUMN "SLS"."SLS$INV"."SALES_VOU_ID" IS 'SALES VOUCHER IF WHICH HAS POSTED IN FINANCE';
   COMMENT ON COLUMN "SLS"."SLS$INV"."EX_TRD_FLG" IS 'Column to store value of trading flag';
   COMMENT ON COLUMN "SLS"."SLS$INV"."MAIL_SENT_CHK" IS 'Column to store value to check mail has been sent for the document or not.';
   COMMENT ON COLUMN "SLS"."SLS$INV"."MANUL_REMOV_DT" IS 'Column to store Time for Item removal, Manualy.';
   COMMENT ON COLUMN "SLS"."SLS$INV"."DIRCT_PRNT_CHK_FR_INV_RPT" IS 'If Invoice detail report is printed directly, then to restrict user from printing again this column is used.';
   COMMENT ON COLUMN "SLS"."SLS$INV"."RPRT_PRNT_CNT" IS 'no. of invoice detail report link clicked and report generated.';
   COMMENT ON COLUMN "SLS"."SLS$INV"."BUSNES_PATNR_ID" IS 'Business Partner EO ID';
   COMMENT ON COLUMN "SLS"."SLS$INV"."INV_RE_UPDTED" IS 'Flag for ammended invoice.';
   COMMENT ON COLUMN "SLS"."SLS$INV"."TAX_TYPE" IS 'To store which type of Tax will be applicable on the Sales Invoice. i.e. GST or Legacy Tax. "1153" : GST | "1154" : Legacy tax System ';
   COMMENT ON COLUMN "SLS"."SLS$INV"."PNT_OF_SPLY" IS 'To store the value of point of supply for GST Calculation';
   COMMENT ON COLUMN "SLS"."SLS$INV"."E_WAY_BILL_NO" IS 'To store E way bill number for GST';
   COMMENT ON COLUMN "SLS"."SLS$INV"."RVRS_CHRG_APLICBL" IS 'Flag storing GST payable under reverse charge';
   COMMENT ON COLUMN "SLS"."SLS$INV"."CUST_LEG_CODE" IS 'customer Legacy code.';
  GRANT FLASHBACK ON "SLS"."SLS$INV" TO "PMS";
  GRANT DEBUG ON "SLS"."SLS$INV" TO "PMS";
  GRANT QUERY REWRITE ON "SLS"."SLS$INV" TO "PMS";
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$INV" TO "PMS";
  GRANT REFERENCES ON "SLS"."SLS$INV" TO "PMS";
  GRANT UPDATE ON "SLS"."SLS$INV" TO "PMS";
  GRANT SELECT ON "SLS"."SLS$INV" TO "PMS";
  GRANT INSERT ON "SLS"."SLS$INV" TO "PMS";
  GRANT INDEX ON "SLS"."SLS$INV" TO "PMS";
  GRANT DELETE ON "SLS"."SLS$INV" TO "PMS";
  GRANT ALTER ON "SLS"."SLS$INV" TO "PMS";
  GRANT UPDATE ON "SLS"."SLS$INV" TO "MM";
  GRANT SELECT ON "SLS"."SLS$INV" TO "MM";
  GRANT REFERENCES ON "SLS"."SLS$INV" TO "MM";
  GRANT QUERY REWRITE ON "SLS"."SLS$INV" TO "MM";
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$INV" TO "MM";
  GRANT INSERT ON "SLS"."SLS$INV" TO "MM";
  GRANT INDEX ON "SLS"."SLS$INV" TO "MM";
  GRANT FLASHBACK ON "SLS"."SLS$INV" TO "MM";
  GRANT DELETE ON "SLS"."SLS$INV" TO "MM";
  GRANT DEBUG ON "SLS"."SLS$INV" TO "MM";
  GRANT ALTER ON "SLS"."SLS$INV" TO "MM";
  GRANT ALTER ON "SLS"."SLS$INV" TO "FIN";
  GRANT DELETE ON "SLS"."SLS$INV" TO "FIN";
  GRANT INDEX ON "SLS"."SLS$INV" TO "FIN";
  GRANT INSERT ON "SLS"."SLS$INV" TO "FIN";
  GRANT SELECT ON "SLS"."SLS$INV" TO "FIN";
  GRANT UPDATE ON "SLS"."SLS$INV" TO "FIN";
  GRANT REFERENCES ON "SLS"."SLS$INV" TO "FIN";
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$INV" TO "FIN";
  GRANT QUERY REWRITE ON "SLS"."SLS$INV" TO "FIN";
  GRANT DEBUG ON "SLS"."SLS$INV" TO "FIN";
  GRANT FLASHBACK ON "SLS"."SLS$INV" TO "FIN";
  GRANT REFERENCES ON "SLS"."SLS$INV" TO "MNF" WITH GRANT OPTION;
  GRANT SELECT ON "SLS"."SLS$INV" TO "MNF" WITH GRANT OPTION;
  GRANT UPDATE ON "SLS"."SLS$INV" TO "MNF" WITH GRANT OPTION;
  GRANT ALTER ON "SLS"."SLS$INV" TO "APP";
  GRANT DEBUG ON "SLS"."SLS$INV" TO "APP";
  GRANT DELETE ON "SLS"."SLS$INV" TO "APP";
  GRANT FLASHBACK ON "SLS"."SLS$INV" TO "APP";
  GRANT INDEX ON "SLS"."SLS$INV" TO "APP";
  GRANT INSERT ON "SLS"."SLS$INV" TO "APP";
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$INV" TO "APP";
  GRANT QUERY REWRITE ON "SLS"."SLS$INV" TO "APP";
  GRANT REFERENCES ON "SLS"."SLS$INV" TO "APP";
  GRANT SELECT ON "SLS"."SLS$INV" TO "APP";
  GRANT UPDATE ON "SLS"."SLS$INV" TO "APP";
  GRANT ALTER ON "SLS"."SLS$INV" TO PUBLIC;
  GRANT DELETE ON "SLS"."SLS$INV" TO PUBLIC;
  GRANT INDEX ON "SLS"."SLS$INV" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$INV" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$INV" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$INV" TO PUBLIC;
  GRANT REFERENCES ON "SLS"."SLS$INV" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$INV" TO PUBLIC;
  GRANT QUERY REWRITE ON "SLS"."SLS$INV" TO PUBLIC;
  GRANT DEBUG ON "SLS"."SLS$INV" TO PUBLIC;
  GRANT FLASHBACK ON "SLS"."SLS$INV" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$INV" TO "SVC";
  GRANT ALTER ON "SLS"."SLS$INV" TO "MNF" WITH GRANT OPTION;
  GRANT DEBUG ON "SLS"."SLS$INV" TO "MNF" WITH GRANT OPTION;
  GRANT DELETE ON "SLS"."SLS$INV" TO "MNF" WITH GRANT OPTION;
  GRANT FLASHBACK ON "SLS"."SLS$INV" TO "MNF" WITH GRANT OPTION;
  GRANT INDEX ON "SLS"."SLS$INV" TO "MNF" WITH GRANT OPTION;
  GRANT INSERT ON "SLS"."SLS$INV" TO "MNF" WITH GRANT OPTION;
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$INV" TO "MNF" WITH GRANT OPTION;
  GRANT QUERY REWRITE ON "SLS"."SLS$INV" TO "MNF" WITH GRANT OPTION;
