--------------------------------------------------------
--  DDL for Table SLS$EXPNS$INVC$TR
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$EXPNS$INVC$TR" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"DOC_ID_SRC" VARCHAR2(40 BYTE), 
	"DLV_SCHDL_NO" NUMBER(5,0), 
	"ITM_ID" VARCHAR2(50 BYTE), 
	"EXP_TYPE" NUMBER(5,0), 
	"EXP_COA_ID" NUMBER(10,0), 
	"TAX_RULE_ID" NUMBER(10,0), 
	"TAX_RULE_FLG" VARCHAR2(1 BYTE), 
	"TAX_EXMPT_FLG" VARCHAR2(1 BYTE), 
	"TAX_AMT" NUMBER(26,6), 
	"TAX_AMT_BS" NUMBER(26,6), 
	"TAXABLE_AMT_SP" NUMBER(26,6), 
	"TAXABLE_AMT_BS" NUMBER(26,6)
   ) ;
  GRANT UPDATE ON "SLS"."SLS$EXPNS$INVC$TR" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$EXPNS$INVC$TR" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$EXPNS$INVC$TR" TO PUBLIC;
