--------------------------------------------------------
--  DDL for Table SLS$SUBC$INV$ITM
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$SUBC$INV$ITM" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"ITM_ID" VARCHAR2(50 BYTE), 
	"ITM_PRICE" NUMBER(26,6), 
	"ITM_UOM" VARCHAR2(20 BYTE), 
	"ITM_QTY" NUMBER(26,6), 
	"ITM_EXP_PRICE" NUMBER(26,6), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"ITM_AMT_BS" NUMBER(26,6), 
	"ITM_AMT_SP" NUMBER(26,6), 
	"ITM_SR_NO" NUMBER(10,0), 
	"UOM_CONV_FCTR" NUMBER(26,6), 
	"ITM_AMT_GS_SP" NUMBER(26,6), 
	"ITM_AMT_GS_BS" NUMBER(26,6), 
	"DOC_ID_SRC" VARCHAR2(40 BYTE), 
	"RENEW_BASIS" NUMBER(5,0), 
	"FIXED_TERM_STRTDT" DATE, 
	"FIXED_TERM_ENDDT" DATE, 
	"RENEW_PRCNT" NUMBER(3,0), 
	"STRT_DT" DATE, 
	"END_DT" DATE, 
	"CONTACT_PERSON_BILL" VARCHAR2(100 BYTE), 
	"CONTACT_PERSON_TECH" VARCHAR2(100 BYTE)
   ) ;
  GRANT SELECT ON "SLS"."SLS$SUBC$INV$ITM" TO "APP";
  GRANT ALTER ON "SLS"."SLS$SUBC$INV$ITM" TO PUBLIC;
  GRANT DELETE ON "SLS"."SLS$SUBC$INV$ITM" TO PUBLIC;
  GRANT INDEX ON "SLS"."SLS$SUBC$INV$ITM" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$SUBC$INV$ITM" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$SUBC$INV$ITM" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$SUBC$INV$ITM" TO PUBLIC;
  GRANT REFERENCES ON "SLS"."SLS$SUBC$INV$ITM" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$SUBC$INV$ITM" TO PUBLIC;
  GRANT QUERY REWRITE ON "SLS"."SLS$SUBC$INV$ITM" TO PUBLIC;
  GRANT DEBUG ON "SLS"."SLS$SUBC$INV$ITM" TO PUBLIC;
  GRANT FLASHBACK ON "SLS"."SLS$SUBC$INV$ITM" TO PUBLIC;
