--------------------------------------------------------
--  DDL for Table SLS$INCT$PROC$DTL$SRC
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$INCT$PROC$DTL$SRC" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"EO_ID" NUMBER(20,0), 
	"TRGT_VLU" NUMBER(26,6), 
	"ACHV_VLU" NUMBER(26,6), 
	"DOC_ID_SRC" VARCHAR2(40 BYTE), 
	"INV_VOU_ID" VARCHAR2(40 BYTE)
   ) ;
  GRANT INSERT ON "SLS"."SLS$INCT$PROC$DTL$SRC" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$INCT$PROC$DTL$SRC" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$INCT$PROC$DTL$SRC" TO PUBLIC;
