--------------------------------------------------------
--  DDL for Table SLS$INCT$PROC$GRP
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$INCT$PROC$GRP" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"FREQ_BASIS" NUMBER(20,0), 
	"GRP_ID" VARCHAR2(20 BYTE), 
	"GRP_AMT_SP" NUMBER(26,6), 
	"GRP_AMT_BS" NUMBER(26,6), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE
   ) ;

   COMMENT ON COLUMN "SLS"."SLS$INCT$PROC$GRP"."FREQ_BASIS" IS '1 - DAILY, 2- WEEKLY, 3- QUARTERLY, 4- HALFYEARLY, 5- MONTHLY';
  GRANT INSERT ON "SLS"."SLS$INCT$PROC$GRP" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$INCT$PROC$GRP" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$INCT$PROC$GRP" TO PUBLIC;
