--------------------------------------------------------
--  DDL for Table SLS$SHIPMNT$HDR
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$SHIPMNT$HDR" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"DOC_DT" DATE, 
	"EO_ID" NUMBER(20,0), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE DEFAULT SYSDATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"SHIPMNT_ID" VARCHAR2(20 BYTE), 
	"CURR_ID_SP" NUMBER(10,0), 
	"CURR_CONV_FCTR" NUMBER(26,6), 
	"WH_ID" VARCHAR2(20 BYTE), 
	"SHIPMNT_STAT" NUMBER(10,0), 
	"COGS_VOU_ID" VARCHAR2(40 BYTE), 
	"TRANSPORTER_ID" NUMBER(20,0), 
	"REMARKS" VARCHAR2(250 BYTE), 
	"TRANS_MODE" NUMBER(5,0), 
	"TRANS_VH_NO" VARCHAR2(50 BYTE), 
	"TRANS_GR_NO" VARCHAR2(50 BYTE), 
	"TRANS_CONTNR_NO" VARCHAR2(50 BYTE), 
	"SHIP_ADDS" VARCHAR2(20 BYTE), 
	"REV_COGS_VOU_ID" VARCHAR2(40 BYTE), 
	"EMP_EO_ID" NUMBER(20,0), 
	"PRJ_ID" VARCHAR2(40 BYTE) DEFAULT 'PROJ0000', 
	"REQ_TYP" VARCHAR2(1 BYTE), 
	"VEHICLE_TYP" NUMBER(20,0), 
	"ROUTE_DOC_ID" VARCHAR2(40 BYTE), 
	"TO_PAY" VARCHAR2(1 BYTE), 
	"FY_ID" NUMBER(10,0), 
	"CURR_ID_BS" NUMBER(10,0), 
	"ITM_PRICE_TYPE" NUMBER(5,0) DEFAULT 937, 
	"DRVR_NM" VARCHAR2(100 BYTE), 
	"DRVR_CNTC" VARCHAR2(100 BYTE), 
	"PORT_OF_LANDING" VARCHAR2(20 BYTE), 
	"PORT_OF_DISCHRG" VARCHAR2(20 BYTE), 
	"GROSS_WT" NUMBER(26,6), 
	"NET_WT" NUMBER(26,6), 
	"EMPTY_WT" NUMBER(26,6), 
	"SHIP_DLV_DISTANCE" NUMBER(26,6), 
	"ADDS_ID_SUPP" VARCHAR2(20 BYTE), 
	"DLV_TYPE" NUMBER(20,0) DEFAULT 1070, 
	"TRANS_GR_DT" DATE, 
	"DRVR_ID" VARCHAR2(50 BYTE), 
	"BUSNES_PATNR_ID" NUMBER(20,0), 
	"INV_RE_UPDTED" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"TRN_BOY_NM" VARCHAR2(250 BYTE), 
	"SO_CLSD_FRM_SHIPMNT" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"USE_OWN_TRNP" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"INTM_SHRT_CLS" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"DLVRY_BOY_NM" VARCHAR2(100 BYTE), 
	"DLVRY_BOY_CNTC" VARCHAR2(100 BYTE), 
	"RPRT_PRINT" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"RPRT_DOWNLD_CNT" NUMBER(5,0) DEFAULT 0
   ) ;

   COMMENT ON COLUMN "SLS"."SLS$SHIPMNT$HDR"."DRVR_NM" IS 'Column to store driver name';
   COMMENT ON COLUMN "SLS"."SLS$SHIPMNT$HDR"."DRVR_CNTC" IS 'Column to store Driver Contact No.';
   COMMENT ON COLUMN "SLS"."SLS$SHIPMNT$HDR"."PORT_OF_LANDING" IS 'Column to store the port of Landing of shipment';
   COMMENT ON COLUMN "SLS"."SLS$SHIPMNT$HDR"."PORT_OF_DISCHRG" IS 'Column to store the port of Discharge of the shipment';
   COMMENT ON COLUMN "SLS"."SLS$SHIPMNT$HDR"."GROSS_WT" IS 'Column to store the gross weight of the Shipment';
   COMMENT ON COLUMN "SLS"."SLS$SHIPMNT$HDR"."NET_WT" IS 'Column to store the net weight of the Shipment';
   COMMENT ON COLUMN "SLS"."SLS$SHIPMNT$HDR"."EMPTY_WT" IS 'Column to store the empty weight of the Shipment';
   COMMENT ON COLUMN "SLS"."SLS$SHIPMNT$HDR"."SHIP_DLV_DISTANCE" IS 'To Store Distance between supplier location and customer location';
   COMMENT ON COLUMN "SLS"."SLS$SHIPMNT$HDR"."ADDS_ID_SUPP" IS 'Column to Store Supplier Dispatch Location ';
   COMMENT ON COLUMN "SLS"."SLS$SHIPMNT$HDR"."DRVR_ID" IS 'To Store User defiend Driver ID';
   COMMENT ON COLUMN "SLS"."SLS$SHIPMNT$HDR"."BUSNES_PATNR_ID" IS 'Business Partner EO ID';
   COMMENT ON COLUMN "SLS"."SLS$SHIPMNT$HDR"."INV_RE_UPDTED" IS 'Flag for ammended invoice.';
   COMMENT ON COLUMN "SLS"."SLS$SHIPMNT$HDR"."TRN_BOY_NM" IS 'To store the name of turn Boy of the Transporter';
   COMMENT ON COLUMN "SLS"."SLS$SHIPMNT$HDR"."SO_CLSD_FRM_SHIPMNT" IS 'To store the flag to indicate if the Sales order is closed from shipment or not';
   COMMENT ON COLUMN "SLS"."SLS$SHIPMNT$HDR"."USE_OWN_TRNP" IS 'To use transportation Y/N';
   COMMENT ON COLUMN "SLS"."SLS$SHIPMNT$HDR"."DLVRY_BOY_NM" IS 'Stores Name Of Delivery Boy';
   COMMENT ON COLUMN "SLS"."SLS$SHIPMNT$HDR"."DLVRY_BOY_CNTC" IS 'Stores Contact Number Of Delivery Boy';
  GRANT INDEX ON "SLS"."SLS$SHIPMNT$HDR" TO "APP";
  GRANT INSERT ON "SLS"."SLS$SHIPMNT$HDR" TO "APP";
  GRANT SELECT ON "SLS"."SLS$SHIPMNT$HDR" TO "APP";
  GRANT UPDATE ON "SLS"."SLS$SHIPMNT$HDR" TO "APP";
  GRANT REFERENCES ON "SLS"."SLS$SHIPMNT$HDR" TO "APP";
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$SHIPMNT$HDR" TO "APP";
  GRANT QUERY REWRITE ON "SLS"."SLS$SHIPMNT$HDR" TO "APP";
  GRANT DEBUG ON "SLS"."SLS$SHIPMNT$HDR" TO "APP";
  GRANT FLASHBACK ON "SLS"."SLS$SHIPMNT$HDR" TO "APP";
  GRANT ALTER ON "SLS"."SLS$SHIPMNT$HDR" TO "MM";
  GRANT DEBUG ON "SLS"."SLS$SHIPMNT$HDR" TO "MM";
  GRANT DELETE ON "SLS"."SLS$SHIPMNT$HDR" TO "MM";
  GRANT FLASHBACK ON "SLS"."SLS$SHIPMNT$HDR" TO "MM";
  GRANT INDEX ON "SLS"."SLS$SHIPMNT$HDR" TO "MM";
  GRANT INSERT ON "SLS"."SLS$SHIPMNT$HDR" TO "MM";
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$SHIPMNT$HDR" TO "MM";
  GRANT QUERY REWRITE ON "SLS"."SLS$SHIPMNT$HDR" TO "MM";
  GRANT REFERENCES ON "SLS"."SLS$SHIPMNT$HDR" TO "MM";
  GRANT SELECT ON "SLS"."SLS$SHIPMNT$HDR" TO "MM";
  GRANT UPDATE ON "SLS"."SLS$SHIPMNT$HDR" TO "MM";
  GRANT ALTER ON "SLS"."SLS$SHIPMNT$HDR" TO PUBLIC;
  GRANT DELETE ON "SLS"."SLS$SHIPMNT$HDR" TO PUBLIC;
  GRANT INDEX ON "SLS"."SLS$SHIPMNT$HDR" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$SHIPMNT$HDR" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$SHIPMNT$HDR" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$SHIPMNT$HDR" TO PUBLIC;
  GRANT REFERENCES ON "SLS"."SLS$SHIPMNT$HDR" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$SHIPMNT$HDR" TO PUBLIC;
  GRANT QUERY REWRITE ON "SLS"."SLS$SHIPMNT$HDR" TO PUBLIC;
  GRANT DEBUG ON "SLS"."SLS$SHIPMNT$HDR" TO PUBLIC;
  GRANT FLASHBACK ON "SLS"."SLS$SHIPMNT$HDR" TO PUBLIC;
  GRANT ALTER ON "SLS"."SLS$SHIPMNT$HDR" TO "PMS";
  GRANT DELETE ON "SLS"."SLS$SHIPMNT$HDR" TO "PMS";
  GRANT INDEX ON "SLS"."SLS$SHIPMNT$HDR" TO "PMS";
  GRANT INSERT ON "SLS"."SLS$SHIPMNT$HDR" TO "PMS";
  GRANT SELECT ON "SLS"."SLS$SHIPMNT$HDR" TO "PMS";
  GRANT UPDATE ON "SLS"."SLS$SHIPMNT$HDR" TO "PMS";
  GRANT REFERENCES ON "SLS"."SLS$SHIPMNT$HDR" TO "PMS";
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$SHIPMNT$HDR" TO "PMS";
  GRANT QUERY REWRITE ON "SLS"."SLS$SHIPMNT$HDR" TO "PMS";
  GRANT DEBUG ON "SLS"."SLS$SHIPMNT$HDR" TO "PMS";
  GRANT FLASHBACK ON "SLS"."SLS$SHIPMNT$HDR" TO "PMS";
  GRANT ALTER ON "SLS"."SLS$SHIPMNT$HDR" TO "APP";
  GRANT DELETE ON "SLS"."SLS$SHIPMNT$HDR" TO "APP";
