--------------------------------------------------------
--  DDL for Table SLS$SO$ITM$LOT
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$SO$ITM$LOT" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"DOC_DT" DATE DEFAULT (SYSDATE), 
	"LOT_ID" VARCHAR2(20 BYTE), 
	"ITM_ID" VARCHAR2(50 BYTE), 
	"ITM_UOM" VARCHAR2(20 BYTE), 
	"ITM_QTY" NUMBER(26,6), 
	"ITM_QTY_BS" NUMBER(26,6), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"WH_ID" VARCHAR2(20 BYTE), 
	"ITM_LOT_COST" NUMBER(26,6), 
	"ITM_SR_NO" NUMBER(10,0) DEFAULT 1, 
	"CNT_QTY" NUMBER(26,6) DEFAULT 0
   ) ;
  GRANT SELECT ON "SLS"."SLS$SO$ITM$LOT" TO PUBLIC;
  GRANT INSERT ON "SLS"."SLS$SO$ITM$LOT" TO PUBLIC;
  GRANT INDEX ON "SLS"."SLS$SO$ITM$LOT" TO PUBLIC;
  GRANT DELETE ON "SLS"."SLS$SO$ITM$LOT" TO PUBLIC;
  GRANT ALTER ON "SLS"."SLS$SO$ITM$LOT" TO PUBLIC;
  GRANT FLASHBACK ON "SLS"."SLS$SO$ITM$LOT" TO PUBLIC;
  GRANT DEBUG ON "SLS"."SLS$SO$ITM$LOT" TO PUBLIC;
  GRANT QUERY REWRITE ON "SLS"."SLS$SO$ITM$LOT" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$SO$ITM$LOT" TO PUBLIC;
  GRANT REFERENCES ON "SLS"."SLS$SO$ITM$LOT" TO PUBLIC;
  GRANT INDEX ON "SLS"."SLS$SO$ITM$LOT" TO "PMS";
  GRANT INSERT ON "SLS"."SLS$SO$ITM$LOT" TO "PMS";
  GRANT SELECT ON "SLS"."SLS$SO$ITM$LOT" TO "PMS";
  GRANT UPDATE ON "SLS"."SLS$SO$ITM$LOT" TO "PMS";
  GRANT REFERENCES ON "SLS"."SLS$SO$ITM$LOT" TO "PMS";
  GRANT ON COMMIT REFRESH ON "SLS"."SLS$SO$ITM$LOT" TO "PMS";
  GRANT QUERY REWRITE ON "SLS"."SLS$SO$ITM$LOT" TO "PMS";
  GRANT DEBUG ON "SLS"."SLS$SO$ITM$LOT" TO "PMS";
  GRANT FLASHBACK ON "SLS"."SLS$SO$ITM$LOT" TO "PMS";
  GRANT ALTER ON "SLS"."SLS$SO$ITM$LOT" TO "PMS";
  GRANT DELETE ON "SLS"."SLS$SO$ITM$LOT" TO "PMS";
  GRANT UPDATE ON "SLS"."SLS$SO$ITM$LOT" TO PUBLIC;
