--------------------------------------------------------
--  DDL for Table SLS$RMA$PDR$ITM$SCHM
--------------------------------------------------------

  CREATE TABLE "SLS"."SLS$RMA$PDR$ITM$SCHM" 
   (	"CLD_ID" VARCHAR2(4 BYTE), 
	"SLOC_ID" NUMBER(2,0), 
	"ORG_ID" VARCHAR2(2 BYTE), 
	"HO_ORG_ID" VARCHAR2(2 BYTE), 
	"DOC_ID" VARCHAR2(40 BYTE), 
	"SHIP_ID" VARCHAR2(40 BYTE), 
	"SO_ID" VARCHAR2(40 BYTE), 
	"PICK_ID" VARCHAR2(40 BYTE), 
	"WH_ID" VARCHAR2(20 BYTE), 
	"ITM_ID" VARCHAR2(50 BYTE), 
	"SCHM_ID" VARCHAR2(40 BYTE), 
	"ITM_DISC_APPLIED_ON" NUMBER(5,0), 
	"ITM_DISC_VAL" NUMBER(26,6), 
	"ITM_TOT_DISC_VAL" NUMBER(26,6), 
	"USR_ID_CREATE" NUMBER(4,0), 
	"USR_ID_CREATE_DT" DATE DEFAULT SYSDATE, 
	"USR_ID_MOD" NUMBER(4,0), 
	"USR_ID_MOD_DT" DATE, 
	"ITM_SR_NO" NUMBER(10,0) DEFAULT 1
   ) ;
  GRANT INSERT ON "SLS"."SLS$RMA$PDR$ITM$SCHM" TO PUBLIC;
  GRANT SELECT ON "SLS"."SLS$RMA$PDR$ITM$SCHM" TO PUBLIC;
  GRANT UPDATE ON "SLS"."SLS$RMA$PDR$ITM$SCHM" TO PUBLIC;
